<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bota y Botn_pdpthumb lazyloaded_1_2</name>
   <tag></tag>
   <elementGuidId>8a5b307e-04bd-4489-96b6-f8d45722092b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.img-viewer.active-thumb > div.slide___3-Nqo.carousel__slide.carousel__slide--visible > div.slideInner___2mfX9.carousel__inner-slide > img.pdpthumb.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ea312f1a-874a-4a7d-b73c-cc3e8ec8b788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pdpthumb lazyloaded</value>
      <webElementGuid>f1b1b42e-6a88-4164-b4e9-743ff810c719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/lg/1114907117_3p.jpg</value>
      <webElementGuid>82c659b4-63de-4940-920d-d8db35be9b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bota corta Quirelli para hombre 4</value>
      <webElementGuid>495081c2-854d-4868-9253-6ad5fcc79b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4cb13576-58a6-42ec-a727-579ce3ac14f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/lg/1114907117_3p.jpg</value>
      <webElementGuid>f1088087-2b60-499e-9072-caa3dc04ce6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listBeforeEtalage&quot;)/div[@class=&quot;verticalSlider___34ZFD carousel__slider carousel__slider--vertical&quot;]/div[@class=&quot;carousel__slider-tray-wrapper verticalSlideTrayWrap___2nO7o carousel__slider-tray-wrap--vertical&quot;]/div[@class=&quot;sliderTray___-vHFQ sliderAnimation___300FY carousel__slider-tray verticalTray___12Key carousel__slider-tray--vertical&quot;]/li[@class=&quot;img-viewer active-thumb&quot;]/div[@class=&quot;slide___3-Nqo carousel__slide carousel__slide--visible&quot;]/div[@class=&quot;slideInner___2mfX9 carousel__inner-slide&quot;]/img[@class=&quot;pdpthumb lazyloaded&quot;]</value>
      <webElementGuid>ef89facf-009f-4b16-a2b0-dbc709f90a41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='listBeforeEtalage']/div/div/div/li[4]/div/div/img</value>
      <webElementGuid>7ad907e8-138f-4abf-a792-7d9189e512cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bota corta Quirelli para hombre 4']</value>
      <webElementGuid>7909bd86-9bb3-4e65-a843-94ef3146e0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/img</value>
      <webElementGuid>f9b1e85e-8edc-4556-8711-46c704d379d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Bota corta Quirelli para hombre 4' and @src = 'https://ss237.liverpool.com.mx/lg/1114907117_3p.jpg']</value>
      <webElementGuid>673bfa65-9dfa-4299-89fc-bfd47964b05f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
