<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pigmento</name>
   <tag></tag>
   <elementGuidId>4916b0ac-dddb-409a-846a-75b8404647c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2e0b6143-9dda-40b1-a333-7e5bbf527ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ef7f70bb-819b-42bc-9f78-d86d8fd6f2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss701.liverpool.com.mx/sm/1069561965.jpg</value>
      <webElementGuid>3a626e55-52b1-4136-83b9-3eaa0797fb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Primer M.A.C Prep + Prime Fix + Mattifying Mist</value>
      <webElementGuid>6ad4c566-3286-4d10-ada5-8b67c05b4695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_14</value>
      <webElementGuid>a0152873-42a0-4d27-b9bd-669c56c8cb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_14&quot;)</value>
      <webElementGuid>d830c78a-3e9d-4928-a26a-a4d5ea9b8c19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_14']</value>
      <webElementGuid>b61076e7-86ff-448d-865a-013eb0b4cdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[15]/a/div/figure/div/section/img</value>
      <webElementGuid>4078ebc3-9d7a-448a-9e3e-2256d3f6c67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Primer M.A.C Prep + Prime Fix + Mattifying Mist']</value>
      <webElementGuid>0135c1c5-30f5-4882-9925-22dee1b25f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/a/div/figure/div/section/img</value>
      <webElementGuid>016895e9-177a-4e00-b0b7-d024435128a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss701.liverpool.com.mx/sm/1069561965.jpg' and @alt = 'Primer M.A.C Prep + Prime Fix + Mattifying Mist' and @id = 'img_14']</value>
      <webElementGuid>0f92eced-f8ba-4109-8874-c59f29565cae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
