<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Apple Magic</name>
   <tag></tag>
   <elementGuidId>fb411dd0-cfca-42ce-9248-84a5e41dcdea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_13']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5375040d-ed36-49cf-9612-c1097a3b5410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a0f7b9c2-9cd9-43eb-b215-8ad2b4fd2d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss701.liverpool.com.mx/sm/7497894.jpg</value>
      <webElementGuid>e3405997-04a1-4a56-baa0-f164ed08923c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pigmento para ojos M.A.C Little Pigment</value>
      <webElementGuid>7bd86ee1-393b-40e8-822f-a9c7a354b267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_13</value>
      <webElementGuid>c16a8006-0cbb-4a33-9d1f-d9c72313d25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_13&quot;)</value>
      <webElementGuid>7d317216-90f9-4403-a649-377ec0daf7fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_13']</value>
      <webElementGuid>d809a56e-6efa-4210-bdda-073d73e294a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[14]/a/div/figure/div/section/img</value>
      <webElementGuid>633781d1-9fe6-48a5-8c76-d5e72d7da5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pigmento para ojos M.A.C Little Pigment']</value>
      <webElementGuid>7098d40e-c47c-4ee1-a4bb-2526be3b8e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/a/div/figure/div/section/img</value>
      <webElementGuid>3bbb34e7-e375-4cb2-a1a0-df5d685a3203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss701.liverpool.com.mx/sm/7497894.jpg' and @alt = 'Pigmento para ojos M.A.C Little Pigment' and @id = 'img_13']</value>
      <webElementGuid>d4de9f05-ddc3-4fd6-be81-14dfffcb95d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
