<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Rubor M.A.C Extra Dimension Blush_a-plus_cfe440</name>
   <tag></tag>
   <elementGuidId>c05c5345-b775-4358-bf53-622c4337363c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[12]/figure/div/div/div/ul/li[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.a-plus__icon.plp-plus__icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bdb3275e-775a-46f4-a94e-1309b2229185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-plus__icon plp-plus__icon</value>
      <webElementGuid>90481d74-4a53-4bfd-a6ee-35dc48c12a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 p-2 p-lg-1&quot;]/div[@class=&quot;o-listing__products&quot;]/ul[@class=&quot;m-product__listingPlp&quot;]/li[@class=&quot;m-product__card card-masonry a&quot;]/figure[@class=&quot;m-figureCard__figure card m-plp-product-card m-card&quot;]/div[@class=&quot;o-card__image__container&quot;]/div[1]/div[@class=&quot;a-plp-color&quot;]/ul[1]/li[@class=&quot;a-plus__icon plp-plus__icon&quot;]</value>
      <webElementGuid>0d813c44-1745-4460-a1a2-085a9b235419</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[12]/figure/div/div/div/ul/li[7]</value>
      <webElementGuid>00c30285-f072-4af6-ae70-1c708abdf85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rubor M.A.C Extra Dimension Blush'])[1]/following::li[7]</value>
      <webElementGuid>9313d98a-ab5c-49e6-adb8-3dd5974b707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple MacBook Air 13 pulgadas Full HD Intel UHD Intel Core i5 8 GB RAM 256 GB SSD'])[1]/following::li[11]</value>
      <webElementGuid>b13b4a58-af55-4763-bc0a-1e1012a1e34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple Magic Mouse Inalámbrico'])[1]/preceding::li[1]</value>
      <webElementGuid>8ca6940a-d95e-484e-a72a-99e68d980cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pigmento para ojos M.A.C Little Pigment'])[1]/preceding::li[3]</value>
      <webElementGuid>0d69e2e5-673d-44e1-b51e-b267be3cd22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/div/div/ul/li[7]</value>
      <webElementGuid>8b87df1a-7ef4-4d10-94af-273eefd56fd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
