<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paymentSection_confirmation</name>
   <tag></tag>
   <elementGuidId>a61641f5-ff75-4c7a-ab91-f72ebde6a4dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.m-box.payment-section</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='m-box payment-section']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>785ed03e-8fd1-41c1-9710-1f111465ece4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-box payment-section</value>
      <webElementGuid>cc8cd8e3-ac37-4f68-ba94-d807c81a4467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pago en efectivo:$1,349.25 (IVA incluído)Pago pendienteVence: 27 Feb 2023/23:59:59Referencia: 1010103874017249</value>
      <webElementGuid>b650de12-d6b0-4b71-a26b-c8aa4cb7d3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-confirmation-page&quot;)/div[@class=&quot;two-blocks-layout section-container&quot;]/div[@class=&quot;m-box payment-section&quot;]</value>
      <webElementGuid>433c6474-5782-4c40-83d8-d2d1131f2183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order-confirmation-page']/div[3]/div[2]</value>
      <webElementGuid>982579bf-ab68-45e2-9439-3bd48c77693e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tijuana'])[1]/following::div[1]</value>
      <webElementGuid>d4c71034-f4c9-4571-9cf2-61cdb0ee270d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJA CALIFORNIA,'])[1]/following::div[1]</value>
      <webElementGuid>41661907-b07f-445d-a2b2-602657bb241d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>a41cfe06-46b2-4442-ba24-b10b3f5c85d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pago en efectivo:$1,349.25 (IVA incluído)Pago pendienteVence: 27 Feb 2023/23:59:59Referencia: 1010103874017249' or . = 'Pago en efectivo:$1,349.25 (IVA incluído)Pago pendienteVence: 27 Feb 2023/23:59:59Referencia: 1010103874017249')]</value>
      <webElementGuid>8d29267d-b78a-4761-979e-bda85397bc5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
