<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>promotionSection_opc</name>
   <tag></tag>
   <elementGuidId>60d3fabd-2746-478a-9aeb-489165b6b5bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='a-btn a-btn--action --secondary a-checkout__btnPromotion text-promotions show  ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72e25617-d8e1-4311-a2dc-b34f699a3baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--action --secondary a-checkout__btnPromotion text-promotions show  </value>
      <webElementGuid>5322e341-a93a-495a-8978-261f2aacf29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25% de descuento.</value>
      <webElementGuid>868399ba-9daf-41b0-94ce-b5af08b18fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_productsContainer&quot;)/div[@class=&quot;col-12 m-box m-box-adjust m-checkout__productAdded pt-3&quot;]/div[@class=&quot;product-card-container&quot;]/div[@class=&quot;mt-3 pl-lg-0 product-promotion&quot;]/div[@class=&quot;m-product__giftRegistry-container d-lg-block&quot;]/div[@class=&quot;a-btn a-btn--action --secondary a-checkout__btnPromotion text-promotions show&quot;]</value>
      <webElementGuid>3953c66d-0093-4fd6-9552-d0f1dd0be575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_productsContainer']/div/div[2]/div[10]/div/div</value>
      <webElementGuid>ee059213-b59c-44fb-af2a-e1c360783e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elige una promoción'])[1]/following::div[2]</value>
      <webElementGuid>1c83b157-b14f-4d42-8373-4afd65591240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrega estimada:'])[3]/following::div[3]</value>
      <webElementGuid>5b3bbcee-f3b9-407c-8b5b-31ab8da5ae3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar para mesa de regalos'])[2]/preceding::div[1]</value>
      <webElementGuid>52fbed26-ddd0-4be3-899d-e512a6216193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div</value>
      <webElementGuid>4d39341f-ca43-4f79-915d-a910797c6e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '25% de descuento.' or . = '25% de descuento.')]</value>
      <webElementGuid>93513a21-5a03-4fb2-96ea-6b30f5593e60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
