<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PlaceOrder</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>71f3d765-7eaf-4f39-9840-53a30a0f1aa0</testSuiteGuid>
   <testCaseLink>
      <guid>0d50f863-8df7-47f9-a118-0b4b91438992</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Liverpool - orders - E2E/Card-EndToEndTestCase - QA-BT1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ea4ba994-4b1f-41d5-bac4-697f5e692979</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Liverpool - orders - E2E/Card-EndToEndTestCase - QA-SL</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ee363f1-1b26-43bb-ab82-fffdcab63e22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cc588d3-3c3d-4d82-a254-8de07212f046</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64026802-3fbb-4265-a3bd-c30634da65cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5652f1b5-1910-4b8b-a8d7-b6e87ebc2a73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bb1ea46-3a23-4cac-8d7c-7e9124eb6b76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>371dfe02-e7cf-47dd-8af9-fc62cc5c0317</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Liverpool - orders - E2E/Openpay-EndToEndTestCase - QA-BT</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bde967f0-3199-408d-857f-87e74f136c6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9089046-0402-4f9f-9199-9fa99740a0d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee5fc92f-84b0-4371-95f0-ad2db741bc40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a60557e-8dec-4772-a9fb-5a0ca04d46fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0ab8b8b-e644-4a57-a56d-ccdffbdacde6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Liverpool - orders - E2E/Openpay-EndToEndTestCase - QA-SL</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32f36411-fe04-4bd3-8f5b-9cb53d95a727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca659ded-f4af-4d05-a9bb-51f1d8bc8653</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb7689cf-7048-4971-83c3-b1b34750707e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff35ca27-9650-4cb0-bebd-210122afe9f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55323bff-f236-4c34-8783-fbde0ff97bec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Liverpool - orders - E2E/Paypal-EndToEndTestCase - QA-BT</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09e7137b-5563-47fc-bebc-8cbdbe6393c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79e65073-8e85-44da-827d-0193909f22e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05494099-7e61-4fb5-8847-1db04a32e9b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbe6f192-a260-4d52-83d2-545db989d120</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f0dac74-50a5-4dcc-b872-a51528ae7e45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e37e3387-a3d0-4f91-931b-e11053140480</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Liverpool - orders - E2E/Paypal-EndToEndTestCase - QA-SL</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b139cb5-2c8d-458b-a8e9-42c1e924b5e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d93a8f6f-cbc8-4c2c-8f08-7d78b38a37ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a595b773-d0a2-47fd-92ca-c4cc3458da17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f5c2b4c-3fef-4990-8aa0-7f8ea70dc0c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7da237b-2f82-40e9-9ead-bceba8da62dc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
