<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Comprar ahora</name>
   <tag></tag>
   <elementGuidId>86d7ed3c-e9fd-4f9e-b9e7-22bcb40a2db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sticky__button-addToExpressCart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sticky__button-addToExpressCart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e71b5cb5-2728-41e4-ba3f-074a48f973cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary</value>
      <webElementGuid>40d08427-50a4-4542-a8d8-a4810b37a905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sticky__button-addToExpressCart</value>
      <webElementGuid>d33df566-0a60-421e-a64f-fd7263feed47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprar ahora</value>
      <webElementGuid>832ad8c2-bb4a-42ab-af6e-46921bd88116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky__button-addToExpressCart&quot;)</value>
      <webElementGuid>84e62bfc-db0a-4267-a6f5-86fa0c4256ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sticky__button-addToExpressCart']</value>
      <webElementGuid>4ed8b006-23fd-4631-a03f-d90550c51738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div[3]/div/div/div[3]/div[2]/button</value>
      <webElementGuid>f35bcc7b-7082-49ee-b118-d95a88c38030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar a mi bolsa'])[1]/following::button[1]</value>
      <webElementGuid>fe401822-bf5e-4e53-bbd4-b675c538ff36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[2]</value>
      <webElementGuid>781f7fcb-cd77-4b2c-9d81-ea79137a065b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>492c601c-c205-4a47-a5a0-c0834f02279f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belleza'])[1]/preceding::button[1]</value>
      <webElementGuid>9311b26c-bdc6-45e1-bcec-4d62dead7486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comprar ahora']/parent::*</value>
      <webElementGuid>2c94cacf-2967-4404-aefd-2738e021e848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b2ae459c-d9d4-4b38-9305-0f39f751023b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sticky__button-addToExpressCart' and (text() = 'Comprar ahora' or . = 'Comprar ahora')]</value>
      <webElementGuid>f86346a6-12f1-4e54-a594-438aef5884e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
