<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Entregaestimada_cart</name>
   <tag></tag>
   <elementGuidId>5473b913-55f1-4262-9aee-98e0e68f1f5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Entrega estimada:']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mb-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b8b5684-8e44-419d-b1d8-55e2d99eeb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2</value>
      <webElementGuid>defc54f3-d2ac-406c-8d61-9cc897613c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrega estimada: </value>
      <webElementGuid>5081b0a4-a1d4-4d33-a33d-6bad9df22dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1111964218&quot;)/div[@class=&quot;o-myBag__column o-myBag__column--triple&quot;]/div[@class=&quot;o-myBag__description&quot;]/div[@class=&quot;d-none d-lg-block&quot;]/div[@class=&quot;delivery-options&quot;]/div[@class=&quot;delivery-home&quot;]/div[@class=&quot;mb-2&quot;]</value>
      <webElementGuid>ba5860ab-920b-4307-8702-e95f9ccdcfc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1111964218']/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>64c3c82c-f5b4-454e-baf2-8541ef9ce595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::div[9]</value>
      <webElementGuid>24927a95-35cf-474a-938e-6befa8390352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad'])[1]/following::div[9]</value>
      <webElementGuid>921c659d-aac2-4251-a939-86615547e968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más opciones de entrega'])[1]/preceding::div[1]</value>
      <webElementGuid>8d7522b0-8524-4b62-b665-3f692887f1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar para mesa de regalos'])[1]/preceding::div[3]</value>
      <webElementGuid>cf8fc2c6-47ce-489f-918d-28f21f6afa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrega estimada:']/parent::*</value>
      <webElementGuid>308e85c1-44f7-4a34-9ae6-1ddcb116b692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>bbf93694-2ef1-449d-b6b6-03df5c92d2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Entrega estimada: ' or . = 'Entrega estimada: ')]</value>
      <webElementGuid>db6837ba-0dc1-4714-a00b-d092b6e09119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
