<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>myBagImageProduct_cart</name>
   <tag></tag>
   <elementGuidId>2cd12f2a-09d2-4af7-8f32-10bcea2202fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.a-myBagImageProduct</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='alt-Description'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3f618c4-b10e-4774-a03d-82ff512328ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/lg/1111964187.jpg</value>
      <webElementGuid>d2a183b6-5a5b-4426-8e36-475e30326625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>alt-Description</value>
      <webElementGuid>f0768cb7-fd93-44fe-99e8-173c0992e0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-myBagImageProduct</value>
      <webElementGuid>03ea2c2f-90e3-432c-93f6-173a632d3d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nonclickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4e729e0-53b3-40cf-9a74-ad5c6ef44719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1111964218&quot;)/div[@class=&quot;o-myBag__column o-myBag__column--triple&quot;]/div[@class=&quot;o-myBag__image&quot;]/figure[@class=&quot;m-imageProductMyBag&quot;]/img[@class=&quot;a-myBagImageProduct&quot;]</value>
      <webElementGuid>732fe47b-84b4-48a3-92eb-b4592a85f926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1111964218']/div/div/figure/img</value>
      <webElementGuid>8bf8bb87-d46b-4495-8305-78fcb339ae62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='alt-Description']</value>
      <webElementGuid>e01e6ba8-0c76-4871-ae14-69b9b90bd31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>564cb7ef-5939-43b5-a8db-f1a3e468d9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss237.liverpool.com.mx/lg/1111964187.jpg' and @alt = 'alt-Description']</value>
      <webElementGuid>4502935a-e7f3-4a19-8b71-d984586488a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
