<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AGUASCALIENTES</name>
   <tag></tag>
   <elementGuidId>a4c09792-7c25-41d9-a913-de5cdb20ace5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filters-storeLocator-storeInformation']/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-product__anchorSelectState</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7660ef74-aeec-4c4d-ac03-4b7d1286f7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-product__anchorSelectState</value>
      <webElementGuid>8cf2e402-23a1-45e7-8c0d-e1b97c30210c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>b2437680-b7d9-4ef9-aa6e-1c25c2eb9cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#availability-modal</value>
      <webElementGuid>0bd6b2ce-65e9-41f7-864d-58ced758f36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/home#!</value>
      <webElementGuid>229c8c2d-7647-4343-adec-412623596125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AGUASCALIENTES</value>
      <webElementGuid>ddd19ab6-10d3-4d58-8a01-909a8ef9ffa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filters-storeLocator-storeInformation&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content storeInformation_modal&quot;]/div[@class=&quot;modal-body p-0 select_states-body&quot;]/a[@class=&quot;a-product__anchorSelectState&quot;]</value>
      <webElementGuid>3b77bd70-1c19-4bad-91c6-c36f921b9d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filters-storeLocator-storeInformation']/div/div/div[2]/a</value>
      <webElementGuid>e5b594c2-4f40-483e-95ae-e674bd34b536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AGUASCALIENTES')]</value>
      <webElementGuid>a534a7a6-4586-4134-8c64-6310bd7dc2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona tu estado'])[2]/following::a[1]</value>
      <webElementGuid>1f90f5c9-00c1-4700-993f-120bf0a6855e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/following::a[1]</value>
      <webElementGuid>ee5053a5-b8f3-4b16-afe6-8e7125c6dc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJA CALIFORNIA'])[1]/preceding::a[1]</value>
      <webElementGuid>2c19fb5f-fde2-41bf-b597-9a33434d2596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJA CALIFORNIA SUR'])[1]/preceding::a[2]</value>
      <webElementGuid>f9b38a7d-a8e7-428c-8ae5-4b791c70869d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AGUASCALIENTES']/parent::*</value>
      <webElementGuid>d54defa0-19ab-4205-a1e1-d7caf8fd153f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/home#!')])[688]</value>
      <webElementGuid>7a6fa1c4-953e-4115-92f6-cf4c3b6655a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/a</value>
      <webElementGuid>77f3cea3-d470-4ce0-91ab-7f75746b1827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/home#!' and (text() = 'AGUASCALIENTES' or . = 'AGUASCALIENTES')]</value>
      <webElementGuid>7ae8e65f-d91e-47b6-88eb-080f76690a0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
