<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_COLIMA</name>
   <tag></tag>
   <elementGuidId>39913191-48bb-4c94-8674-726742c62b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filters-storeLocator-storeInformation']/div/div/div[2]/a[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04eba4ae-35a3-4d01-8874-5257fc436d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-product__anchorSelectState</value>
      <webElementGuid>17772585-0a54-4966-ac69-6f2650404ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>6cdfe0d1-0cfe-45a6-a6c5-b14ac004d193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#availability-modal</value>
      <webElementGuid>66e975ce-320d-47b3-9ffa-5efb1ecba5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/home#!</value>
      <webElementGuid>4f11fa6b-31e8-4843-9b66-e720a4e5bb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COLIMA</value>
      <webElementGuid>e1e0a558-da3b-4ea2-95c2-9547758aca59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filters-storeLocator-storeInformation&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content storeInformation_modal&quot;]/div[@class=&quot;modal-body p-0 select_states-body&quot;]/a[@class=&quot;a-product__anchorSelectState&quot;]</value>
      <webElementGuid>3ef6a6dc-f640-4327-a34c-9d8c74293010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filters-storeLocator-storeInformation']/div/div/div[2]/a[6]</value>
      <webElementGuid>fae2cdff-265f-4bba-9562-e1e80a6b3f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'COLIMA')]</value>
      <webElementGuid>c97c0eac-d49e-4939-9fb5-66b8e7e753c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COAHUILA'])[1]/following::a[1]</value>
      <webElementGuid>98a80ca6-310d-4590-9590-97015c272aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAMPECHE'])[1]/following::a[2]</value>
      <webElementGuid>506f05ef-6329-4bc6-8d3e-f50596dcca01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHIAPAS'])[1]/preceding::a[1]</value>
      <webElementGuid>d95f0bb8-9c3b-4dc2-b059-86aa344d7242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHIHUAHUA'])[1]/preceding::a[2]</value>
      <webElementGuid>66fbdf7b-ec1a-4eed-a49f-df5e4bcdc5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COLIMA']/parent::*</value>
      <webElementGuid>e441eabe-0753-4273-820d-0e54c43c5bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/home#!')])[655]</value>
      <webElementGuid>40db72b2-ad4f-4670-b5d1-e0fdc75e75a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>78fb2557-d65c-4a58-a900-9f7f861c13b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/home#!' and (text() = 'COLIMA' or . = 'COLIMA')]</value>
      <webElementGuid>57da5d28-bb4c-4831-bc1a-6ed32a5ec221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
