<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buscar</name>
   <tag></tag>
   <elementGuidId>d8a8841e-486a-4b55-a35c-52d6498a0da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='mdc-tab store-tab  mdc-tab--active opc__header__tabs__item header__tabs__store ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mdc-button.a-btn__primary.m-eddBox__updateButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>799032a6-fcf0-4537-a91b-3527476c23c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-button a-btn__primary m-eddBox__updateButton</value>
      <webElementGuid>f0e45443-f7e6-462d-83ac-dc520bb52585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>ba8cf100-924c-4380-80e7-a1d28a54d6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ciudad_tienda&quot;)/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-4 col-lg-4 pl-2 pl-lg-2&quot;]/button[@class=&quot;mdc-button a-btn__primary m-eddBox__updateButton&quot;]</value>
      <webElementGuid>377bafd3-9387-4fa1-a961-74cf5880328b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ciudad_tienda']/div/div[2]/button</value>
      <webElementGuid>67c14f13-189c-41bb-a7dc-00d30e9d31cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C.P. Ciudad o Tienda'])[2]/following::button[1]</value>
      <webElementGuid>60e07ee3-e1ed-4d21-b9dc-74d77ba76036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/following::button[1]</value>
      <webElementGuid>8f7c5f1a-3022-43d6-95d5-dfc06805d7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar por mi ubicación actual'])[1]/preceding::button[1]</value>
      <webElementGuid>4ca565fa-88cc-4afa-b1d2-8fc3d000a285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>e5d180ba-4eb4-4ddc-861b-e318ec9b7fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Buscar' or . = 'Buscar')]</value>
      <webElementGuid>798dd8b3-eaa5-40ed-a861-7ebfe86a4d6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
