<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>footer_name_not.com_CLP</name>
   <tag></tag>
   <elementGuidId>fb1033db-caab-4dff-85e6-884577d35cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='min-vh-100']//h6[contains (text(),'.com')]//b)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>9cdf9526-6dd0-4c98-89af-b574172cfb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mujer en Liverpool.com.mx</value>
      <webElementGuid>695e5c22-3f78-41b1-b8cb-8b93d1e2cc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;o-blp-mainContent order-1 order-lg-2 px-0 px-lg-0 d-none d-lg-block&quot;]/div[@class=&quot;slotdiv d-none d-lg-block&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-12-sm seoRow d-none d-lg-block&quot;]/div[@class=&quot;seoText&quot;]/h6[2]</value>
      <webElementGuid>7656d500-43a9-4195-b192-744fddfb6783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[4]/main/div[5]/div/div[2]/div/div/h6[2]</value>
      <webElementGuid>a9f4ab89-cdad-4f62-8005-a3aff7694a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tendencia'])[2]/following::h6[1]</value>
      <webElementGuid>ffe08840-62cd-41f3-9fce-664f107c5cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aéropostale, Banana Republic, GAP, Chico´s'])[2]/following::h6[1]</value>
      <webElementGuid>38af930b-3887-4a70-bbb4-646e3d0136ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte al cliente'])[1]/preceding::h6[1]</value>
      <webElementGuid>e16090d7-5aa7-46d3-acb5-8cad5e5a72f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/h6[2]</value>
      <webElementGuid>1ee0dbb5-3978-4304-a8b0-daddb0bda097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Mujer en Liverpool.com.mx' or . = 'Mujer en Liverpool.com.mx')]</value>
      <webElementGuid>ef3c2ea8-6534-410e-87ab-b1160212e34e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
