<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubCategory4_leftmenu_CLP</name>
   <tag></tag>
   <elementGuidId>239f0bb2-2c9a-4fb1-b0b6-dddf2ffcf667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@class='nav-sub-options-leftMenu pl-40 ']//li[@class='nav-sub-link-leftMenu'][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>26b602c0-9ffe-4501-9079-a00f4dbe89a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678034382017</value>
      <webElementGuid>57101640-6114-4e0d-be36-518ae5ed4cef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
