<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubCategory5_leftmenu_CLP</name>
   <tag></tag>
   <elementGuidId>64fb76e3-61e0-41c7-9ea9-1abbf1345218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='nav-sub-link-leftMenu'][5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>800db545-d1aa-4507-b00c-2798e19b2fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678034384682</value>
      <webElementGuid>2ea044e1-5524-41d8-8c9f-42861626dded</webElementGuid>
   </webElementProperties>
</WebElementEntity>
