<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Compartir_pdp</name>
   <tag></tag>
   <elementGuidId>664466ee-be24-4778-9177-f1406a1a5d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*/text()[normalize-space(.)='Compartir']/parent::*)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ml-1.a-product__labelProductShareWeb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0fba56ff-80d0-4278-b8e5-f605681d78c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-1 a-product__labelProductShareWeb</value>
      <webElementGuid>e3642c01-234c-4e21-bc0a-a396bc712d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compartir</value>
      <webElementGuid>35ab7264-f1c3-4ddf-a817-b9964542fe90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/div[@class=&quot;mt-4 d-none d-lg-block&quot;]/a[@class=&quot;m-product__anchorShareSocial&quot;]/span[@class=&quot;ml-1 a-product__labelProductShareWeb&quot;]</value>
      <webElementGuid>2cb1fdbb-2d0f-4652-9be7-a6738e24d340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/div[12]/a/span</value>
      <webElementGuid>04c6dd05-f419-45a9-a150-ae84f2d4c355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más información'])[1]/following::span[1]</value>
      <webElementGuid>8bd10ee3-a4ff-469d-b80e-9519cd002186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[3]/following::span[1]</value>
      <webElementGuid>eb7018d7-a3d6-440c-a9cd-424cf5aa4d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recibe a domicilio'])[1]/preceding::span[1]</value>
      <webElementGuid>b14cbacb-586b-43af-ba4f-094bfaa5a8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compartir']/parent::*</value>
      <webElementGuid>66194074-84f3-4e37-a997-d09004b68a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>ddedb8d0-8364-472b-9871-f4e0366dfe1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Compartir' or . = 'Compartir')]</value>
      <webElementGuid>6ea17581-2354-4d80-a30c-afe7b21117f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
