<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Mesa de regalos   Mi crdito    Servicios_01b361</name>
   <tag></tag>
   <elementGuidId>70768d88-32fd-4f4a-9f8e-942e77babfd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.o-col.px-0.text-left.col-lg-5.col-xl-6 > ul.m-navDesktop__menuList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>cc23827d-2838-44a6-acd9-130fb9fe9e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-navDesktop__menuList</value>
      <webElementGuid>c9b5ee44-5067-41b6-9279-d01a104cec70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Mesa de regalos   Mi crédito    Servicios  Centro de Seguros   Tiempo aire   Viajes   Citas en tienda   Diseño de interiores   Sorteos y concursos   Centro de Seguros   Tiempo aire   Viajes   Citas en tienda   Diseño de interiores   Sorteos y concursos    BYD </value>
      <webElementGuid>9dcfa63e-1cbc-4741-96d5-055314b88a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[1]/div[@class=&quot;o-header noSearchBar d-flex align-items-center d-lg-block&quot;]/div[@class=&quot;o-container__fluid container-fluid wrap-megamenu d-none d-lg-block&quot;]/div[@class=&quot;o-container container p-0&quot;]/nav[@class=&quot;m-megamenu&quot;]/div[@class=&quot;o-row row align-items-center&quot;]/div[@class=&quot;o-col col-lg-10 col-xl-9 pr-0&quot;]/div[@class=&quot;o-row row&quot;]/div[@class=&quot;o-col col-lg order-lg-2 pt-3 pt-lg-0&quot;]/div[@class=&quot;o-row row&quot;]/div[@class=&quot;o-col px-0 text-left col-lg-5 col-xl-6&quot;]/ul[@class=&quot;m-navDesktop__menuList&quot;]</value>
      <webElementGuid>44e976d5-43b7-4759-909f-88bd2f714f59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[3]/div[2]/div/nav/div/div/div/div[2]/div/div/ul</value>
      <webElementGuid>c26311c2-9a0f-4838-8685-1b91d9a2d41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver todas las secciones'])[15]/following::ul[1]</value>
      <webElementGuid>886b11d1-232d-4193-a8ac-b0279b074267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muebles'])[3]/following::ul[1]</value>
      <webElementGuid>1eec1dd8-74d7-4b9a-a3e5-cc82af58c979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul</value>
      <webElementGuid>51e1eea7-f33e-4113-ab1c-035cbab109a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = '  Mesa de regalos   Mi crédito    Servicios  Centro de Seguros   Tiempo aire   Viajes   Citas en tienda   Diseño de interiores   Sorteos y concursos   Centro de Seguros   Tiempo aire   Viajes   Citas en tienda   Diseño de interiores   Sorteos y concursos    BYD ' or . = '  Mesa de regalos   Mi crédito    Servicios  Centro de Seguros   Tiempo aire   Viajes   Citas en tienda   Diseño de interiores   Sorteos y concursos   Centro de Seguros   Tiempo aire   Viajes   Citas en tienda   Diseño de interiores   Sorteos y concursos    BYD ')]</value>
      <webElementGuid>e884ed32-801c-4c7e-a65b-2488d8b54ffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
