<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finalizar compra</name>
   <tag></tag>
   <elementGuidId>df60fe8f-0e3c-46d7-abf5-261d4218cfc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitForOther']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submitForOther</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99bfbb04-9903-4941-8857-91e0ff8e890d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary</value>
      <webElementGuid>881626bd-49ec-4abe-840b-79b6ac079091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitForOther</value>
      <webElementGuid>62c09b23-8d6e-4d66-b21e-1a3e60ec9986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finalizar compra</value>
      <webElementGuid>78a99206-2b66-4258-b996-4d654a15dacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitForOther&quot;)</value>
      <webElementGuid>74d118c2-1ea8-4bb1-b5d6-e9564e6b4201</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitForOther']</value>
      <webElementGuid>605fbc21-fad4-4282-b3e3-5cb650be4efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_container']/div[7]/div[2]/div/div[4]/div[2]/button</value>
      <webElementGuid>9a0bd363-114d-4a13-919c-5e9b441dc214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos, Condiciones y Aviso de Privacidad'])[1]/following::button[1]</value>
      <webElementGuid>635c6939-79f8-4f8f-a0eb-b604929a423f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$29.40'])[2]/following::button[1]</value>
      <webElementGuid>9579d824-106e-4bf2-940e-b17c8051e781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambios, devoluciones y cancelaciones'])[1]/preceding::button[1]</value>
      <webElementGuid>fd18b2c5-f81f-4208-99ed-4a6fa9d4cd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preguntas frecuentes'])[1]/preceding::button[1]</value>
      <webElementGuid>603f5da4-8bfa-4a4a-ac04-30a9bd5e47df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalizar compra']/parent::*</value>
      <webElementGuid>18757f69-73c8-431d-97a3-b27dbb65ea7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/button</value>
      <webElementGuid>7e3869a8-bf66-4471-9eb5-772ba34246fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submitForOther' and (text() = 'Finalizar compra' or . = 'Finalizar compra')]</value>
      <webElementGuid>1d94151d-05a1-46ee-becd-1feffecacbab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
