<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>discountLabel_opc</name>
   <tag></tag>
   <elementGuidId>b0bac953-d414-414f-bb58-272fa2f8f935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='m-breakdownExpenses__detail']//p[contains(text(),'Descuento:')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c8a6c8a6-37c2-4b9e-a64b-482fd8731e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-inlineElement -enphasisDecimal</value>
      <webElementGuid>59ed3de1-48f2-4930-9a43-b519e08d0a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descuento:</value>
      <webElementGuid>1b454cba-cd83-418d-8781-758890ea4881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_buysummary&quot;)/div[@class=&quot;m-breakdownExpenses w-100 mt-0&quot;]/div[@class=&quot;m-breakdownExpenses__detail&quot;]/div[@class=&quot;m-breakdownExpenses__description&quot;]/div[@class=&quot;m-breakdownExpenses__column--priceContainer&quot;]/p[@class=&quot;a-inlineElement -enphasisDecimal&quot;]</value>
      <webElementGuid>6887b2de-ccbc-4dd5-8d87-159ad1777ec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_buysummary']/div[2]/div/div/div[2]/p</value>
      <webElementGuid>783bef09-02f9-4a3d-af39-09c545f546e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2 disponibles)'])[1]/following::p[2]</value>
      <webElementGuid>51a34989-a2b3-45bc-8482-391a5723a59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cupones'])[1]/following::p[2]</value>
      <webElementGuid>437ea06c-a99d-4310-84e4-d770ad46add4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirma tu compra'])[2]/preceding::p[10]</value>
      <webElementGuid>2181f3f0-9c00-4114-89be-8333cc7ec786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/preceding::p[10]</value>
      <webElementGuid>f432b601-4e57-4573-b3e0-06c50e42d38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descuento:']/parent::*</value>
      <webElementGuid>b2005881-cdf1-4061-acf6-d7081da6904c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/p</value>
      <webElementGuid>54ca8057-4865-4aa7-9b86-3a4ed1990c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Descuento:' or . = 'Descuento:')]</value>
      <webElementGuid>ef1905f6-4190-4b51-9630-8957c69efdac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
