<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subTotalPrice_opc</name>
   <tag></tag>
   <elementGuidId>8b64de60-4ec7-4f0f-8fe0-84d8de9fec5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='m-breakdownExpenses__column--priceContainer']//p)[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.a-inlineElement.-enphasisDecimal.-alignDecimal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8d530b04-f34d-48e0-8443-6d3da12f8074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-inlineElement -enphasisDecimal -alignDecimal</value>
      <webElementGuid>1cbddb80-e38f-47f3-b667-cbb2fe974f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$49.00</value>
      <webElementGuid>6c06c325-debf-47bf-86f9-1354de3894cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_buysummary&quot;)/div[@class=&quot;m-breakdownExpenses w-100 mt-0&quot;]/div[@class=&quot;m-breakdownExpenses__detail&quot;]/div[@class=&quot;m-breakdownExpenses__quantity&quot;]/div[@class=&quot;m-breakdownExpenses__column--priceContainer&quot;]/p[@class=&quot;a-inlineElement -enphasisDecimal -alignDecimal&quot;]</value>
      <webElementGuid>bd00e1a1-c50c-4079-851e-e57662a9e374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_buysummary']/div[2]/div/div[2]/div/p</value>
      <webElementGuid>9dd48b79-74ef-473c-b05f-cca4f3ca28f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2 disponibles)'])[1]/following::p[5]</value>
      <webElementGuid>0af3aeb7-efbb-4223-bf9b-5fcbcb27e3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cupones'])[1]/following::p[5]</value>
      <webElementGuid>89aab19f-52a0-4993-be4d-a74f79447522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirma tu compra'])[2]/preceding::p[7]</value>
      <webElementGuid>795ad18e-0dfb-4fcf-bbf2-1bf8214c9200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/preceding::p[7]</value>
      <webElementGuid>0321741d-045e-4de8-8515-5d942cdda400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$']/parent::*</value>
      <webElementGuid>a8e69ef3-2cde-4561-9632-592ad4a5a622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/p</value>
      <webElementGuid>863df0b8-d613-43f2-ac67-7dd22d5037de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '$49.00' or . = '$49.00')]</value>
      <webElementGuid>c6184766-4cb1-46d4-a276-78e2aaf244da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
