<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Calificacin_icon-arrow_up_1</name>
   <tag></tag>
   <elementGuidId>47ada9c5-183f-4a5b-b191-77fc6a0dae19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[29]/div/div/button/h3/div/div[2]/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bf06c85c-d412-407b-856c-e8ccf9198bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow_up</value>
      <webElementGuid>281ad577-13ab-4e77-9d98-4a4bf47dd74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-4 m-aside__content&quot;]/div[@class=&quot;m-plp-cat-container d-none d-lg-block mb-5&quot;]/div[@class=&quot;o-aside d-aside--margin&quot;]/div[@class=&quot;m-plp__filterSection&quot;]/div[@class=&quot;m-plp__filterSection&quot;]/div[@class=&quot;a-plp__btnFilter&quot;]/button[@class=&quot;a-title__filter&quot;]/h3[@class=&quot;m-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-auto&quot;]/div[@class=&quot;a-icon__filter down&quot;]/i[@class=&quot;icon-arrow_up&quot;]</value>
      <webElementGuid>82afa954-4219-493b-b937-d80fb8fb7ce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[29]/div/div/button/h3/div/div[2]/div/i</value>
      <webElementGuid>8bc377ad-bd25-4503-8a78-4b446199282a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/div/div/button/h3/div/div[2]/div/i</value>
      <webElementGuid>9a669492-436e-4f23-af83-e7f28f044602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
