<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadCrumb_blp</name>
   <tag></tag>
   <elementGuidId>e2c28d44-41bc-49b9-b2e5-da93dbf581e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='m-breadcrumb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.m-breadcrumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3329de15-6d70-49d5-a3c9-5510eb501cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-breadcrumb</value>
      <webElementGuid>5abcc6be-e9f9-4143-afee-63af244264e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Home   Mujer </value>
      <webElementGuid>e7619c2c-ae6f-47c1-bd16-fb4c93dcb4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row d-none d-lg-block m-row-bootstrap&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row p-0&quot;]/div[@class=&quot;m-breadcrumb&quot;]</value>
      <webElementGuid>a63f970f-b7d0-49aa-8c56-936682955156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>fd30cb60-b621-4cc7-8e1c-010635bc7a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver todo'])[1]/following::div[5]</value>
      <webElementGuid>9fd3754f-9818-435c-a027-abec6b571c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sal de tu zona de confort y atrévete.'])[1]/following::div[8]</value>
      <webElementGuid>36a18c4e-0673-42e5-8a71-7a33e6cb950f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div</value>
      <webElementGuid>dc9a336f-4545-4858-91de-ca8772782557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Home   Mujer ' or . = '  Home   Mujer ')]</value>
      <webElementGuid>fde139f0-9ce1-4e91-93cc-847993dced15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
