<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_SalesForce</name>
   <tag></tag>
   <elementGuidId>8976fb23-7080-4e9c-a0f0-08933703b289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idToken2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idToken2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db569033-fe3d-41d9-91e4-682dadab7f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7c171ace-f7d6-49c7-9954-34353c37e569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idToken2</value>
      <webElementGuid>ba2a1b63-76cb-4795-ade1-9c9bbabe0967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>callback_1</value>
      <webElementGuid>7e4abb39-46b5-4bda-acc1-2c6ffe12f412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validator</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5247ea67-2d39-4b16-8f44-40bb6f6e6ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validator-event</name>
      <type>Main</type>
      <value>keyup</value>
      <webElementGuid>a658b3c8-8a74-449a-bea7-dd15e7e0c126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>1cdf41a7-d16e-478e-adaf-281a1a6cf813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>396cd646-9e4b-4217-9b17-1fa50cc41fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71733522-fefc-417f-bd9a-5f2b91233649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idToken2&quot;)</value>
      <webElementGuid>05af1779-2f29-4cae-95be-b4474bce3500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idToken2']</value>
      <webElementGuid>21938682-3536-4697-ad67-5ad956b07768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/form/fieldset/div/div/input</value>
      <webElementGuid>5642f765-c970-4754-a15e-5aaee3e26249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8fc2576a-a18c-4d20-8c20-d0032fe7925e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'idToken2' and @name = 'callback_1' and @placeholder = 'Password']</value>
      <webElementGuid>99904143-78d0-4935-84e4-51d229c36aec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
