<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verify</name>
   <tag></tag>
   <elementGuidId>f52da7e7-537b-4e54-8ac6-53971b90f791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_brand.slds-p-vertical_x-small.brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea933b6f-1368-440d-9d71-f25ca48074a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ba5f7745-01aa-4829-9510-c63ab703e642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand slds-p-vertical_x-small brand</value>
      <webElementGuid>93b9a97a-1fb2-4cc4-b370-7a207aa42662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>dce5e282-2e6f-4627-816e-63c78789d8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/vaasdist-verify[1]/div[@class=&quot;main&quot;]/vaas-verify[1]/div[1]/vaas-sfa-check-verify[1]/vaas-sfa-check[1]/vaas-container[1]/div[@class=&quot;slds-p-around_large container&quot;]/div[1]/slot[1]/div[@class=&quot;slds-box content&quot;]/vaas-sfa-totp-fallback[1]/div[@class=&quot;slds-box container&quot;]/form[1]/div[@class=&quot;slds-m-top_medium&quot;]/vaas-button-brand[@class=&quot;half&quot;]/button[@class=&quot;slds-button slds-button_brand slds-p-vertical_x-small brand&quot;]</value>
      <webElementGuid>f4f2a70f-2074-4f3a-9796-12899815fc19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>8fe3d0ad-b71d-4916-819d-e8effdf3aa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/vaasdist-verify/div/vaas-verify/div/vaas-sfa-check-verify/vaas-sfa-check/vaas-container/div/div/slot/div/vaas-sfa-totp-fallback/div[2]/form/div/vaas-button-brand/button</value>
      <webElementGuid>2c4ea68d-1b9b-4964-a9ec-3319f7505a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>5f9fd257-c63f-4244-bfec-405f8bcf2e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification Code'])[1]/following::button[2]</value>
      <webElementGuid>bc86767b-b4f3-4d7c-9563-6155efdefb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Verification'])[1]/preceding::button[1]</value>
      <webElementGuid>c07c9459-43b5-4522-b212-f11061b221b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//vaas-button-brand/button</value>
      <webElementGuid>19a2d061-9c56-4dc1-ae41-42bb5dac0ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>ce6a2054-3f97-4d10-b23a-9404e0867c24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
