<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product3_PLP (1)</name>
   <tag></tag>
   <elementGuidId>c377572b-4790-4ce9-8cdf-7580886d2186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='m-product__card card-masonry a'][3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>337be1c0-dfbb-4b86-b9b7-08c462758091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>6cb93374-e786-405e-9623-578a9597ae6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss628.liverpool.com.mx/sm/1131665608.jpg</value>
      <webElementGuid>7d3e6d34-77e8-4ab1-b082-672742375a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Laptop Huawei Nobele-wfh9al 14 pulgadas full hd Intel Core I5 Intel Iris Xe 16 GB RAM 512 GB SSD</value>
      <webElementGuid>17f17086-a07a-4635-a09a-1694d7d35a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_0</value>
      <webElementGuid>2f186c6a-b57b-4ff0-96f3-388f50023573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_0&quot;)</value>
      <webElementGuid>28b9d576-1a5f-4b8e-9d1e-9ea96a16ced8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_0']</value>
      <webElementGuid>4e6fe1a2-6b9e-4152-ab2b-1a987f52e0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li/a/div/figure/div/section/img</value>
      <webElementGuid>f92f3925-0c0a-408a-a851-40ae747fdd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Laptop Huawei Nobele-wfh9al 14 pulgadas full hd Intel Core I5 Intel Iris Xe 16 GB RAM 512 GB SSD']</value>
      <webElementGuid>16bf44ed-1928-4e8f-af34-9bb31fb8734f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/img</value>
      <webElementGuid>bc68fbde-1d95-46e5-a727-6c414268086b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss628.liverpool.com.mx/sm/1131665608.jpg' and @alt = 'Laptop Huawei Nobele-wfh9al 14 pulgadas full hd Intel Core I5 Intel Iris Xe 16 GB RAM 512 GB SSD' and @id = 'img_0']</value>
      <webElementGuid>5290c234-ce7d-4e0d-8885-8b48e25e1b36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
