<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product2_PLP</name>
   <tag></tag>
   <elementGuidId>44a56429-6a33-4d67-aece-b88fa13c7ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='m-product__card card-masonry a'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f339d46d-6d42-467c-aa6d-f24c9c35f4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678040710443</value>
      <webElementGuid>6e472614-1119-4f50-a2a1-3d4d5adad270</webElementGuid>
   </webElementProperties>
</WebElementEntity>
