<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product4_PLP</name>
   <tag></tag>
   <elementGuidId>12f5a719-4118-499f-b6d1-413188107c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@class='m-product__card card-masonry a'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8704d9e5-7f09-442c-b387-5df80ca5baaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678040710443</value>
      <webElementGuid>614c8874-17d5-43f1-bc90-cd7e59ccfe02</webElementGuid>
   </webElementProperties>
</WebElementEntity>
