<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product1_PLP (1)</name>
   <tag></tag>
   <elementGuidId>4dff5e21-b92f-430e-b407-0963ff235396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='m-product__card card-masonry a'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ea35f78c-daff-4a50-9bd2-023847430535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>311f86af-5c46-4a7d-a56d-b4c7bcde548a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss628.liverpool.com.mx/sm/1131665608.jpg</value>
      <webElementGuid>2f27122a-e627-4d59-81fe-44e4920e1b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Laptop Huawei Nobele-wfh9al 14 pulgadas full hd Intel Core I5 Intel Iris Xe 16 GB RAM 512 GB SSD</value>
      <webElementGuid>242828d6-d6ed-4cc5-b524-942af650fc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_0</value>
      <webElementGuid>20836d4b-2e1c-4c9f-a679-61d1e6e87186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_0&quot;)</value>
      <webElementGuid>a645dc6b-bc1d-46e3-85fc-e19b1f11886a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_0']</value>
      <webElementGuid>f23fd9ab-6a32-4ae8-91b1-25289b2ac64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li/a/div/figure/div/section/img</value>
      <webElementGuid>6253e975-ee8b-491e-9656-27c77aeb700e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Laptop Huawei Nobele-wfh9al 14 pulgadas full hd Intel Core I5 Intel Iris Xe 16 GB RAM 512 GB SSD']</value>
      <webElementGuid>a4ee2530-f207-4032-bd82-a35d8b631506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/img</value>
      <webElementGuid>e3557391-4d0b-43c9-b61b-6ab5c582fe50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss628.liverpool.com.mx/sm/1131665608.jpg' and @alt = 'Laptop Huawei Nobele-wfh9al 14 pulgadas full hd Intel Core I5 Intel Iris Xe 16 GB RAM 512 GB SSD' and @id = 'img_0']</value>
      <webElementGuid>ea06c83e-8841-49a4-b4e4-076bfd6e25cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
