<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product5_PLP</name>
   <tag></tag>
   <elementGuidId>f0070c6e-d830-4f5a-888a-96081df64c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@class='m-product__card card-masonry a'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>51c6461f-6e1d-4884-bc1d-c9d6f0080422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678040710443</value>
      <webElementGuid>be8a82bb-5300-46ff-a59e-21f4230fb9d9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
