<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product1_PLP</name>
   <tag></tag>
   <elementGuidId>ba048748-85f4-4f18-b7a2-a997543af885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@class='m-product__card card-masonry a'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>9940145b-be3a-4f3c-9980-16d2ae03a0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678040710443</value>
      <webElementGuid>a7e78672-72d2-4ebd-93d9-2bb34fed28c3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
