<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product3_PLP</name>
   <tag></tag>
   <elementGuidId>149396aa-b0c1-4093-b86e-11683eb8cf1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='m-product__card card-masonry a'][3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a2065240-e6b6-49bc-b410-a84b79dc26a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678040710443</value>
      <webElementGuid>83e66d9f-babe-44b5-bc2c-03ca9256fa0f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
