<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>l3Category_clp</name>
   <tag></tag>
   <elementGuidId>777b77be-c050-4c96-9866-f76108017d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div/img)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>47829cfc-3759-4a16-8360-84924017a41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0855f15c-a7d8-4790-8c07-e04d28a90247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.liverpool.com.mx/assets/images/categorias/damas/catst4003357.jpg</value>
      <webElementGuid>a4ca9bcd-ecba-4f55-abd9-c089f23a6fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tenis</value>
      <webElementGuid>102dec46-d29d-4265-86bf-d0af516ec195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>21752d81-65ba-49ee-afd1-3126f52820f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/main[1]/div[@class=&quot;container-fluid o-main-container p-0 o-clp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[1]/div[@class=&quot;row mt-lg-3 m-row-bootstrap leftMenu-clpMobile&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent clp_headband&quot;]/div[@class=&quot;o-clp-mainContent&quot;]/section[@class=&quot;clp_body&quot;]/div[@class=&quot;o-cards-row o-clp-cards-row mt-lg-4&quot;]/div[@class=&quot;o-clp-cards-row_container&quot;]/div[1]/figure[@class=&quot;m-figureCard__figure card  m-card&quot;]/a[1]/div[@class=&quot;lazyload-wrapper&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>850bc4db-6a5a-4329-8fa0-3bce78e8a972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div/div[2]/div/div[2]/section/div/div/div/figure/a/div/img</value>
      <webElementGuid>076caba2-4614-4d99-a47a-5f37dbb0417d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tenis']</value>
      <webElementGuid>ce5f1f6d-fd82-4e2b-95fa-4a1b2dfa9b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>63414ea2-1ca2-4dd1-b950-5042c26d1147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.liverpool.com.mx/assets/images/categorias/damas/catst4003357.jpg' and @alt = 'Tenis']</value>
      <webElementGuid>4a38c42b-29a3-4554-9a75-921f069f7fa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
