<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainSearchbar_misCompras</name>
   <tag></tag>
   <elementGuidId>15535ab3-bc2c-419b-8f09-9445b20f0f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='mainSearchbar'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.m-header__searchBar.m-order__search__searchBar.gray-shadow.m-order__search__input > div.input-group > #mainSearchbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a42bd1db-e635-4a80-8c8a-2fdf175a3475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainSearchbar</value>
      <webElementGuid>60a6e376-86f1-43b8-8f96-bd8f09fd0483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-bar plp-no__results</value>
      <webElementGuid>fa54d1f8-8348-40ab-b1da-30cf7f0ddfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Buscar ...</value>
      <webElementGuid>6e2258d5-2ea9-465e-a238-d69249e0b1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38afd7ef-7f16-48a7-9203-0442df4c7043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Busca por nombre de producto o número de pedido</value>
      <webElementGuid>c6623492-3b1a-4169-96d0-10cbfced77bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>47f39973-79d4-443d-a7ac-5ecde94c8087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>98283368-39ad-4c71-844a-023cf934949c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;o-order__search flex-grid MisComprasContainer padd-20 pb-4&quot;]/div[@class=&quot;o-order__search__searchBar miscompras__searchBar d-none d-lg-block&quot;]/div[@id=&quot;searchInput&quot;]/div[@class=&quot;m-header__searchBar m-order__search__searchBar gray-shadow m-order__search__input&quot;]/div[@class=&quot;input-group&quot;]/input[@id=&quot;mainSearchbar&quot;]</value>
      <webElementGuid>d027d041-5041-4a8c-bf10-11718032f421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='mainSearchbar'])[2]</value>
      <webElementGuid>8a1d5ae9-103b-4b8f-9c59-1794c6fc4aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchInput']/div/div/input</value>
      <webElementGuid>2f6a73c7-a5a0-4bf5-a6f4-b7dc45c9fcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>d992f2fc-7795-49cc-9d9b-c82343935c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mainSearchbar' and @type = 'text' and @placeholder = 'Busca por nombre de producto o número de pedido']</value>
      <webElementGuid>5df28ee5-a1a5-4ff3-a615-8871e45a1a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
