<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jobs</name>
   <tag></tag>
   <elementGuidId>eb697844-1485-42a7-b1a9-3d0eefb8828e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=''])[135]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.overview_subtitle_bm.bm-menu-item.jobschedules</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c89a5a9c-e258-4d6b-b2a0-f26a4545c083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://bjcl-006.dx.commercecloud.salesforce.com/on/demandware.store/Sites-Site/default/ViewApplication-BM?SelectedMenuItem=operations&amp;CurrentMenuItemId=operations&amp;screen=job&amp;menuactionid=jobschedules&amp;csrf_token=12briIa_e01FeLl0CtS9ZHPVFPw4slaEKljIyakBlvryMbcZwqThjzI7aZD-yLi07qTWx_o-dMOYkcppHEy9YXyo6hlQhFrLD2MLZneeMxnv0VoLBgJmcgAT0bJ1xLpFzqStIeYs_jfyvEV_twTRSvz1ytrymG-cfI8SY-ua-SDQaLiVxnQ%3d</value>
      <webElementGuid>dc61ee76-8e5b-42c9-9d9c-ada2a557a144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overview_subtitle_bm bm-menu-item jobschedules</value>
      <webElementGuid>8a6d39f7-a171-4723-a887-87c044e466fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Jobs

</value>
      <webElementGuid>f999569c-7759-4ee7-87d0-d79cf7fcbcc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ext-strict&quot;]/body[@class=&quot;ext-safari bm-welcome-page&quot;]/div[@class=&quot;slds-layout-frame&quot;]/div[@class=&quot;slds-layout&quot;]/ccbm[@class=&quot;cc-Sandbox&quot;]/div[@class=&quot;slds-layout-header bm-site-navigation-menus&quot;]/header[@class=&quot;slds-global-header_container&quot;]/div[@class=&quot;slds-context-bar&quot;]/nav[@class=&quot;slds-context-bar__secondary&quot;]/ul[@class=&quot;slds-grid bm-site-navigation-menus&quot;]/li[@class=&quot;slds-context-bar__item slds-context-bar__dropdown-trigger slds-dropdown-trigger_click table-action-menu&quot;]/div[@class=&quot;slds-context-bar__icon-action slds-p-left_none menu bm-dropdown-menu admin show-menu&quot;]/div[@class=&quot;administration-menu the-menu slds-dropdown__list admin&quot;]/div[@class=&quot;bm-menu-columns&quot;]/div[@class=&quot;bm-menu-column&quot;]/div[@class=&quot;section-name operations&quot;]/div[@class=&quot;bm-menu-section&quot;]/div[@class=&quot;leftmenu_sub_bm&quot;]/div[@class=&quot;menu_items_bm&quot;]/div[@class=&quot;overview_item_bm&quot;]/div[@class=&quot;overview_subtitle_bm&quot;]/a[@class=&quot;overview_subtitle_bm bm-menu-item jobschedules&quot;]</value>
      <webElementGuid>86cb2c83-5201-40c4-851e-9cbeeb7bf728</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=''])[135]</value>
      <webElementGuid>cf69306a-8abb-492f-b4be-7d6eac381896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jobs')]</value>
      <webElementGuid>d51c9f4f-4055-415f-854a-7678642c2ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operations'])[1]/following::a[1]</value>
      <webElementGuid>f6e3616f-c5f3-41be-bdd4-439e627b7086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross Cloud Trust'])[1]/following::a[2]</value>
      <webElementGuid>3dc36258-2b5a-432e-949e-e3aee71c9a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job History'])[1]/preceding::a[1]</value>
      <webElementGuid>392a309d-2557-4906-957a-c155855c32d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Step Types'])[1]/preceding::a[2]</value>
      <webElementGuid>ea4eb3ff-652e-4ce6-b7ff-ed0d6b16d5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jobs']/parent::*</value>
      <webElementGuid>2d218c9d-a500-409d-a184-0820887c58de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://bjcl-006.dx.commercecloud.salesforce.com/on/demandware.store/Sites-Site/default/ViewApplication-BM?SelectedMenuItem=operations&amp;CurrentMenuItemId=operations&amp;screen=job&amp;menuactionid=jobschedules&amp;csrf_token=12briIa_e01FeLl0CtS9ZHPVFPw4slaEKljIyakBlvryMbcZwqThjzI7aZD-yLi07qTWx_o-dMOYkcppHEy9YXyo6hlQhFrLD2MLZneeMxnv0VoLBgJmcgAT0bJ1xLpFzqStIeYs_jfyvEV_twTRSvz1ytrymG-cfI8SY-ua-SDQaLiVxnQ%3d')]</value>
      <webElementGuid>728038ff-5db0-414e-bdb7-230db598799a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/div[5]/div/div/div/div[2]/div/div/a</value>
      <webElementGuid>2ee4dad0-77dc-46ac-92b0-cce37748b1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://bjcl-006.dx.commercecloud.salesforce.com/on/demandware.store/Sites-Site/default/ViewApplication-BM?SelectedMenuItem=operations&amp;CurrentMenuItemId=operations&amp;screen=job&amp;menuactionid=jobschedules&amp;csrf_token=12briIa_e01FeLl0CtS9ZHPVFPw4slaEKljIyakBlvryMbcZwqThjzI7aZD-yLi07qTWx_o-dMOYkcppHEy9YXyo6hlQhFrLD2MLZneeMxnv0VoLBgJmcgAT0bJ1xLpFzqStIeYs_jfyvEV_twTRSvz1ytrymG-cfI8SY-ua-SDQaLiVxnQ%3d' and (text() = '
Jobs

' or . = '
Jobs

')]</value>
      <webElementGuid>d7a0a927-da73-4ad0-866c-36a528b11dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
