<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Negro_atom-color  0_0</name>
   <tag></tag>
   <elementGuidId>410d846d-1e8a-4dc3-8f8f-7d667225466a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='color-list-mobile']/li/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2889b3f4-a97d-4ee1-ad39-5c3509795d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skuid</name>
      <type>Main</type>
      <value>1029509103</value>
      <webElementGuid>6726c61c-e29e-4090-bb1b-5b1d85c89ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>atom-color @@ 0:_:0</value>
      <webElementGuid>a43b7e4a-43fe-4414-b64f-38e53218b139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>color0</value>
      <webElementGuid>e3eacd66-f89b-4ba4-9b5f-7f7d5197a338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/group/elvis-set-sala-contempor%C3%A1nea-gris/100000000147?skuid=100000000147#!</value>
      <webElementGuid>78100ac0-0772-4904-8b4e-c9e5b6cb94ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-container&quot;)/div[@class=&quot;o-content white-container mt-4&quot;]/div[@class=&quot;o-collection__products&quot;]/div[@class=&quot;o-product__container&quot;]/article[@class=&quot;o-product__collectionDescription product-selected&quot;]/div[@class=&quot;o-product__collectionDescription__detail&quot;]/div[@class=&quot;m-product__colors&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 pr-0&quot;]/div[@class=&quot;m-product__productColor mt-0&quot;]/ul[@id=&quot;color-list-mobile&quot;]/li[@class=&quot;a-productColor__item active mr-lg-2 mr-3 mt-2&quot;]/a[@class=&quot;atom-color @@ 0:_:0&quot;]</value>
      <webElementGuid>7494bb18-bdb4-43f4-9135-7a298fe1c1f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='color-list-mobile']/li/a)[2]</value>
      <webElementGuid>c7e80ba2-8777-49fe-b81e-b9064eee792b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/group/elvis-set-sala-contempor%C3%A1nea-gris/100000000147?skuid=100000000147#!')])[216]</value>
      <webElementGuid>a4234bd9-82af-4f73-9088-af8966e3fc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[3]/div[2]/div[3]/div[2]/div/div/ul/li/a</value>
      <webElementGuid>acbe40c1-d8fc-44b6-b728-8d2ae15729e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/group/elvis-set-sala-contempor%C3%A1nea-gris/100000000147?skuid=100000000147#!']</value>
      <webElementGuid>16435e6c-7e0e-443d-8b5b-99507b959e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
