<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Seleccionar_1</name>
   <tag></tag>
   <elementGuidId>d2712f8f-bf90-47ba-b2d3-63ecb58ad961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1029509098']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1029509098</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be9ec5f8-731d-4ae5-ad16-0f688d552891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--tertiary a-product__select </value>
      <webElementGuid>fe82d7f7-b239-4f63-ab72-6965f0ac92dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1029509098</value>
      <webElementGuid>15f292c5-3926-4c64-aba1-ab8c62315b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccionar</value>
      <webElementGuid>c4bccdb1-52c3-4377-84c0-8acf37e63f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-container&quot;)/div[@class=&quot;o-content white-container mt-4&quot;]/div[@class=&quot;o-collection__products&quot;]/div[@class=&quot;o-product__container&quot;]/article[@class=&quot;o-product__collectionDescription product-selected&quot;]/div[@class=&quot;o-product__collectionDescription__purchase&quot;]/div[@class=&quot;container d-lg-block d-none o-product__purchase__info&quot;]/div[1]/aside[@class=&quot;o-product__purchase p-0 pt-lg-3 pr-lg-3 pl-lg-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/aside[@class=&quot;o-product__productInfo pb-lg-4&quot;]/div[@class=&quot;o-product__productQty pto&quot;]/div[@class=&quot;row d-flex&quot;]/div[@class=&quot;col col-lg-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 pt-lg-3&quot;]/button[@id=&quot;1029509098&quot;]</value>
      <webElementGuid>6ebaeef0-32dc-4603-a905-9dc0678f71a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='1029509098']</value>
      <webElementGuid>62410a1f-9024-417f-b3ed-fbaef98977f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='products-container']/div/div/div/article[3]/div[4]/div/div/aside/div/div/aside/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>c99e4064-3d3f-447f-97ae-0d636173bf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresa tu código postal'])[3]/following::button[2]</value>
      <webElementGuid>b4378641-61bc-4da7-b37a-e8d1fb74114c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar'])[7]/preceding::button[1]</value>
      <webElementGuid>0d8b2b3b-c24c-4de3-9003-c3e12f3f7fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar'])[8]/preceding::button[2]</value>
      <webElementGuid>5c2d7934-7ce2-4b69-b12a-100ddb9e0538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[3]/div[4]/div/div/aside/div/div/aside/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>8e98027b-4eda-4054-a221-6af6db2ddce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '1029509098' and (text() = 'Seleccionar' or . = 'Seleccionar')]</value>
      <webElementGuid>35a84c46-102e-48ca-b49d-87a95936bafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
