<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Chica</name>
   <tag></tag>
   <elementGuidId>63e39fa8-96dc-4b5e-98e5-e8da6618f245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='size-list-container']/li/button)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>990441b8-15de-4f1f-8227-f9a4e8bdcd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--actionpdp</value>
      <webElementGuid>ca6b01ac-e54c-4071-8588-456301d5071c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skuid</name>
      <type>Main</type>
      <value>1029509103</value>
      <webElementGuid>833b3b2f-e409-425c-bc34-0dca600d635d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Chica </value>
      <webElementGuid>5bcdded2-b00d-4c5d-af6c-c8d46552556f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-container&quot;)/div[@class=&quot;o-content white-container mt-4&quot;]/div[@class=&quot;o-collection__products&quot;]/div[@class=&quot;o-product__container&quot;]/article[@class=&quot;o-product__collectionDescription product-selected&quot;]/div[@class=&quot;o-product__collectionDescription__detail&quot;]/div[@class=&quot;m-product__size -optic mt-4 mb-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/ul[@id=&quot;size-list-container&quot;]/li[1]/button[@class=&quot;a-btn a-btn--actionpdp&quot;]</value>
      <webElementGuid>728c6dbe-72ef-41c5-9f1e-fcfd4781f0b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='size-list-container']/li/button)[2]</value>
      <webElementGuid>8e5c2356-c384-4bbe-b7d4-6b2f295efce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Negro'])[1]/following::button[1]</value>
      <webElementGuid>99db8fd8-184d-4380-88a0-a1c637426738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chica']/parent::*</value>
      <webElementGuid>54e322e1-e937-4441-96a4-c877fe9f48e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[3]/div[2]/div[4]/div[2]/div/ul/li/button</value>
      <webElementGuid>3caa7934-229f-427a-8b7c-45d868a479a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Chica ' or . = ' Chica ')]</value>
      <webElementGuid>e0cf7794-e33a-41d3-a13c-e7b824ed8ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
