<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Seleccionar</name>
   <tag></tag>
   <elementGuidId>d737e557-0b8f-4d8c-ba1b-0a71eeddd614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1029509098']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1029509098</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbbedf70-2b46-4ebb-965b-07cc05f87f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--tertiary a-product__select </value>
      <webElementGuid>e28296fa-7265-4579-98b4-05d04be045ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1029509098</value>
      <webElementGuid>dd78dbc1-ed17-41cc-aa68-290a053d8c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccionar</value>
      <webElementGuid>4c07b5a3-1501-42c8-b705-b1dc66ef4489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-container&quot;)/div[@class=&quot;o-content white-container mt-4&quot;]/div[@class=&quot;o-collection__products&quot;]/div[@class=&quot;o-product__container&quot;]/article[@class=&quot;o-product__collectionDescription product-selected&quot;]/div[@class=&quot;o-product__collectionDescription__purchase&quot;]/div[@class=&quot;container d-lg-block d-none o-product__purchase__info&quot;]/div[1]/aside[@class=&quot;o-product__purchase p-0 pt-lg-3 pr-lg-3 pl-lg-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/aside[@class=&quot;o-product__productInfo pb-lg-4&quot;]/div[@class=&quot;o-product__productQty pto&quot;]/div[@class=&quot;row d-flex&quot;]/div[@class=&quot;col col-lg-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 pt-lg-3&quot;]/button[@id=&quot;1029509098&quot;]</value>
      <webElementGuid>f278d4e3-f388-452e-b14a-30b4aa0e9743</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='1029509098']</value>
      <webElementGuid>edc3d583-6d95-4d3e-8200-3f5ec5e5854c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='products-container']/div/div/div/article[3]/div[4]/div/div/aside/div/div/aside/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>4e6253c4-8b62-4394-aa30-8e87fa639a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresa tu código postal'])[3]/following::button[2]</value>
      <webElementGuid>76652f64-4c63-4e0e-9e21-308fc12605d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar'])[8]/preceding::button[1]</value>
      <webElementGuid>ed020aac-32f9-4951-8e8d-cc81be61b7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar'])[9]/preceding::button[2]</value>
      <webElementGuid>fd8d9660-fa21-4c73-ac8f-539ad3a937da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[3]/div[4]/div/div/aside/div/div/aside/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>64d1a97d-a0ae-44e1-8e63-ddbd6cceb398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '1029509098' and (text() = 'Seleccionar' or . = 'Seleccionar')]</value>
      <webElementGuid>d624df24-e1ec-474e-8243-23e2e8101fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='10075769']</value>
      <webElementGuid>2f491bd0-b497-4783-81c6-0473648a52b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='products-container']/div/div/div/article[2]/div[4]/div/div/aside/div/div/aside/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>c09882ae-d5b1-40e9-962e-432843de18e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresa tu código postal'])[2]/following::button[2]</value>
      <webElementGuid>632ede76-ef6a-4738-aee7-f15c948a2925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar'])[5]/preceding::button[1]</value>
      <webElementGuid>4575a93e-8e73-4a20-a950-e1b2394a8971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar'])[6]/preceding::button[2]</value>
      <webElementGuid>dc59df28-0539-4f66-8d26-269d26989fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/div[4]/div/div/aside/div/div/aside/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>f86ea6e7-c2e8-4ca7-92e2-57dd4deaf626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '10075769' and (text() = 'Seleccionar' or . = 'Seleccionar')]</value>
      <webElementGuid>90f355e3-b3a1-4b3b-b3d0-57f22adebd80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
