<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Artculos agregados 0  de  3 CobertorCdi_537c22</name>
   <tag></tag>
   <elementGuidId>a116ccc3-e137-40f5-b079-de82d94370ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o-product__container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='products-container']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96801558-836c-41d7-803f-34ff46d488e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-product__container</value>
      <webElementGuid>ee6505d3-a816-416f-93e1-d943b0e92239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Artículos agregados 0  de  3 CobertorCódigo de Producto: 3959023                 (0) $26900$17485 CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsapp Previous Next Lente solar Marino negroCódigo de Producto: 10075769                 (0) $13900$8340 : Multicolor    Tamaño:    Unitalla  CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsapp BlusaCódigo de Producto: 1029509098                 (0) $2000$1200 : Negro    Tamaño:    Chica     Mediana     Grande  CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsappAgregar a mi Bolsa</value>
      <webElementGuid>84e7974a-c880-4230-b986-0703fcbc3297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-container&quot;)/div[@class=&quot;o-content white-container mt-4&quot;]/div[@class=&quot;o-collection__products&quot;]/div[@class=&quot;o-product__container&quot;]</value>
      <webElementGuid>82626051-fa77-49e1-b714-5c93a10eca2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='products-container']/div/div/div</value>
      <webElementGuid>b2c306a6-0311-4b9e-8cde-f989ed7b3a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver artículos'])[1]/following::div[3]</value>
      <webElementGuid>f2950ee5-788a-49ba-abf6-8b41d5dea19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compartir'])[1]/following::div[5]</value>
      <webElementGuid>f8cff206-c32d-418c-a0ab-d3b0acf81b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div</value>
      <webElementGuid>d25f2e0b-211c-42e4-be46-033dbe0d52be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Artículos agregados 0  de  3 CobertorCódigo de Producto: 3959023                 (0) $26900$17485 CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsapp Previous Next Lente solar Marino negroCódigo de Producto: 10075769                 (0) $13900$8340 : Multicolor    Tamaño:    Unitalla  CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsapp BlusaCódigo de Producto: 1029509098                 (0) $2000$1200 : Negro    Tamaño:    Chica     Mediana     Grande  CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsappAgregar a mi Bolsa' or . = 'Artículos agregados 0  de  3 CobertorCódigo de Producto: 3959023                 (0) $26900$17485 CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsapp Previous Next Lente solar Marino negroCódigo de Producto: 10075769                 (0) $13900$8340 : Multicolor    Tamaño:    Unitalla  CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsapp BlusaCódigo de Producto: 1029509098                 (0) $2000$1200 : Negro    Tamaño:    Chica     Mediana     Grande  CaracterísticasOfertas especiales y promociones Recibe a domicilioIngresa tu código postal para conocer si este producto puede llegar el día de hoyCantidad:123456 + SeleccionarSeleccionarSeleccionarCompartirpwa.facebook.textpwa.twitter.textpwa.email.textpwa.copiar.textWhatsappAgregar a mi Bolsa')]</value>
      <webElementGuid>7de0a85d-8812-4e08-871e-a1583e3173e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
