<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Blusa</name>
   <tag></tag>
   <elementGuidId>5f71ff31-c42f-4fbf-b4a8-146eb43ba859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='products-container']/div/div/div/article[3]/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e3f46594-b403-492f-98e2-0b524754f60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-product__information--title</value>
      <webElementGuid>3347be83-b63c-479e-91f0-cf8b0606d1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blusa</value>
      <webElementGuid>a41be8b8-266f-442c-a663-870764c5b2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-container&quot;)/div[@class=&quot;o-content white-container mt-4&quot;]/div[@class=&quot;o-collection__products&quot;]/div[@class=&quot;o-product__container&quot;]/article[@class=&quot;o-product__collectionDescription product-selected&quot;]/div[@class=&quot;o-product__collectionDescription__detail&quot;]/h1[@class=&quot;a-product__information--title&quot;]</value>
      <webElementGuid>896a8b88-1eb5-40b9-b0d6-d4dcf526d7c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='products-container']/div/div/div/article[3]/div[2]/h1</value>
      <webElementGuid>abd135c3-9f12-4218-b757-1e8086390f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp'])[2]/following::h1[1]</value>
      <webElementGuid>f0880873-61ef-4344-8d18-891a399fbebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pwa.copiar.text'])[2]/following::h1[1]</value>
      <webElementGuid>ab488c0f-1a43-466f-8d7f-1c6342cfd93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Negro'])[1]/preceding::h1[1]</value>
      <webElementGuid>0bfb51a9-c285-49da-8270-4908e1577095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blusa']/parent::*</value>
      <webElementGuid>4b49f2ca-c211-42de-94cf-eb27e61a063b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[3]/div[2]/h1</value>
      <webElementGuid>a11c932f-28bf-4dba-90dd-acc447027198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Blusa' or . = 'Blusa')]</value>
      <webElementGuid>a1b72d12-ff48-460a-85a2-e7fca1978864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
