<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Cobertor</name>
   <tag></tag>
   <elementGuidId>f2df5c4f-0c9c-410a-af84-ecf23848a255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o-product__collectionDescription__detail > h1.a-product__information--title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='products-container']/div/div/div/article/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>899e7221-a98d-473f-8aff-6d641a664354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-product__information--title</value>
      <webElementGuid>7a8f9048-4b16-4527-860b-8c9b353b7df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cobertor</value>
      <webElementGuid>cb7aaccf-9dbc-4ac9-967b-710e71918f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-container&quot;)/div[@class=&quot;o-content white-container mt-4&quot;]/div[@class=&quot;o-collection__products&quot;]/div[@class=&quot;o-product__container&quot;]/article[@class=&quot;o-product__collectionDescription product-selected&quot;]/div[@class=&quot;o-product__collectionDescription__detail&quot;]/h1[@class=&quot;a-product__information--title&quot;]</value>
      <webElementGuid>a6270732-3875-440f-be35-54111cd98e21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='products-container']/div/div/div/article/div[2]/h1</value>
      <webElementGuid>cb130560-2f65-4204-aa93-913850f2d80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos agregados'])[1]/following::h1[1]</value>
      <webElementGuid>91292553-981e-4a90-a205-d1a3bdbe624a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Características'])[1]/preceding::h1[1]</value>
      <webElementGuid>c25f0e99-2a56-4cba-953d-222df0072765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cobertor']/parent::*</value>
      <webElementGuid>02db2216-53c2-40ab-9433-021b77d4c55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div[2]/h1</value>
      <webElementGuid>997e955e-1381-49a5-8970-13cb0b146002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Cobertor' or . = 'Cobertor')]</value>
      <webElementGuid>7596805c-5935-4471-91b0-976417c95e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
