<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Lente solar Marino negro</name>
   <tag></tag>
   <elementGuidId>ca21ff97-fe04-4394-878b-680e86e2f791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='products-container']/div/div/div/article[2]/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2204ba6b-ac94-4a50-a3a7-774453539350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-product__information--title</value>
      <webElementGuid>14c13453-716e-45f7-8787-898cad8154c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lente solar Marino negro</value>
      <webElementGuid>ac237c5c-ed62-48c1-958c-5b2e87cd64fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-container&quot;)/div[@class=&quot;o-content white-container mt-4&quot;]/div[@class=&quot;o-collection__products&quot;]/div[@class=&quot;o-product__container&quot;]/article[@class=&quot;o-product__collectionDescription product-selected&quot;]/div[@class=&quot;o-product__collectionDescription__detail&quot;]/h1[@class=&quot;a-product__information--title&quot;]</value>
      <webElementGuid>52b1eb2c-bb8f-40c6-a271-da757449a3d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='products-container']/div/div/div/article[2]/div[2]/h1</value>
      <webElementGuid>32a12f1a-7dec-4e5a-8dde-c6a4fa4f65cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multicolor'])[1]/preceding::h1[1]</value>
      <webElementGuid>92509c87-e37a-4621-a811-606ccc99127a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lente solar Marino negro']/parent::*</value>
      <webElementGuid>b52a877b-88cb-4e9c-b88f-1c63c8d330b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/div[2]/h1</value>
      <webElementGuid>d80afee9-b9b3-4cea-b6ab-6d07f5cab7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Lente solar Marino negro' or . = 'Lente solar Marino negro')]</value>
      <webElementGuid>5911b612-7b13-4f9a-986c-a8946ec7da95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
