<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Cant_icon-close_ci</name>
   <tag></tag>
   <elementGuidId>8f7dbf77-0483-4e7a-ae4a-168908040728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div[2]/div/div[3]/div/div/div/div/div/div/div/div[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-close_ci</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e738cf70-9298-44c5-84dd-7ab6057c63ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-close_ci</value>
      <webElementGuid>180432c7-1d91-45a2-8838-f8af1fb95cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[3]/div[@class=&quot;o-stickyBar__container__collections  showSticky&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;o-stickyBar__productsAdded&quot;]/div[@class=&quot;m-gallery&quot;]/div[@class=&quot;slick-slider m-carousel sticky__product__gallery slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;o-stickyBar__productAdded item1 added&quot;]/div[@class=&quot;m-stickyBar__productAdded__close&quot;]/i[@class=&quot;icon-close_ci&quot;]</value>
      <webElementGuid>22582956-ef48-4611-b74e-96c7c9668bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div[2]/div/div[3]/div/div/div/div/div/div/div/div[2]/i</value>
      <webElementGuid>d8cbc28d-51fb-40c3-ac0f-fc8158fa173c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]/i</value>
      <webElementGuid>ed44532e-0c50-4ed9-99bb-690e8649a4a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
