<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Cdigo de Producto 100000000147</name>
   <tag></tag>
   <elementGuidId>0e7e9da7-2222-459f-8c4a-72bb37e9f5b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.m-product__information--code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[5]/section/div/main/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e1d569ca-dd7b-4007-8416-23c53997bb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-product__information--code</value>
      <webElementGuid>0cd014b9-1ef5-4d38-a21d-be576543c13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Código de Producto: 100000000147</value>
      <webElementGuid>196727d5-bff4-432b-bbf9-2bfbbad1bf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;o-product&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/p[@class=&quot;m-product__information--code&quot;]</value>
      <webElementGuid>1e6093dd-177c-4439-a30a-99d8ca90743b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[5]/section/div/main/div[2]/p</value>
      <webElementGuid>b928a51a-c505-4f93-a3e8-1b7b1d4d5927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elvis Set Sala Contemporánea Gris'])[2]/following::p[1]</value>
      <webElementGuid>5be7b38a-093a-46ca-983d-2f66c128055e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba Ciclo 3.1 Modificado'])[1]/following::p[1]</value>
      <webElementGuid>50f2f377-8900-4ab4-8a22-0e276a035aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::p[1]</value>
      <webElementGuid>91820505-7823-4281-b8a3-2744f110a282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::p[3]</value>
      <webElementGuid>233cbfef-b6c2-43d2-ab40-78c83465b0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Código de Producto:']/parent::*</value>
      <webElementGuid>bf7efb4f-feba-4508-951b-4a36f5295ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>602ef9c0-2117-4387-816f-bb84ea7b103e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Código de Producto: 100000000147' or . = 'Código de Producto: 100000000147')]</value>
      <webElementGuid>edd5cefa-2af6-4945-90de-1e4100085792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
