<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tarjetas  Monedero_paypalImage</name>
   <tag></tag>
   <elementGuidId>21759033-e509-40f7-9675-dad6b91f2263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='paypalImage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paypalImage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1663f5ed-9b53-436c-b393-cd5bbe3628cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../static/images/atomo-icono-paypal.svg</value>
      <webElementGuid>816ce30c-6be3-4935-b6e2-6999f1479278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo PayPal</value>
      <webElementGuid>bf4d9831-01ce-45a4-80ae-85530c500bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-paymentOptionContainer__logo img-fluid</value>
      <webElementGuid>4ccb647a-0d73-4747-878c-4e60c683fcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalImage</value>
      <webElementGuid>09f8283a-a66a-409b-b924-7c94fe142035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalImage&quot;)</value>
      <webElementGuid>55d4e383-8981-4c87-b9e3-839e509048a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='paypalImage']</value>
      <webElementGuid>00effcac-08ce-443f-a7fe-dcbbd5c386bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_modalbody']/div/div[2]/button[2]/img</value>
      <webElementGuid>e64983c2-0747-4ceb-a54f-27a46478e2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo PayPal']</value>
      <webElementGuid>dd7abeb2-ad0c-4126-b2f3-6e8abb8016ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>bb27004d-f49a-463f-9aac-6fe262cd969c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../static/images/atomo-icono-paypal.svg' and @alt = 'Logo PayPal' and @id = 'paypalImage']</value>
      <webElementGuid>42f8b35a-8053-416a-87d2-5543ebd890ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
