<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FigureCart_hp</name>
   <tag></tag>
   <elementGuidId>e1cc97da-e7c1-4652-ba7d-e07c054b3092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//figure[@class='m-figureCard__figure']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
