<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L3_Verify_hp</name>
   <tag></tag>
   <elementGuidId>344823b9-f2e2-4c25-99a3-a7f9ac37915b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#abc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='abc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06b96027-4539-42e4-b2e6-afd48fa2864e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-breadcrumb__label</value>
      <webElementGuid>40cac624-01b7-4f82-a099-c26829896799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abc</value>
      <webElementGuid>f4df6117-3e90-4043-9748-216c7ce3a8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/lentes/cat3410047#!</value>
      <webElementGuid>e54dd391-6010-49a9-be58-15cd2611a5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lentes</value>
      <webElementGuid>380f99e5-c2a8-456e-b359-8a4d4de57717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abc&quot;)</value>
      <webElementGuid>5b024bab-433e-4f64-87e7-6975cafc1ff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='abc']</value>
      <webElementGuid>a13ef261-4058-4e1c-a5d8-43d9dfd2c35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>dd71d9b2-dc22-4cb1-866d-7b7bb5eeccf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lentes')]</value>
      <webElementGuid>e7024735-6244-47f5-be6d-8bbe88807a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accesorios de Hombre'])[1]/following::a[1]</value>
      <webElementGuid>875e6ab1-2303-496f-b1dc-647961a075a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[1]/following::a[2]</value>
      <webElementGuid>b3b2dc36-1bc5-4fad-8ddc-e043a660469d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorías'])[2]/preceding::a[1]</value>
      <webElementGuid>fe2160b5-e402-4db2-8869-23f512b6f9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hombre'])[2]/preceding::a[1]</value>
      <webElementGuid>76d3f674-af0a-48ee-bd1d-7d81cda5aa92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lentes']/parent::*</value>
      <webElementGuid>05614cdd-08fc-4431-893c-3ff407672cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/lentes/cat3410047#!')])[4]</value>
      <webElementGuid>0a522587-cf6c-4eea-89d3-fd57f735d617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>b83a96c6-96be-4989-b77a-ee5195cd38dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'abc' and @href = '/tienda/lentes/cat3410047#!' and (text() = 'Lentes' or . = 'Lentes')]</value>
      <webElementGuid>92637c66-2c34-4a59-abea-e74d818d0461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
