<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>primaryBanner_hp</name>
   <tag></tag>
   <elementGuidId>6bcdf844-935f-4785-8a39-5a93b96e1a35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bannerNo-1']/section/div/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.a_banner_img.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>67d84e99-27dc-4f50-80cf-2149cd3d20e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a_banner_img lazyloaded</value>
      <webElementGuid>47fbf144-b4f2-4b62-8f11-2e9fc8272ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/home/img/feb23/bc_160223mue.jpg</value>
      <webElementGuid>7b043614-d918-4896-8189-c0a82c4e11e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Muebles | Liverpool</value>
      <webElementGuid>fd46c3c8-14fb-470b-8a58-6ba2c8ef0002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Muebles | Liverpool</value>
      <webElementGuid>d3160e5b-87ac-4f1c-9761-ef741798ed95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bannerNo-1&quot;)/section[1]/div[@class=&quot;o-mainBanner&quot;]/a[1]/picture[@class=&quot;img-zoom&quot;]/img[@class=&quot;a_banner_img lazyloaded&quot;]</value>
      <webElementGuid>79878c62-a100-483e-b890-4c1a8f498e16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bannerNo-1']/section/div/a/picture/img</value>
      <webElementGuid>2edf4789-e3b5-4103-b84f-8d7e8f72585c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Muebles | Liverpool']</value>
      <webElementGuid>0afd954a-ac9c-49b8-a201-ee31fa5f6198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>942148ba-2219-4419-b125-685af72b5bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assetspwa.liverpool.com.mx/assets/digital/home/img/feb23/bc_160223mue.jpg' and @alt = 'Muebles | Liverpool' and @title = 'Muebles | Liverpool']</value>
      <webElementGuid>ddd5f07c-4451-4a24-a4ac-c8b25c79247e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
