<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>secondaryBanner_hp</name>
   <tag></tag>
   <elementGuidId>744ba32f-7018-43fa-8892-89fecfcc741e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bannerNo-2']/section[4]/div/div/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7843c200-ed51-41a9-96ac-3eeaab324a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a_banner_img lazyloaded</value>
      <webElementGuid>c6bf6974-f072-4557-aa30-2192450116af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/home/img/feb23/bpromo01a_160223patio.jpg</value>
      <webElementGuid>c0d03054-1931-43ea-b4af-2a1a6dfb717f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Patio y jardín | Liverpool</value>
      <webElementGuid>c7daf931-6a33-4788-9fed-bc5d6b51f600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Patio y jardín | Liverpool</value>
      <webElementGuid>ded7af09-c1c4-401f-b483-2f65a3653e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bannerNo-2&quot;)/section[@class=&quot;o-container-banners&quot;]/div[@class=&quot;o-container-promos&quot;]/div[@class=&quot;m-banners&quot;]/a[@class=&quot;m-mainBanner__link&quot;]/picture[1]/img[@class=&quot;a_banner_img lazyloaded&quot;]</value>
      <webElementGuid>43949a6a-15bd-41f5-8bbb-f395816ec1db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bannerNo-2']/section[4]/div/div/a/picture/img</value>
      <webElementGuid>27622996-589d-447b-a11a-7c2623bd8c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Patio y jardín | Liverpool']</value>
      <webElementGuid>abf48963-00fc-4f9f-be16-ad36fa829a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/a/picture/img</value>
      <webElementGuid>52d5aa9b-dc60-42bb-bec6-628a0639f84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assetspwa.liverpool.com.mx/assets/digital/home/img/feb23/bpromo01a_160223patio.jpg' and @alt = 'Patio y jardín | Liverpool' and @title = 'Patio y jardín | Liverpool']</value>
      <webElementGuid>df5c900b-5564-472c-9cb4-dcb7024a18c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
