<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyStore_hp</name>
   <tag></tag>
   <elementGuidId>81fbdc52-c447-4c56-bae2-0ad0f7918f79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.list-group-item.a-list-li-scrollable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/aside/div/div[10]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3739bedc-0031-4b16-8737-c2a5cee31442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item a-list-li-scrollable</value>
      <webElementGuid>aed05801-eb2a-4d71-8689-bac7aef7cdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Liverpool Acapulco La Isla </value>
      <webElementGuid>98565095-ab45-4491-a8f3-69b4927f23dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container p-0&quot;]/div[@class=&quot;row mt-lg-3 mb-lg-5 mb-0&quot;]/aside[@class=&quot;col-lg-4&quot;]/div[@class=&quot;o-storeLocator-aside d-none d-lg-block&quot;]/div[@class=&quot;m-list-scrollable&quot;]/ul[@class=&quot;list-group m-list-ul-scrollable&quot;]/li[@class=&quot;list-group-item a-list-li-scrollable&quot;]</value>
      <webElementGuid>fbf73a2e-cba1-46a5-9e1e-3f2871145665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/aside/div/div[10]/ul/li</value>
      <webElementGuid>235ec9b2-8b2a-47b2-82aa-cd7c5191bf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar por tipo de tienda'])[1]/following::li[1]</value>
      <webElementGuid>69669d13-9e44-41e8-9e3d-b8545c0c8877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione estado'])[1]/following::li[1]</value>
      <webElementGuid>3774459a-5fdc-4b3d-a622-ec2436b60caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Liverpool Acapulco La Isla']/parent::*</value>
      <webElementGuid>aae38def-77b9-4e1a-b932-7df835280dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/ul/li</value>
      <webElementGuid>9d6197fc-b316-4549-9ce9-554cccb999f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '  Liverpool Acapulco La Isla ' or . = '  Liverpool Acapulco La Isla ')]</value>
      <webElementGuid>70f4a31f-8ef4-4b31-95aa-f3354e094974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
