<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Totalplay Shop</name>
   <tag></tag>
   <elementGuidId>88df95f3-ae89-4876-9ae2-ae6a20234dff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SelectedSiteID-wrap']/span/span[2]/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sod_option.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ded3cbe5-5e61-422a-914f-25fa0f8d12bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sod_option active</value>
      <webElementGuid>fc736ccc-8c36-4bbc-81b3-fc065508a5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Totalplay Shop</value>
      <webElementGuid>ed79b93f-3933-45f0-8207-1d5590460556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>e6dfac91a443d68dbd279ec008</value>
      <webElementGuid>6b8dfc0c-2e5c-4783-8152-2abccf19163e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Totalplay Shop</value>
      <webElementGuid>84baf1fc-4fc5-4fd4-bf38-fcfe0f1ad52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedSiteID-wrap&quot;)/span[@class=&quot;sod_select focus open&quot;]/span[@class=&quot;sod_list_wrapper&quot;]/span[@class=&quot;sod_list&quot;]/span[@class=&quot;sod_option active&quot;]</value>
      <webElementGuid>01e3e2cc-b004-4521-aa53-ab62f35b5137</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SelectedSiteID-wrap']/span/span[2]/span/span[2]</value>
      <webElementGuid>a535ea63-9429-4b37-a62d-23a94c87ba8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Site'])[1]/following::span[1]</value>
      <webElementGuid>2d5085bb-8b7d-4b18-9e4c-a8d0910b2f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Selection'])[1]/preceding::span[1]</value>
      <webElementGuid>bd8519db-8956-42a4-ae33-b8c7ea70acf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant Tools'])[1]/preceding::span[2]</value>
      <webElementGuid>874ce8f8-ef1e-4bb6-8023-a8117b170341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Totalplay Shop']/parent::*</value>
      <webElementGuid>8c8e466d-bc1e-47ea-9af2-02d192563601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span[2]</value>
      <webElementGuid>1d56b423-1c5b-47a1-ba37-99067bd67121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Totalplay Shop' and (text() = 'Totalplay Shop' or . = 'Totalplay Shop')]</value>
      <webElementGuid>ecd890aa-2779-4015-8f9e-cbec0ea47de7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
