<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Close_Icon_Filter_plp</name>
   <tag></tag>
   <elementGuidId>fc0f0c07-ba81-4084-804c-8f6afcefa242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='mdc-chip__text']/i[@class='icon-close'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.plp-filters-container.mt-3.mb-3 > div.mdc-chip-set > div.mdc-chip.a-plp__filterSelection > div.mdc-chip__text > i.icon-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8910faf9-a8a5-463a-b1f7-74817ea09887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-close</value>
      <webElementGuid>370311d0-728e-4eee-b9fc-9d94e9be3794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-4 m-aside__content&quot;]/div[@class=&quot;m-plp-cat-container d-none d-lg-block mb-5&quot;]/div[@class=&quot;o-aside d-aside--margin&quot;]/div[@class=&quot;plp-filters-container mt-3 mb-3&quot;]/div[@class=&quot;mdc-chip-set&quot;]/div[@class=&quot;mdc-chip a-plp__filterSelection&quot;]/div[@class=&quot;mdc-chip__text&quot;]/i[@class=&quot;icon-close&quot;]</value>
      <webElementGuid>488e5629-fc90-4245-8032-ed97e8542be8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[5]/div/div/div/i</value>
      <webElementGuid>8519f5d6-c029-46ce-a39b-1eabe068578b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/i</value>
      <webElementGuid>dd4960de-1ffd-4472-a3c9-612d79a834a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
