<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gridView_plp</name>
   <tag></tag>
   <elementGuidId>fa8df7fd-f93c-4f3a-b491-eaf1bd5c3b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='a-gridview']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-vistagrid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e3ea9c89-35f1-4f77-a3d2-5516f9235895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-vistagrid</value>
      <webElementGuid>aa1507f9-f349-42bc-95c9-9971ad17e9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-gridview&quot;)/i[@class=&quot;icon-vistagrid&quot;]</value>
      <webElementGuid>96ed486d-7b2f-4ed4-be25-521553f4bcf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='a-gridview']/i</value>
      <webElementGuid>221ee67b-891d-43fa-88f2-9016c6d4b624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>488ef799-e770-42aa-8903-249f05ac346e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
