<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listView_plp</name>
   <tag></tag>
   <elementGuidId>77108a5d-b3b8-44bc-bc7a-00b10c2af7ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='a-listview']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-vistalista</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3360872d-9817-4ced-b4ec-a2c45c773a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-vistalista</value>
      <webElementGuid>4229fb41-dfbe-40a0-b012-bce4a8281c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-listview&quot;)/i[@class=&quot;icon-vistalista&quot;]</value>
      <webElementGuid>a4439060-a5bf-4dae-9b9b-6caedf50c189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='a-listview']/i</value>
      <webElementGuid>954aac5b-5cf8-489d-9a99-7497795722f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>9289ef55-0cb9-4219-a533-7a8ba385cd81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
