<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainBanner_plp</name>
   <tag></tag>
   <elementGuidId>197c6085-3e3a-4296-872a-6b5ca0bd4680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='mainBanner'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.o-blp-mainContent.order-1.order-lg-2.px-0.px-lg-0.d-none.d-lg-block > div.contaier-fluid.p-0 > div.row > div.container-promo01.col-12.col-lg-12 > a.m-mainBanner__link > picture.img-zoom > #mainBanner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>71bb0026-3ce3-4ead-9599-609e9b8204d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBanner</value>
      <webElementGuid>9326be64-baa4-4baf-9f3b-2e1878df48ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-mainBanner__image lazyloaded</value>
      <webElementGuid>7bb47e39-e069-464f-b96c-75b4c0f10352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/landing/mujer/blp_vestidos_121222.jpg</value>
      <webElementGuid>6667b934-36fd-45a4-90e2-a190684eeffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Renta de vestidos | Liverpool</value>
      <webElementGuid>da652d36-93e1-4be9-8862-a32b4bffce76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Renta de vestidos | Liverpool</value>
      <webElementGuid>e078ffe1-03fc-45df-983a-456d3f0a901f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/landing/mujer/blp_vestidos_121222.jpg</value>
      <webElementGuid>53771c10-864a-406b-9df1-fe6b71307bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;o-blp-mainContent order-1 order-lg-2 px-0 px-lg-0 d-none d-lg-block&quot;]/div[@class=&quot;contaier-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container-promo01 col-12 col-lg-12&quot;]/a[@class=&quot;m-mainBanner__link&quot;]/picture[@class=&quot;img-zoom&quot;]/img[@id=&quot;mainBanner&quot;]</value>
      <webElementGuid>45cfe701-82f5-4f8e-a09a-bd5095917483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='mainBanner'])[10]</value>
      <webElementGuid>90920aa9-67fe-4770-ad2c-a7ea70dc6eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[4]/main/div[2]/div/div[4]/div/a/picture/img</value>
      <webElementGuid>632fdf55-bc69-4da3-ae35-dd8161ca4cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Renta de vestidos | Liverpool'])[2]</value>
      <webElementGuid>87429028-4fd7-4d70-b8e6-99218e61d514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/a/picture/img</value>
      <webElementGuid>4d4356ab-5255-4c3a-ad41-641c687dd951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'mainBanner' and @alt = 'Renta de vestidos | Liverpool' and @title = 'Renta de vestidos | Liverpool' and @src = 'https://assetspwa.liverpool.com.mx/assets/digital/landing/mujer/blp_vestidos_121222.jpg']</value>
      <webElementGuid>0d828248-1569-4816-ab1e-37ce56ed1fd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
