<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Precios_plp</name>
   <tag></tag>
   <elementGuidId>1dcbf3b6-e747-4c09-aaf1-8f48da0143d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[title=&quot;Precios&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='col a-text__filter'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8715232d-42d3-419f-ae6e-17b6d1b7e382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Precios</value>
      <webElementGuid>4bc7893e-f1b6-4e81-a172-056105014005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Precios</value>
      <webElementGuid>06567ecf-5bb5-4b21-a5e8-9639b7a39128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-4 m-aside__content&quot;]/div[@class=&quot;m-plp-cat-container d-none d-lg-block mb-5&quot;]/div[@class=&quot;o-aside d-aside--margin&quot;]/div[@class=&quot;m-plp__filterSection&quot;]/div[@class=&quot;a-plp__btnFilter&quot;]/button[@class=&quot;a-title__filter&quot;]/h3[@class=&quot;m-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col a-text__filter&quot;]/label[1]</value>
      <webElementGuid>9929d6b9-e11c-46e8-8f31-bae8bf317426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[28]/div/button/h3/div/div/label</value>
      <webElementGuid>57bcacb9-509f-45ff-8334-75c218c5c6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver más'])[2]/following::label[1]</value>
      <webElementGuid>4ff874fa-cc2c-445c-9aa7-8169aad02c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CH (433)'])[1]/following::label[1]</value>
      <webElementGuid>a839a6e0-6306-4e0f-93db-8b8c381b2cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Precios']/parent::*</value>
      <webElementGuid>8cec0d5b-8e8b-45db-b6fd-c7e0a45932a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/button/h3/div/div/label</value>
      <webElementGuid>95426ca4-3c9f-49ff-9cdf-7e020dc2ad91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Precios' and (text() = 'Precios' or . = 'Precios')]</value>
      <webElementGuid>bfcc5575-a6a3-4439-b67f-4fa1f2e9ee09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
