<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Price_Filter_max_plp</name>
   <tag></tag>
   <elementGuidId>fa11aa19-87d2-4c30-b41c-a7061039eefd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#max-price-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@Class='a-price__filterInput']//input[@id='max-price-filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e5bbb9a-2923-49ac-b18f-a6e2a8aa07aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max-price-filter</value>
      <webElementGuid>d92f1b3c-8c8f-4a16-960c-78dc03383666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1237821c-f705-4b78-af4d-17c8c9169c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1970c735-6b0c-43b6-a6c9-dd4f563a728a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Máximo</value>
      <webElementGuid>c5d815e1-5161-49c0-9cd3-7a7465d5c9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66a9bcdb-9746-4780-9b93-734872d17b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>maxPrice</value>
      <webElementGuid>1163baa7-531c-4e28-8a05-93e6d23ff1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max-price-filter&quot;)</value>
      <webElementGuid>34850863-7dc9-4d86-b09f-aff42bf80ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max-price-filter']</value>
      <webElementGuid>f2bfbcc8-025c-41b1-b14b-a57cc690a36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[53]/div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>9aed1042-ebae-4d07-82f6-fe80b7061889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[53]/div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>5fffbfb7-9be3-4826-9ea9-ac283c398b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'max-price-filter' and @type = 'text' and @placeholder = 'Máximo']</value>
      <webElementGuid>f73d7218-e322-4a33-9fff-e1b07fd3e588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
