<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Price_Filter_min_plp</name>
   <tag></tag>
   <elementGuidId>d561c67b-0874-4dc2-adbf-4ec6ad7b4579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#min-price-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@Class='a-price__filterInput']//input[@id='min-price-filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c177488-5df7-4ee1-9050-36cd7b715c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>min-price-filter</value>
      <webElementGuid>fc20c227-ff18-4b77-8464-fe05f5a18f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4a108696-815b-4a83-a908-a335dc55b92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>257054b3-8da9-4f2a-98e4-c13cae6647dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mínimo</value>
      <webElementGuid>402dc3bc-99b0-4f4b-9deb-5c92aa273a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd864d35-1c42-45e3-836e-966e3f7c95da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>minPrice</value>
      <webElementGuid>eb4253e1-842d-442f-a555-c33d0127575c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;min-price-filter&quot;)</value>
      <webElementGuid>94745670-892d-4f1c-9209-630c5dc0d375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='min-price-filter']</value>
      <webElementGuid>942b4c7d-193e-439a-a15b-07454b69ce64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[53]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>7a583785-75e6-4ba1-a11f-9a19f70ebbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[53]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>2a1716ad-6771-4a2a-90ab-74a8adad0f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'min-price-filter' and @type = 'text' and @placeholder = 'Mínimo']</value>
      <webElementGuid>4d246809-c739-4406-84c0-e84588fde873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
