<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SeeMore_plp</name>
   <tag></tag>
   <elementGuidId>f4fb24dc-a4c6-4f23-89cf-09af942d2e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='a-link__viewMore'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-link__viewMore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>baae18d8-171c-40a3-8e96-7c2187c79b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link__viewMore</value>
      <webElementGuid>9e98f197-1bfb-416c-b5eb-78798dea3444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda?s=mac#!</value>
      <webElementGuid>65c5b772-6ef2-4d8c-968a-ffb1e118c05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver más</value>
      <webElementGuid>741f9cb2-de33-47f5-8608-982cac39e8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-4 m-aside__content&quot;]/div[@class=&quot;m-plp-cat-container d-none d-lg-block mb-5&quot;]/div[@class=&quot;o-aside d-aside--margin&quot;]/div[@class=&quot;m-plp__filterSection&quot;]/div[@class=&quot;plp-filter-options active&quot;]/a[@class=&quot;a-link__viewMore&quot;]</value>
      <webElementGuid>a103045b-223d-405f-8afe-49d68207f469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[51]/div[2]/a</value>
      <webElementGuid>4ab24b2f-8513-41b1-bc76-7250932f7d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ver más')]</value>
      <webElementGuid>975c5349-975a-484b-b7de-bc5ec56a1be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tamaño'])[1]/preceding::a[1]</value>
      <webElementGuid>cab6f32d-8b91-4011-8be1-66a2978607d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CH (1)'])[1]/preceding::a[1]</value>
      <webElementGuid>37f92aa5-5a28-4df4-b5a5-54f54b29bed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver más']/parent::*</value>
      <webElementGuid>76b65888-476b-4a70-a1c8-afbde4323e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda?s=mac#!')])[5]</value>
      <webElementGuid>83644883-6415-4580-a2e2-94a74a1d1ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[51]/div[2]/a</value>
      <webElementGuid>c0ebb2d6-dc0b-4a88-8ff1-64822b7a5ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda?s=mac#!' and (text() = 'Ver más' or . = 'Ver más')]</value>
      <webElementGuid>c5f7678d-99b2-4e19-8e4e-5484b74d6954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
