<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_PriceTag_plp</name>
   <tag></tag>
   <elementGuidId>d12af232-be2c-4f1f-bf3d-ba04b8fdd188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='variants.prices.sortPrice-100-500']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab48b72c-c3c3-46ff-a607-3b04791a6336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>variants.prices.sortPrice-100-500</value>
      <webElementGuid>69d740f9-e6a8-4248-8f47-6c5cfb125215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-radio__input mdc-radio__native-control</value>
      <webElementGuid>99a88c9a-534d-4519-8b4d-98901a03b1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f0d450c4-af2a-4f34-b7e8-c282ac1727ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>70fcb1d4-25eb-4ab8-b417-b446783cce58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;variants.prices.sortPrice-100-500&quot;)</value>
      <webElementGuid>507fb005-2d64-420f-8d01-9a9861f88d41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='variants.prices.sortPrice-100-500']</value>
      <webElementGuid>6dfdef7b-0950-4db3-99f5-f06ebe3f43df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[53]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>49a31cd2-9989-4d32-9172-e00632a14d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[53]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>8d393ef4-bfb7-4d49-8937-b1df0bb78a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'variants.prices.sortPrice-100-500' and @type = 'radio']</value>
      <webElementGuid>70e9d875-bcc1-4f3b-844b-2dc253718127</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
