<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Img_3_plp</name>
   <tag></tag>
   <elementGuidId>8ebc0e31-627f-4701-87a8-6299e3b03f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='https://ss701.liverpool.com.mx/lg/1021509082.jpg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef01e617-7c9d-4a8f-ac24-7a62fd84721b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9dc64006-28e5-43df-8ea3-70696f9763d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss701.liverpool.com.mx/lg/1021509082.jpg</value>
      <webElementGuid>b6f20054-d5cf-472d-8e48-078b46e71e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lipstick M.A.C Retro Matte</value>
      <webElementGuid>8a7cb04a-b10b-4aa9-9c71-8459be41db51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_1</value>
      <webElementGuid>d1814622-6b14-40bf-b314-72a73f040dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_1&quot;)</value>
      <webElementGuid>94bd1d20-c5d5-442c-bb0c-5653ee2df339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_1']</value>
      <webElementGuid>55c6d7fc-4972-499e-a03b-07fae7a7c3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>a5ae7dfa-77d6-4f5b-8ed3-a88d6ae5c356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lipstick M.A.C Retro Matte']</value>
      <webElementGuid>c0d209a3-3ea8-457b-9a7a-878bbf0da27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>b9456aa3-b3b4-4e21-8b9e-f8b5256474bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss701.liverpool.com.mx/lg/1021509082.jpg' and @alt = 'Lipstick M.A.C Retro Matte' and @id = 'img_1']</value>
      <webElementGuid>7fdadf8b-499d-4117-b95a-07fa94e4053d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
