<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Quantity_plp</name>
   <tag></tag>
   <elementGuidId>adbd3f72-591d-4ea1-9145-3abe0338a776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-flag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@class='a-plp-results-title']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59b0b62c-a866-4878-8f32-b827174ec5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-flag</value>
      <webElementGuid>dc480b9c-6670-4ddf-bc41-799761e57990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compra mínima 4 piezas</value>
      <webElementGuid>0b745bde-0cb3-4f5a-9969-c732b973e703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 p-2 p-lg-1&quot;]/div[@class=&quot;o-listing__products&quot;]/ul[@class=&quot;m-product__listingPlp&quot;]/li[@class=&quot;m-product__card card-masonry a&quot;]/figure[@class=&quot;m-figureCard__figure card m-plp-product-card m-card&quot;]/div[@class=&quot;o-card__image__container&quot;]/div[1]/div[@class=&quot;m-plp-flag-container&quot;]/span[@class=&quot;a-flag&quot;]</value>
      <webElementGuid>f8eaa540-00aa-4c84-af53-e537ad40056b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[7]/figure/div/div/div[2]/span</value>
      <webElementGuid>f17c1683-bcf0-42ee-93a9-41bcadb5527e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaso para agua Haus de vidrio'])[1]/following::span[3]</value>
      <webElementGuid>8124367d-420a-4a01-8d20-3cd98b7140e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaso high ball Haus Chrome de vidrio'])[1]/following::span[8]</value>
      <webElementGuid>35ed27bc-9a75-4284-a782-bdf450414034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaso con tapa y popote Brandtrendy 1 pieza'])[1]/preceding::span[1]</value>
      <webElementGuid>d10c659c-ccf7-4f3c-b01e-669e09f0b251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set de vasos Haus de vidrio con 12 piezas'])[1]/preceding::span[9]</value>
      <webElementGuid>353ce43a-d98c-43a0-9d7b-c25010379bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compra mínima 4 piezas']/parent::*</value>
      <webElementGuid>d82b8cd2-2ed8-468e-b5f4-042d3d66aa90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/div/div[2]/span</value>
      <webElementGuid>05c48011-5ef5-4c57-bde5-3cd1299d5dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Compra mínima 4 piezas' or . = 'Compra mínima 4 piezas')]</value>
      <webElementGuid>673958f8-9b83-4394-9be2-3369bfb1adea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
