<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Quantity_plp</name>
   <tag></tag>
   <elementGuidId>adbd3f72-591d-4ea1-9145-3abe0338a776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='m-plp-flag-container']/span[@class='a-flag']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-flag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b88cf9cf-cbb9-4f2f-8ce9-ad7644688557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-flag</value>
      <webElementGuid>1293bb5b-cd0d-4ffb-81e0-66507d67cce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compra mínima 4 piezas</value>
      <webElementGuid>c7bc9f44-563a-4526-8bdf-eb03db0a2083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 p-2 p-lg-1&quot;]/div[@class=&quot;o-listing__products&quot;]/ul[@class=&quot;m-product__listingPlp&quot;]/li[@class=&quot;m-product__card card-masonry a&quot;]/figure[@class=&quot;m-figureCard__figure card m-plp-product-card m-card&quot;]/div[@class=&quot;o-card__image__container&quot;]/div[1]/div[@class=&quot;m-plp-flag-container&quot;]/span[@class=&quot;a-flag&quot;]</value>
      <webElementGuid>a9b4275b-fde0-40ef-bbeb-d160e06e3f2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[7]/figure/div/div/div[2]/span</value>
      <webElementGuid>7fe19705-3b0e-4072-8d10-126acd893ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaso para agua Haus de vidrio'])[1]/following::span[3]</value>
      <webElementGuid>684b10b6-8d69-43f6-ac08-feaf70102773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaso high ball Haus Chrome de vidrio'])[1]/following::span[8]</value>
      <webElementGuid>f3f4bd20-bac5-418b-aa52-2953ba2f5167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaso con tapa y popote Brandtrendy 1 pieza'])[1]/preceding::span[1]</value>
      <webElementGuid>ef845a56-ccb3-4ba5-8c42-42fd38f1d418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set de vasos Haus de vidrio con 12 piezas'])[1]/preceding::span[9]</value>
      <webElementGuid>aab7c68f-99ea-4f1e-8d46-c24d65a98f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compra mínima 4 piezas']/parent::*</value>
      <webElementGuid>0c8e7e3e-e824-42ab-b77a-a10531ab7b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/div/div[2]/span</value>
      <webElementGuid>4b74b9f9-19ae-4dd5-83a8-0600544c327d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Compra mínima 4 piezas' or . = 'Compra mínima 4 piezas')]</value>
      <webElementGuid>e70838cd-db36-4206-bd13-8caab8269f7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
