<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Img_2_plp</name>
   <tag></tag>
   <elementGuidId>cda56c2f-f20a-441e-b6a5-e7369f34334f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='https://ss701.liverpool.com.mx/lg/1021509066.jpg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad185970-99ef-4c0d-93ba-5649ca6dfcb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>426c4cf6-10b2-46a4-aed6-3b30ff133cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss701.liverpool.com.mx/lg/1021509066.jpg</value>
      <webElementGuid>a5c709ed-a466-4008-928d-b2b9927913ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lipstick M.A.C Retro Matte</value>
      <webElementGuid>0cb35f7a-54cb-4ce9-aad2-6e6ffe08ca85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_1</value>
      <webElementGuid>21dfaa44-85b7-487c-8d1f-d0f5b7a27d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_1&quot;)</value>
      <webElementGuid>6fb366a2-f420-4338-ab35-7d9d324b34d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_1']</value>
      <webElementGuid>937fcb19-4475-4135-8438-cfbbc2195a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>7c006534-ef12-4564-8845-87d1f2ecfaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lipstick M.A.C Retro Matte']</value>
      <webElementGuid>6e6bbfac-942b-4053-b333-6ad89cde6ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>604bc8d9-a0b5-422c-8813-e8caf1f534e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss701.liverpool.com.mx/lg/1021509066.jpg' and @alt = 'Lipstick M.A.C Retro Matte' and @id = 'img_1']</value>
      <webElementGuid>a3b06922-c6ed-4267-8e19-145403fde80f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
