<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Price_Filter_plp</name>
   <tag></tag>
   <elementGuidId>a0cb7a0e-6fd3-43c5-946d-32dd7212589b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.plp-filters-container.mt-3.mb-3 > div.mdc-chip-set > div.mdc-chip.a-plp__filterSelection > div.mdc-chip__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@Class='mdc-chip-set']/div[@class='mdc-chip a-plp__filterSelection']/div[@class='mdc-chip__text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3943e9a-cc03-47fd-a336-b28352124c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-chip__text</value>
      <webElementGuid>d169d507-e9ce-447a-b70b-bd44671a4a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$200.0 -$500.0</value>
      <webElementGuid>297eb675-ba77-4d5d-ad29-0d5fc6e5745c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-4 m-aside__content&quot;]/div[@class=&quot;m-plp-cat-container d-none d-lg-block mb-5&quot;]/div[@class=&quot;o-aside d-aside--margin&quot;]/div[@class=&quot;m-plp__filterApplied mt-4&quot;]/div[@class=&quot;plp-filters-container mt-3 mb-3&quot;]/div[@class=&quot;mdc-chip-set&quot;]/div[@class=&quot;mdc-chip a-plp__filterSelection&quot;]/div[@class=&quot;mdc-chip__text&quot;]</value>
      <webElementGuid>b6d21e0b-2a1f-46d9-8004-bb6f813d98f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>af34cfd7-9b4f-4569-a2f6-e1e1a748e6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar Filtros'])[1]/following::div[5]</value>
      <webElementGuid>c20d0376-2392-4a0a-ae58-4e5ab1e18386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorías'])[2]/preceding::div[1]</value>
      <webElementGuid>f7891201-0ce8-4649-837b-727f1c79e005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belleza'])[1]/preceding::div[6]</value>
      <webElementGuid>bd6f837f-97a0-473f-ab03-c4a1bf57d1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>679e2b3d-1a24-4804-b38c-fd48e0448eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '$200.0 -$500.0' or . = '$200.0 -$500.0')]</value>
      <webElementGuid>701d287a-5801-41d9-bc1a-b021eb73a309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
