<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Img_1_plp</name>
   <tag></tag>
   <elementGuidId>331eb25d-365f-4fa0-b7bf-d348d418eb25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4f40c723-5022-4228-a01c-d41673dff802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a0e34203-835e-447e-9cb8-216e6842174b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss701.liverpool.com.mx/lg/1011422132.jpg</value>
      <webElementGuid>31d51dfa-5481-489d-b47a-be46c9c1d7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lipstick M.A.C Retro Matte</value>
      <webElementGuid>0cdda578-65e5-42e0-b3a6-4efdfc42d8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_1</value>
      <webElementGuid>3288e98f-e4f1-4e10-92dc-d20ba80e8b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_1&quot;)</value>
      <webElementGuid>1d448220-704b-497f-a902-02281df5d22a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_1']</value>
      <webElementGuid>daa78999-c428-44ff-9ae2-dbca481ae29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>1be32962-8b95-4b50-af7f-03cbd31bf533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lipstick M.A.C Retro Matte']</value>
      <webElementGuid>c10eebd9-a593-4fc7-8dc0-b721084707bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>3ef4f986-e556-4bea-986d-38a359d0a939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss701.liverpool.com.mx/lg/1011422132.jpg' and @alt = 'Lipstick M.A.C Retro Matte' and @id = 'img_1']</value>
      <webElementGuid>f93f1682-a668-4ffe-8894-75e44f2d4bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
