<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(1)_img_1</name>
   <tag></tag>
   <elementGuidId>331eb25d-365f-4fa0-b7bf-d348d418eb25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='https://ss701.liverpool.com.mx/lg/1011422132.jpg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1b8bbbaa-f783-494d-9854-30fd8a850baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>333c8ae0-c435-4a40-a7f5-b9daa18590a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss701.liverpool.com.mx/lg/1011422132.jpg</value>
      <webElementGuid>b0503580-2acc-4b62-9af1-3d68fcd44ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lipstick M.A.C Retro Matte</value>
      <webElementGuid>22da5c73-2fa1-4c53-b5f6-3b782736b20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_1</value>
      <webElementGuid>f315da23-9847-4ebf-923a-5f1b13007d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_1&quot;)</value>
      <webElementGuid>e7cb3008-75c3-472e-90a9-08df7ccffc35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_1']</value>
      <webElementGuid>3a628a10-9f2c-4b8d-9c17-08eeff45be1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>f28da3ee-2d37-4fc4-82d5-d93fd5163e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lipstick M.A.C Retro Matte']</value>
      <webElementGuid>13472749-22f3-4171-957f-b36a7194cdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>10d74a87-b6bc-40f4-8e76-3531b98bfa9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss701.liverpool.com.mx/lg/1011422132.jpg' and @alt = 'Lipstick M.A.C Retro Matte' and @id = 'img_1']</value>
      <webElementGuid>cd39f79d-aead-464e-882b-b1138c09ead6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
