<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>referenceNumber_confirmation</name>
   <tag></tag>
   <elementGuidId>2010a82a-9d1d-4c3d-a557-9fa1c3bb27a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.reference-section__number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='reference-section']//span[@class='reference-section__number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f13a1dc7-ca15-41cb-96df-cf40ec0d2fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reference-section__number</value>
      <webElementGuid>0fbb8da9-c9d6-4400-b6c6-8e81823a6173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1010103874017249</value>
      <webElementGuid>cc9a58d3-98fd-4d48-bb06-1b725c8ccb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-confirmation-page&quot;)/div[@class=&quot;two-blocks-layout section-container&quot;]/div[@class=&quot;m-box payment-section&quot;]/div[@class=&quot;reference-section&quot;]/span[@class=&quot;reference-section__number&quot;]</value>
      <webElementGuid>073f980d-40d8-451d-8c39-06856544f2d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order-confirmation-page']/div[3]/div[2]/div[5]/span[2]</value>
      <webElementGuid>251aab81-dd58-4f4b-b526-d00967a1efca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referencia:'])[1]/following::span[1]</value>
      <webElementGuid>ca913619-d1d9-40ae-8150-7fb32bb12661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vence:'])[1]/following::span[3]</value>
      <webElementGuid>779e2e8e-6a2a-45ca-9eae-dd91f38bfce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANTE'])[1]/preceding::span[1]</value>
      <webElementGuid>da9c70c2-7469-4506-bb61-1f1a0cd1347b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar ticket de pago'])[1]/preceding::span[1]</value>
      <webElementGuid>e5b313e6-bbb9-4daa-8003-679c3d0bc994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1010103874017249']/parent::*</value>
      <webElementGuid>c20a81c3-1cd7-41e2-9911-5a7c89a9aec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span[2]</value>
      <webElementGuid>a3e47749-0648-411b-ab4a-05aeeaaaa702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1010103874017249' or . = '1010103874017249')]</value>
      <webElementGuid>7be83541-d945-4e27-a382-6274dee5004b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
