<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product_plp</name>
   <tag></tag>
   <elementGuidId>82f19687-fa65-4c1f-87c8-cc8d25708409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o-blp-mainContent.order-1.order-lg-2.px-0.px-lg-0.d-none.d-lg-block > div.contaier-fluid.p-0 > div.row > div.container-promo01.col-12.col-lg-6 > a.m-mainBanner__link > div.banner-promo03-desc.category-promo03 > ul.btn-catpromo03 > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div[2]/div/a/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>36987416-76be-4da8-8bde-926aadaf1d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHAMARRAS</value>
      <webElementGuid>0f1fdd5a-3035-447c-9945-d1229185c03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;o-blp-mainContent order-1 order-lg-2 px-0 px-lg-0 d-none d-lg-block&quot;]/div[@class=&quot;contaier-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container-promo01 col-12 col-lg-6&quot;]/a[@class=&quot;m-mainBanner__link&quot;]/div[@class=&quot;banner-promo03-desc category-promo03&quot;]/ul[@class=&quot;btn-catpromo03&quot;]/li[1]</value>
      <webElementGuid>e861265e-8943-4328-9ffb-022b9ef4ba99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[4]/main/div[2]/div/div[2]/div/a/div/ul/li</value>
      <webElementGuid>7235b612-2266-475d-95e8-983fafb583d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROPA INTERIOR'])[2]/following::li[1]</value>
      <webElementGuid>0ad6b8a0-66ad-4abc-9eac-a2f4136ee2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TENIS'])[2]/following::li[2]</value>
      <webElementGuid>683b4505-ffc0-404b-8be6-d6d8050be304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLAYERAS'])[2]/preceding::li[1]</value>
      <webElementGuid>d980fe95-3bdf-4c4e-89b6-4f574efabceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOTAS'])[2]/preceding::li[2]</value>
      <webElementGuid>651130b0-9b7c-4bc3-86bc-547c980e63f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a/div/ul/li</value>
      <webElementGuid>d3bd42ca-c2f7-47d4-94fc-cd7dbfc57b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'CHAMARRAS' or . = 'CHAMARRAS')]</value>
      <webElementGuid>2bdf3441-7c23-4821-ade8-f462d08281af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
