<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eliminar_cart</name>
   <tag></tag>
   <elementGuidId>a4a5c6f9-bc9f-462b-aa85-ea78c753b62a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[(text() = 'Eliminar' or . = 'Eliminar')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a86e246-2494-45db-b0e8-b3634342815d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn-myBag--elements a-btn--elementsMyBags a_myBag__btnElements--desktop </value>
      <webElementGuid>2cbf3e43-cb9e-45c4-9fe9-89b1b30220b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>45fb0939-300c-42bf-88bc-01102ad30fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1111964218&quot;)/div[@class=&quot;o-myBag__column o-myBag__column--triple&quot;]/div[@class=&quot;o-myBag__description&quot;]/div[@class=&quot;m-latestinlineElement__block m-latestinlineElement--triple&quot;]/button[@class=&quot;a-btn-myBag--elements a-btn--elementsMyBags a_myBag__btnElements--desktop&quot;]</value>
      <webElementGuid>287641f2-8107-4c9d-8f2c-8c00bfa3da3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1111964218']/div/div[2]/div[3]/button[4]</value>
      <webElementGuid>4806c5d9-a051-4086-b527-76e0d4db6a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mover a Wishlist'])[1]/following::button[1]</value>
      <webElementGuid>666563b7-ea81-4285-be23-6dc1da70cb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar ahora'])[1]/following::button[2]</value>
      <webElementGuid>a9b738ec-abcb-49af-afdc-8510543baa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::button[2]</value>
      <webElementGuid>5fd3e93e-f23f-46b3-a4c3-1d16815b1887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrega estimada:'])[2]/preceding::button[3]</value>
      <webElementGuid>e6bda8bc-9428-49c3-81b8-a9ae9b63ecbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eliminar']/parent::*</value>
      <webElementGuid>e769dbb6-2761-4cca-bdb5-b211c42710be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>a2efd80a-53d3-4459-abed-7d2bcf95a189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Eliminar' or . = 'Eliminar')]</value>
      <webElementGuid>699d8e80-4978-46b5-a231-8ab94a8011e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
