<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SeguirComprando_cart</name>
   <tag></tag>
   <elementGuidId>38b88d2a-3bc3-45fa-8cca-f4300f3fbe35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='t-myBag__continueToBuy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.a-btn.a-btn--secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e365c1e0-0a8c-421f-a8ad-1ae22942974b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--secondary</value>
      <webElementGuid>276aa18c-1fea-445e-880c-6514dbd7a1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seguir Comprando</value>
      <webElementGuid>db90c150-2e84-441a-8f1b-447789e1300b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;cart-alert-top&quot;]/section[@class=&quot;container-fluid&quot;]/div[@class=&quot;rowE&quot;]/div[@class=&quot;t-myBag__footerTab d-none d-lg-block&quot;]/div[@class=&quot;t-myBag__continueToBuy&quot;]/button[@class=&quot;a-btn a-btn--secondary&quot;]</value>
      <webElementGuid>8776c562-f035-4933-9233-239ce3939d3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/div[5]/div/button</value>
      <webElementGuid>6819ffc3-2d83-450e-8dd5-50cf0cc1a3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complementa tu compra'])[1]/following::button[4]</value>
      <webElementGuid>aa49da02-b20c-41e5-85de-79286a960570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar'])[1]/following::button[4]</value>
      <webElementGuid>3a9b6353-3eb9-48a8-8a53-90c20949dc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe un mensaje'])[1]/preceding::button[1]</value>
      <webElementGuid>5ac62d22-45df-493c-9242-3559d7a72e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::button[1]</value>
      <webElementGuid>f532009b-ec25-437f-9891-ad93ac00938e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seguir Comprando']/parent::*</value>
      <webElementGuid>dc5f7531-e5d3-4dd1-8ac3-d9292cd1d57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>03285ac3-1c39-4998-b2a8-8d326446dd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Seguir Comprando' or . = 'Seguir Comprando')]</value>
      <webElementGuid>4c0470a0-d99f-4f13-bf17-205663adf5b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
