<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paymentSection_orderDetails</name>
   <tag></tag>
   <elementGuidId>3de7d874-cefc-4b55-baa3-1db80912bce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='col-12 m-col col-lg-5 d-none d-lg-block']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.m-col.col-lg-5.d-none.d-lg-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6f7deb7-e3ae-47a7-b2cb-7630479972d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12 m-col col-lg-5 d-none d-lg-block</value>
      <webElementGuid>03fee0ba-a2ff-4582-8ba3-5095514e4700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forma de pagoEfectivoDescargar ticket de pago</value>
      <webElementGuid>4e5e0722-0689-4779-82b5-b94633cdadd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent Detalles_MainContent_Margin_top&quot;]/div[@class=&quot;o-orderDetail&quot;]/div[@class=&quot;row o-row&quot;]/div[@class=&quot;col-12 o-col&quot;]/div[@class=&quot;m-orderDetail__address m-orderDetail__card Detalles_Card_Margin_bottom d-none d-lg-block&quot;]/div[@class=&quot;row m-row&quot;]/div[@class=&quot;col-12 m-col col-lg-5 d-none d-lg-block&quot;]</value>
      <webElementGuid>a439eea3-f470-43ef-8640-e60a0064a365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[4]/div[2]/div[2]/div/div[3]/div/div/div[2]</value>
      <webElementGuid>148074b9-c29f-4f10-bcf2-f1ea7f1f5d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1349.25'])[2]/following::div[5]</value>
      <webElementGuid>c39c2a27-94db-4f64-8ae0-1ab66b14fe0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZAPATO DOCKERS D2122, 28 CM, CHOCOLATE'])[1]/following::div[22]</value>
      <webElementGuid>857bc1ed-024b-4287-a499-dfc696a64d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>ed835f5e-7246-41d7-8e62-30e63e964fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Forma de pagoEfectivoDescargar ticket de pago' or . = 'Forma de pagoEfectivoDescargar ticket de pago')]</value>
      <webElementGuid>db496c09-1487-421e-adf0-e2975bcaa664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
