<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>referenceNumber_orderDetails</name>
   <tag></tag>
   <elementGuidId>7feba2eb-e8ac-449e-9403-80f7cb9d9dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p[@class='Deatlles_Estatus']//b[@class='Detalles_BoldBlack'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b.Detalles_BoldBlack</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>6d58463c-a0c7-4a57-ba8c-6607a0474f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Detalles_BoldBlack</value>
      <webElementGuid>fce0b74b-6e49-4fd2-8d2a-1263f6e5298b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1010103874017249</value>
      <webElementGuid>f8f4e693-c2e2-4e4e-94e1-85348d555abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent Detalles_MainContent_Margin_top&quot;]/div[@class=&quot;o-orderDetail&quot;]/div[@class=&quot;row o-row&quot;]/div[@class=&quot;col-12 o-col&quot;]/div[@class=&quot;m-orderDetail__address m-orderDetail__card Detalles_Card_Margin_bottom d-none d-lg-block&quot;]/div[@class=&quot;row m-row&quot;]/div[@class=&quot;col-12 m-col col-lg-4 d-none d-lg-block&quot;]/p[@class=&quot;Deatlles_Estatus&quot;]/b[@class=&quot;Detalles_BoldBlack&quot;]</value>
      <webElementGuid>8b4e6a8c-9f42-45e1-a3d6-4e67ce15d471</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[4]/div[2]/div[2]/div/div[3]/div/div/div[3]/p[3]/b</value>
      <webElementGuid>8bc292e2-3922-46b9-9dff-5ebd936a7dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago pendiente'])[1]/following::b[1]</value>
      <webElementGuid>976a8827-3653-4012-be08-2f466d308575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar ticket de pago'])[1]/following::b[1]</value>
      <webElementGuid>edefbd83-5f79-4e90-aa46-a62bde4005fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Efectivo'])[2]/preceding::b[3]</value>
      <webElementGuid>a5b46544-69c8-4736-b51b-0b0f4c6871e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar ticket de compra'])[1]/preceding::b[3]</value>
      <webElementGuid>2d4d7d99-e347-4eea-928f-ade9aca6295a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1010103874017249']/parent::*</value>
      <webElementGuid>c4016875-5e16-48f6-aa89-a56dcc7b1f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>1a36033d-d097-46b1-97e8-c29d20b75fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '1010103874017249' or . = '1010103874017249')]</value>
      <webElementGuid>7629531b-5afd-4ce5-a0fa-1994317f2cfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
