<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CHAMARRAS</name>
   <tag></tag>
   <elementGuidId>590c0458-c13d-4be6-b116-43c4d550c290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o-blp-mainContent.order-1.order-lg-2.px-0.px-lg-0.d-none.d-lg-block > div.contaier-fluid.p-0 > div.row > div.container-promo01.col-12.col-lg-6 > a.m-mainBanner__link > div.banner-promo03-desc.category-promo03 > ul.btn-catpromo03 > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div[4]/main/div[2]/div/div[2]/div/a/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8d02ea9e-7c3c-4822-945d-9f888f27e723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHAMARRAS</value>
      <webElementGuid>d17eb7f5-2e0e-4256-a44a-c9e4b54c7bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;o-blp-mainContent order-1 order-lg-2 px-0 px-lg-0 d-none d-lg-block&quot;]/div[@class=&quot;contaier-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container-promo01 col-12 col-lg-6&quot;]/a[@class=&quot;m-mainBanner__link&quot;]/div[@class=&quot;banner-promo03-desc category-promo03&quot;]/ul[@class=&quot;btn-catpromo03&quot;]/li[1]</value>
      <webElementGuid>eaacf546-ef01-4076-8888-252f712bc672</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[4]/main/div[2]/div/div[2]/div/a/div/ul/li</value>
      <webElementGuid>24e5d577-c80a-4b1a-b241-9568af448aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROPA INTERIOR'])[2]/following::li[1]</value>
      <webElementGuid>081ef456-2f51-462c-93c2-0708bb0d79fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TENIS'])[2]/following::li[2]</value>
      <webElementGuid>2f6f8a47-7178-4308-869e-779fdc75dffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLAYERAS'])[2]/preceding::li[1]</value>
      <webElementGuid>ff57deb1-39e3-43f4-b694-fef01be1a311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOTAS'])[2]/preceding::li[2]</value>
      <webElementGuid>2808c6a2-1cf5-47df-8145-f76357dd640b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a/div/ul/li</value>
      <webElementGuid>b0f17975-c220-41bf-9f94-2f6bc789a7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'CHAMARRAS' or . = 'CHAMARRAS')]</value>
      <webElementGuid>3ff27766-37f4-45a0-b815-68dfb782814d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
