<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quantity_value_PDP</name>
   <tag></tag>
   <elementGuidId>5b02cedc-b593-49fb-8306-4c0d95c7b983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='d-none d-lg-block']//input)</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-stickyBarPdp__inputQty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34e12591-6fbf-4bfc-af8d-2eca43f57204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-stickyBarPdp__inputQty</value>
      <webElementGuid>e2bb5c4c-6051-4b60-989d-5005c799f4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-stickyBar__inputQty  m-stickyBarPdp__inputQty</value>
      <webElementGuid>4c4e8f43-881c-4e39-b864-a2213efa0c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73c6b24c-0c21-4aa7-ad7d-3f033ee2c09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ff2037e3-35a2-4430-8c04-9ebe7dd5293f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bb3aa0f5-630b-475a-b031-772ff25b5e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/div[@class=&quot;d-none d-lg-block&quot;]/div[@class=&quot;row o-product__productQty pto&quot;]/div[@class=&quot;col-12 mt-2 mb-3&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;m-stickyBar__qtyInputs d-flex&quot;]/input[@id=&quot;a-stickyBarPdp__inputQty&quot;]</value>
      <webElementGuid>a1a8a6f4-0590-4bb4-ac21-f543571f2dad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a-stickyBarPdp__inputQty']</value>
      <webElementGuid>654b1c02-d2d4-4f76-a1d4-917c0fd182a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/div[6]/div/div[2]/div/div/input</value>
      <webElementGuid>a3dcc557-00c4-4d95-a61e-3a7de5f649bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/input</value>
      <webElementGuid>6c4439be-bb09-4b23-86ff-41eabbc18824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a-stickyBarPdp__inputQty' and @type = 'text']</value>
      <webElementGuid>52a011d1-28a4-4396-8c57-224eff4a3ce0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
