<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchButtton_HP</name>
   <tag></tag>
   <elementGuidId>086a5c8f-7f13-4b3f-b513-a1b7a808dbbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='input-group-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>68f3916e-5f7b-48d4-903d-e6b210e31a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678044748397</value>
      <webElementGuid>44103541-9961-4838-9b71-5cc3b2d0d51b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
