<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>priceSummary_opc</name>
   <tag></tag>
   <elementGuidId>df56d9e6-1f22-4cac-b679-22fcc226751b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='opc_buysummary']/div[2]/div)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.m-breakdownExpenses__detail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26d47154-a118-4082-b0e5-560974ae642f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-breakdownExpenses__detail</value>
      <webElementGuid>74ad57f3-cc45-46a1-9688-750b2ef7d70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subtotal (1 productos):Descuento:Cupones:Costo de envío:$1,799.00$449.75$0.00Gratis</value>
      <webElementGuid>54b7c71c-721a-4e99-8469-abe6c94bae9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_buysummary&quot;)/div[@class=&quot;m-breakdownExpenses w-100 mt-0&quot;]/div[@class=&quot;m-breakdownExpenses__detail&quot;]</value>
      <webElementGuid>5b5d6555-943d-4a46-ac09-fd4e8ea1d61e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_buysummary']/div[2]/div</value>
      <webElementGuid>1f628def-f6e0-4ba9-8e9c-05e3e0a7ed26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cupones'])[1]/following::div[3]</value>
      <webElementGuid>27f47170-2483-45f5-bdc4-149813bb1521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resumen de compra'])[1]/following::div[6]</value>
      <webElementGuid>c24a0cae-0fa1-4503-bc13-14fff930a0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirma tu compra'])[2]/preceding::div[16]</value>
      <webElementGuid>4344d6a6-cf7a-4b38-bb1b-4052018c2aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/preceding::div[16]</value>
      <webElementGuid>479ca618-eedf-4597-9144-2e6790464cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div</value>
      <webElementGuid>37a20d26-905d-4dc0-a1f6-fbfb081cb9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Subtotal (1 productos):Descuento:Cupones:Costo de envío:$1,799.00$449.75$0.00Gratis' or . = 'Subtotal (1 productos):Descuento:Cupones:Costo de envío:$1,799.00$449.75$0.00Gratis')]</value>
      <webElementGuid>98c5621b-c492-48e5-a908-d3b9616ad83c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
