<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deliveryAddressHeading_address_opc</name>
   <tag></tag>
   <elementGuidId>74d09d9f-17df-4aa2-8278-1aaa12491a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Direcciones de Entrega')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>3b689952-d430-4873-a579-73a772486555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>dfa3183b-c88a-47c5-94a7-b1659e975823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Entrega</value>
      <webElementGuid>37dddbce-ce95-448c-9b8e-72fbb383110c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_deliveryAddress&quot;)/h6[@class=&quot;undefined&quot;]</value>
      <webElementGuid>fcd48c31-cfda-4575-a227-f0383e2020cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_deliveryAddress']/h6</value>
      <webElementGuid>79843f63-c586-465c-90e2-b139ebaeac71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirma tu compra'])[1]/following::h6[1]</value>
      <webElementGuid>1b7ff6b8-c7c2-4c24-8640-f9e6f9422b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace con cualquier tarjeta de crédito/débito.'])[1]/following::h6[1]</value>
      <webElementGuid>289f4d2c-db87-4d3c-8ae0-b313a187b370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar'])[1]/preceding::h6[1]</value>
      <webElementGuid>e624fee5-8df3-4c0b-b3fe-3ff686c86734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Entrega']/parent::*</value>
      <webElementGuid>51d445b8-3769-4006-b878-1cc241fc5a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>a47b3ca2-30d9-4f38-83f6-eb2b08b3a78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = '1. Entrega' or . = '1. Entrega')]</value>
      <webElementGuid>5b022e6c-7ad7-4a79-9c61-9154c5bd74a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
