<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Compartir</name>
   <tag></tag>
   <elementGuidId>934bb06e-06d7-4794-8569-13490da7c822</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='social-modal']/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-header.header > #social-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>63190fb3-fdea-4c61-af09-7e6b1887f185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>a6490ad7-c490-46de-b109-6e5e81c6235a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>social-modal</value>
      <webElementGuid>d909229a-219c-437f-8a6c-f1f05f5767f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compartir</value>
      <webElementGuid>ca1c305a-55ad-4599-b131-7f79b9a5d363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;richContID&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 pr-lg-3 pl-lg-3&quot;]/div[@id=&quot;social-modal&quot;]/div[@class=&quot;modal-dialog modal-sm modal-dialog-centered modal-small&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header header&quot;]/h4[@id=&quot;social-modal&quot;]</value>
      <webElementGuid>45c23bdb-2174-44a4-8483-fe836efb7c86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='social-modal']</value>
      <webElementGuid>4677a180-68fc-4f15-97d8-5dad546a3c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='social-modal']/div/div/div/h4</value>
      <webElementGuid>02ec822f-287e-43c9-9e8e-c4c41b7c7ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Políticas'])[1]/following::h4[1]</value>
      <webElementGuid>58de5bdd-b654-4c28-82a5-bdcb4f233644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piel'])[2]/following::h4[2]</value>
      <webElementGuid>c0170987-66ad-498f-b889-8a07cd3faf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::h4[1]</value>
      <webElementGuid>ec7edc0d-bcb6-4250-99ca-6b67a4115d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::h4[1]</value>
      <webElementGuid>85efb6d8-1c7b-445b-b15b-0830935d88ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/h4</value>
      <webElementGuid>d2e8333d-04d1-481b-9c71-0f48a09548cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'social-modal' and (text() = 'Compartir' or . = 'Compartir')]</value>
      <webElementGuid>5db8c6dc-1b73-4824-aa52-ea8e075941a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
