<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L1_Category4_HP</name>
   <tag></tag>
   <elementGuidId>e97faa76-b640-4bf0-83d4-238de885fa7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='a-dekstop__categoryLink']//span)[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d90da3d3-c58f-48e4-af9d-c60e265cae0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678033965677</value>
      <webElementGuid>41c5f130-0b83-418b-8bb0-34249c3bc470</webElementGuid>
   </webElementProperties>
</WebElementEntity>
