<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchbar_HP</name>
   <tag></tag>
   <elementGuidId>417e48f0-be47-451b-aa56-6e549325aae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='form-control search-bar plp-no__results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainSearchbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44ffeed9-6159-4b78-baa8-1c25f4b9653e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainSearchbar</value>
      <webElementGuid>883b4ca5-644c-4de9-a419-153eef5a3526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-bar plp-no__results</value>
      <webElementGuid>fb8f19f3-21ee-4aa8-baf3-97a2ea5b93c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Buscar ...</value>
      <webElementGuid>d81ba31c-3661-41b8-9928-9e1684a3a2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cdc8438-d98b-4ccb-8432-7b72799071b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar...</value>
      <webElementGuid>8aae5d14-ac3b-4875-b136-bf6134aede07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>89cdc9c8-75de-47df-a1f2-d1e8f1fb24ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainSearchbar&quot;)</value>
      <webElementGuid>3e569176-a79b-4301-9729-2105fbcf2abc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainSearchbar']</value>
      <webElementGuid>e803fb71-8b40-41db-bc8d-e925ade3ba13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[4]/div[2]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>f88883ea-c38c-4d29-b4a4-9db2bc6c0b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>848141ba-3f7c-4613-9b4a-f7ba24b6c487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mainSearchbar' and @type = 'text' and @placeholder = 'Buscar...']</value>
      <webElementGuid>4eaf7635-3b0e-44e0-b77e-17238f165737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
