<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Busca una tiendaFiltrarTo navigate, pre_3c2e77</name>
   <tag></tag>
   <elementGuidId>b3800773-5fcc-47d2-97c3-a7049aa0881b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-8.m-storeLocator-map.px-0.px-lg-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76484f1a-c3bb-4eb7-a7a9-fad8361e608d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-lg-8 m-storeLocator-map px-0 px-lg-3</value>
      <webElementGuid>23360bb9-6af7-43e1-99e7-a4ea925730c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Busca una tiendaFiltrarTo navigate, press the arrow keys.Use ctrl + scroll to zoom the map←Move left→Move right↑Move up↓Move down+Zoom in-Zoom outHomeJump left by 75%EndJump right by 75%Page UpJump up by 75%Page DownJump down by 75%MapTerrainSatelliteLabelsKeyboard shortcutsMap DataMap data ©2023 INEGIMap data ©2023 INEGI200 m Click to toggle between metric and imperial unitsTerms of UseReport a map errorUsar mi ubicación</value>
      <webElementGuid>a15b452c-e87d-4d9d-bc9d-c33635e58399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container p-0&quot;]/div[@class=&quot;row mt-lg-3 mb-lg-5 mb-0&quot;]/div[@class=&quot;col-lg-8 m-storeLocator-map px-0 px-lg-3&quot;]</value>
      <webElementGuid>e108e494-beef-4d68-85d5-592d6ee56d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div</value>
      <webElementGuid>7b4bdb78-b2ae-492c-a2c9-83f54f52d744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>d9c9d3cd-0273-46d8-912b-c90b35297c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Busca una tiendaFiltrarTo navigate, press the arrow keys.Use ctrl + scroll to zoom the map←Move left→Move right↑Move up↓Move down+Zoom in-Zoom outHomeJump left by 75%EndJump right by 75%Page UpJump up by 75%Page DownJump down by 75%MapTerrainSatelliteLabelsKeyboard shortcutsMap DataMap data ©2023 INEGIMap data ©2023 INEGI200 m Click to toggle between metric and imperial unitsTerms of UseReport a map errorUsar mi ubicación' or . = 'Busca una tiendaFiltrarTo navigate, press the arrow keys.Use ctrl + scroll to zoom the map←Move left→Move right↑Move up↓Move down+Zoom in-Zoom outHomeJump left by 75%EndJump right by 75%Page UpJump up by 75%Page DownJump down by 75%MapTerrainSatelliteLabelsKeyboard shortcutsMap DataMap data ©2023 INEGIMap data ©2023 INEGI200 m Click to toggle between metric and imperial unitsTerms of UseReport a map errorUsar mi ubicación')]</value>
      <webElementGuid>ad8823df-37fc-463e-912a-2a3f1dff7fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
