<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L3_hp</name>
   <tag></tag>
   <elementGuidId>17d56974-b09c-43bf-85dd-69fcb72d2fe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Lentes')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0481801c-2e02-478e-bcb5-6081e1064ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-desktop__subcategoryTitle subcategoryLevel-3</value>
      <webElementGuid>64133d66-1a22-437b-8d27-a73d00e46441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/home#!</value>
      <webElementGuid>2763c420-3cb0-421b-8f35-c885f2f9bb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lentes</value>
      <webElementGuid>817d628c-dd44-49db-8256-6cb9c82e0d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CAT5020003&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-top&quot;]/div[@class=&quot;col-lg-8 category-menu&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 pb-3&quot;]/ul[@class=&quot;m-desktop-subcategory-list&quot;]/li[6]/a[@class=&quot;a-desktop__subcategoryTitle subcategoryLevel-3&quot;]</value>
      <webElementGuid>0e684e84-e17c-4db4-bc6c-2345935ffa56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CAT5020003']/div/div[2]/div/div/div[3]/ul/li[6]/a</value>
      <webElementGuid>f68684cf-1792-4fff-83ca-08c5ac3c3df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lentes')]</value>
      <webElementGuid>5a4cb469-223b-4c8b-bda9-db5ebd04316a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carteras'])[2]/following::a[1]</value>
      <webElementGuid>2eff7568-7252-47af-9ba7-9c74bc11b620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gorras y Sombreros'])[1]/following::a[2]</value>
      <webElementGuid>417d3f18-4816-4365-ba5e-2e0eea990c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corbatas, Moños y Pañuelos'])[1]/preceding::a[1]</value>
      <webElementGuid>226db5f3-d318-4962-a1d4-316c92f25ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cinturones'])[1]/preceding::a[2]</value>
      <webElementGuid>7fa2b13f-eec7-4d6f-a24c-a61668e5b493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lentes']/parent::*</value>
      <webElementGuid>a11eeb6a-f6a8-4608-adab-0aaa19e64930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/home#!')])[69]</value>
      <webElementGuid>872b3cfd-ba68-49aa-9014-7ef0f01fd548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/li/div/div/div/div[2]/div/div/div[3]/ul/li[6]/a</value>
      <webElementGuid>920527d5-02ef-45ec-9467-242d7896338f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/home#!' and (text() = 'Lentes' or . = 'Lentes')]</value>
      <webElementGuid>2ed0f2a3-956d-4f08-b31d-c4747e7696e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
