<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Color_variants-normalizedColor-Blanco_plp</name>
   <tag></tag>
   <elementGuidId>242f756f-9d29-4fca-aad1-f3b1128fb2f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul//li//a[@class='a-productColor__item a-product__color atom-color'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#variants-normalizedColor-Blanco</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>337c4b3b-9213-423e-a87f-6d90b370e7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-productColor__item a-product__color atom-color</value>
      <webElementGuid>e22765b7-a56c-405c-b648-29309c8dcd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>variants-normalizedColor-Blanco</value>
      <webElementGuid>b417fd01-27ff-41ed-9b5a-a0df4bb8b2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>055dba97-4bea-47ff-ba9a-22a5d1ae7c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;variants-normalizedColor-Blanco&quot;)</value>
      <webElementGuid>40722b20-2ec1-40c0-9b26-381392d285ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='variants-normalizedColor-Blanco']</value>
      <webElementGuid>0c68b468-94ea-4c86-a9d7-cec81aae30eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[26]/div[2]/ul/li/a</value>
      <webElementGuid>b2ccc7d4-377e-4e7c-bcb8-c0b678874381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div[2]/ul/li/a</value>
      <webElementGuid>76758329-477f-4ff9-87c8-c1f4a81c4c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'variants-normalizedColor-Blanco']</value>
      <webElementGuid>2bfeb03f-b55b-4ab6-80ca-bfed27c9ac2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
