<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productImage2_plp</name>
   <tag></tag>
   <elementGuidId>cc6b0a01-94ea-45c5-b061-8fec0616da8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section//img[@id='img_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>7f6f70f0-6ccb-4150-8f12-c53ad556c897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1677462528700</value>
      <webElementGuid>14230c21-63bc-439d-b3b4-80650da54cfd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
