<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tiendas</name>
   <tag></tag>
   <elementGuidId>c843b513-7f25-4f4e-b196-191b21cfc078</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Tiendas']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tiendas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69cefa21-7367-40c1-ac0a-1e367134e387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tiendas</value>
      <webElementGuid>99d56129-2777-4028-97bb-e2744bd7f1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiendas</value>
      <webElementGuid>1cd027ad-111f-4047-befa-0117ef03a6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;grid-container ng-scope&quot;]/div[@class=&quot;grid-100 stores-ayuda&quot;]/div[@class=&quot;grid-70 prefix-15 sufix-75 contact&quot;]/div[@class=&quot;grid-45 block-stores&quot;]/a[1]/div[@class=&quot;grid-90&quot;]/div[@class=&quot;contact-description locstore&quot;]/div[@class=&quot;tiendas&quot;]</value>
      <webElementGuid>674d3694-13e5-48ba-85eb-529ecb1e5f70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[6]/div/div/a/div[2]/div/div</value>
      <webElementGuid>d5e73b67-cd83-4e3e-8d24-4137fd720c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ventas Corporativas'])[2]/following::div[8]</value>
      <webElementGuid>af8772ac-bd87-4824-9d8d-cef2fa606b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ventas Corporativas'])[1]/following::div[8]</value>
      <webElementGuid>b8bf4077-8f48-479a-98c6-20226e07a04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::div[1]</value>
      <webElementGuid>441b93ac-e304-42b7-ba8d-c6e31e1a2e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contáctanos'])[1]/preceding::div[3]</value>
      <webElementGuid>b469c41f-36ab-4115-8bb1-412c22add64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tiendas']/parent::*</value>
      <webElementGuid>58e7d910-afd2-4134-bcbc-204443afee5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div/div</value>
      <webElementGuid>4d1ea369-f6ac-49fa-bba5-37913499dd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tiendas' or . = 'Tiendas')]</value>
      <webElementGuid>47ab9ccd-6ea4-4e77-bfa9-910b9de836e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
