<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Liverpool Paseo Interlomas</name>
   <tag></tag>
   <elementGuidId>a2c32dbd-ab48-4301-947b-46c394fbd492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/aside/div/div[10]/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5064e84e-76c6-4bd8-ac49-3e3c811a1086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item a-list-li-scrollable</value>
      <webElementGuid>a560e53e-ce07-4442-9837-892635a48ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Liverpool Paseo Interlomas </value>
      <webElementGuid>9373aa61-f9da-464a-a71b-974d75d3d01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container p-0&quot;]/div[@class=&quot;row mt-lg-3 mb-lg-5 mb-0&quot;]/aside[@class=&quot;col-lg-4&quot;]/div[@class=&quot;o-storeLocator-aside d-none d-lg-block&quot;]/div[@class=&quot;m-list-scrollable&quot;]/ul[@class=&quot;list-group m-list-ul-scrollable&quot;]/li[@class=&quot;list-group-item a-list-li-scrollable&quot;]</value>
      <webElementGuid>4a80b4f7-30ae-4902-93b6-06156543268d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/aside/div/div[10]/ul/li[3]</value>
      <webElementGuid>0b52e80c-74fe-43ac-ad94-f76e93f99131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Liverpool Paseo Interlomas']/parent::*</value>
      <webElementGuid>44d026c7-efd0-4fbc-95b6-9363e22af13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/ul/li[3]</value>
      <webElementGuid>1378b26d-3227-4136-bd51-105f1ed4cee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '  Liverpool Paseo Interlomas ' or . = '  Liverpool Paseo Interlomas ')]</value>
      <webElementGuid>286a2304-cb01-4630-9a9e-82596e435370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
