<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AGUASCALIENTESBAJA CALIFORNIABAJA CA_5addf3</name>
   <tag></tag>
   <elementGuidId>2b7de9ff-b0ee-43b7-ab23-4ea6c3af5d94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-state']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-state</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>36af1d35-37da-4385-8c36-4d41cdcfad66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-select__native-control</value>
      <webElementGuid>87300a70-37a6-488a-8fc5-521301ffbeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-state</value>
      <webElementGuid>9d0c8db4-15c8-47e6-a259-5aed5a4b77cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AGUASCALIENTESBAJA CALIFORNIABAJA CALIFORNIA SURCAMPECHECOAHUILACOLIMACHIAPASCHIHUAHUACDMX/ZONA METROPOLITANADURANGOGUANAJUATOGUERREROHIDALGOJALISCOMÉXICOMICHOACÁNMORELOSNAYARITNUEVO LEÓNOAXACAPUEBLAQUERÉTAROQUINTANA ROOSAN LUIS POTOSÍSINALOASONORATABASCOTAMAULIPASTLAXCALAVERACRUZYUCATÁNZACATECAS</value>
      <webElementGuid>97dfe934-3491-421b-a5a0-7a17473e8ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container p-0&quot;]/div[@class=&quot;row mt-lg-3 mb-lg-5 mb-0&quot;]/aside[@class=&quot;col-lg-4&quot;]/div[@class=&quot;o-storeLocator-aside d-none d-lg-block&quot;]/div[@class=&quot;mdc-ripple-upgraded mdc-select--focused mdc-ripple-upgraded--background-focused&quot;]/div[@class=&quot;mdc-select mdc-select--outlined mdc-select--focused&quot;]/select[@id=&quot;select-state&quot;]</value>
      <webElementGuid>20dbbc2b-cef1-4fa3-8f39-4a6ceec4cedc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-state']</value>
      <webElementGuid>98df9e86-401c-4688-a2f6-05164ff12968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/aside/div/div[2]/div/select</value>
      <webElementGuid>debab3ff-56d2-4eae-8e17-77ecda9eaccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Busca un Liverpool, Centro comercial o Dutty free'])[1]/following::select[1]</value>
      <webElementGuid>78e70a84-b1de-4804-b537-b7ea304e5c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiendas'])[2]/following::select[1]</value>
      <webElementGuid>3f632b1b-6229-452d-ad48-aad6f173574f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione estado'])[1]/preceding::select[1]</value>
      <webElementGuid>7d728bac-974e-455a-ac62-d9a1d41a13ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar por tipo de tienda'])[1]/preceding::select[2]</value>
      <webElementGuid>0052cc75-5dce-4443-8bf4-73a96be96c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>222455be-1201-477d-9bef-75f93852823f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'select-state' and (text() = 'AGUASCALIENTESBAJA CALIFORNIABAJA CALIFORNIA SURCAMPECHECOAHUILACOLIMACHIAPASCHIHUAHUACDMX/ZONA METROPOLITANADURANGOGUANAJUATOGUERREROHIDALGOJALISCOMÉXICOMICHOACÁNMORELOSNAYARITNUEVO LEÓNOAXACAPUEBLAQUERÉTAROQUINTANA ROOSAN LUIS POTOSÍSINALOASONORATABASCOTAMAULIPASTLAXCALAVERACRUZYUCATÁNZACATECAS' or . = 'AGUASCALIENTESBAJA CALIFORNIABAJA CALIFORNIA SURCAMPECHECOAHUILACOLIMACHIAPASCHIHUAHUACDMX/ZONA METROPOLITANADURANGOGUANAJUATOGUERREROHIDALGOJALISCOMÉXICOMICHOACÁNMORELOSNAYARITNUEVO LEÓNOAXACAPUEBLAQUERÉTAROQUINTANA ROOSAN LUIS POTOSÍSINALOASONORATABASCOTAMAULIPASTLAXCALAVERACRUZYUCATÁNZACATECAS')]</value>
      <webElementGuid>9714e0cf-2cf8-42ec-b134-17310048bfa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
