<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alternate_Img_pdp_1</name>
   <tag></tag>
   <elementGuidId>99353c57-e1d9-406f-adf0-2df4961dcf50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.img-viewer.active-thumb > div.slide___3-Nqo.carousel__slide.carousel__slide--visible > div.slideInner___2mfX9.carousel__inner-slide > img.pdpthumb.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='slideInner___2mfX9 carousel__inner-slide'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>722d47bd-63ff-48a0-85f6-61a52f00e4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pdpthumb lazyloaded</value>
      <webElementGuid>85b04607-3f7f-48ac-91c2-527175459dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/lg/1114907117_2p.jpg</value>
      <webElementGuid>1bdfb096-e002-43af-bc67-80573e25c687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bota corta Quirelli para hombre 3</value>
      <webElementGuid>df571d46-422d-42a5-b6b5-af0a849777f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d5a61aff-5baf-4bcb-9357-a8129945f085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/lg/1114907117_2p.jpg</value>
      <webElementGuid>bda2ca30-3d86-49ef-b06e-af97384205b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listBeforeEtalage&quot;)/div[@class=&quot;verticalSlider___34ZFD carousel__slider carousel__slider--vertical&quot;]/div[@class=&quot;carousel__slider-tray-wrapper verticalSlideTrayWrap___2nO7o carousel__slider-tray-wrap--vertical&quot;]/div[@class=&quot;sliderTray___-vHFQ sliderAnimation___300FY carousel__slider-tray verticalTray___12Key carousel__slider-tray--vertical&quot;]/li[@class=&quot;img-viewer active-thumb&quot;]/div[@class=&quot;slide___3-Nqo carousel__slide carousel__slide--visible&quot;]/div[@class=&quot;slideInner___2mfX9 carousel__inner-slide&quot;]/img[@class=&quot;pdpthumb lazyloaded&quot;]</value>
      <webElementGuid>7a5ddbf9-49a5-47df-bde1-5e1078975079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='listBeforeEtalage']/div/div/div/li[3]/div/div/img</value>
      <webElementGuid>9982ab66-11b5-4117-a0fe-dd206ad6d1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bota corta Quirelli para hombre 3']</value>
      <webElementGuid>882783dc-ea1b-4866-94f3-c87a188b208f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/img</value>
      <webElementGuid>b93323a2-8d90-4715-8877-fa8e622eaa91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Bota corta Quirelli para hombre 3' and @src = 'https://ss237.liverpool.com.mx/lg/1114907117_2p.jpg']</value>
      <webElementGuid>783e1820-7e77-4a46-839d-53a1f80c1899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
