<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AlternateImg_pdp</name>
   <tag></tag>
   <elementGuidId>d1e60085-3b95-41da-afa5-3bb83c640cab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.pdpthumb.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@class='pdpthumb lazyloaded'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>15fdc987-c970-40c6-ace2-435da2c41190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pdpthumb lazyloaded</value>
      <webElementGuid>9281e39b-3fe9-4ef7-a53c-28d16083b21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://ss213.liverpool.com.mx/lg/1113670114.jpg</value>
      <webElementGuid>31d55914-4ba8-4329-b861-578707f10586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lentes de sol Perry Ellis Pesun21015 unisex 1</value>
      <webElementGuid>1b6c466f-8333-481a-a18d-48fd7d28a376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5061d4f-1a11-418c-844f-5c039d8acb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss213.liverpool.com.mx/lg/1113670114.jpg</value>
      <webElementGuid>2ddb3628-9505-4fa8-84c3-69da58d05e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listBeforeEtalage&quot;)/div[@class=&quot;verticalSlider___34ZFD carousel__slider carousel__slider--vertical&quot;]/div[@class=&quot;carousel__slider-tray-wrapper verticalSlideTrayWrap___2nO7o carousel__slider-tray-wrap--vertical&quot;]/div[@class=&quot;sliderTray___-vHFQ sliderAnimation___300FY carousel__slider-tray verticalTray___12Key carousel__slider-tray--vertical&quot;]/li[@class=&quot;img-viewer active-thumb&quot;]/div[@class=&quot;slide___3-Nqo carousel__slide carousel__slide--visible&quot;]/div[@class=&quot;slideInner___2mfX9 carousel__inner-slide&quot;]/img[@class=&quot;pdpthumb lazyloaded&quot;]</value>
      <webElementGuid>58d7a948-8435-4d85-b2f2-e8e3a8056ec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='listBeforeEtalage']/div/div/div/li/div/div/img</value>
      <webElementGuid>25dcf290-5310-4bd6-9540-ea0fa5ca1049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lentes de sol Perry Ellis Pesun21015 unisex 1']</value>
      <webElementGuid>092cbb96-a190-401d-967b-4e3f6b6ba9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>bdcf5b1c-b56b-4b05-8120-be78fe44991b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Lentes de sol Perry Ellis Pesun21015 unisex 1' and @src = 'https://ss213.liverpool.com.mx/lg/1113670114.jpg']</value>
      <webElementGuid>7ce8d7c1-affd-4631-91fe-695cc5526d34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
