<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AlternateImg_1_pdp</name>
   <tag></tag>
   <elementGuidId>1f8a8770-ff13-4815-b5f9-51c599e7abbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.img-viewer.active-thumb > div.slide___3-Nqo.carousel__slide.carousel__slide--visible > div.slideInner___2mfX9.carousel__inner-slide > img.pdpthumb.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@class='pdpthumb lazyloaded'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>60150575-ec37-4f18-bbc6-880f0cfd147a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pdpthumb lazyloaded</value>
      <webElementGuid>21050b1e-7f65-49f0-b6e0-e59b536838b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://ss213.liverpool.com.mx/lg/1113670114_1p.jpg</value>
      <webElementGuid>ac91891f-185c-458b-b1c1-ad94ac154252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lentes de sol Perry Ellis Pesun21015 unisex 2</value>
      <webElementGuid>3229729a-e973-49d1-af04-7c89c8ccdfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7ff742a3-e818-45c1-8b07-7a4e8e4863ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss213.liverpool.com.mx/lg/1113670114_1p.jpg</value>
      <webElementGuid>bc2f59fe-2f9e-43d7-b469-4f4ab76686e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listBeforeEtalage&quot;)/div[@class=&quot;verticalSlider___34ZFD carousel__slider carousel__slider--vertical&quot;]/div[@class=&quot;carousel__slider-tray-wrapper verticalSlideTrayWrap___2nO7o carousel__slider-tray-wrap--vertical&quot;]/div[@class=&quot;sliderTray___-vHFQ sliderAnimation___300FY carousel__slider-tray verticalTray___12Key carousel__slider-tray--vertical&quot;]/li[@class=&quot;img-viewer active-thumb&quot;]/div[@class=&quot;slide___3-Nqo carousel__slide carousel__slide--visible&quot;]/div[@class=&quot;slideInner___2mfX9 carousel__inner-slide&quot;]/img[@class=&quot;pdpthumb lazyloaded&quot;]</value>
      <webElementGuid>26223fa1-c6d6-4fa8-ab49-25ca9a9c7595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='listBeforeEtalage']/div/div/div/li[2]/div/div/img</value>
      <webElementGuid>3383112b-aaf9-4f14-b88e-b2b13638e0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lentes de sol Perry Ellis Pesun21015 unisex 2']</value>
      <webElementGuid>d25b9f4b-d030-43e5-82ef-33fdb6448ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/img</value>
      <webElementGuid>31002679-5c1b-4236-9199-42c45086bae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Lentes de sol Perry Ellis Pesun21015 unisex 2' and @src = 'https://ss213.liverpool.com.mx/lg/1113670114_1p.jpg']</value>
      <webElementGuid>5915ed20-550a-4bd5-807c-603ba7842472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
