<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Solares_img-zoom-lens-id</name>
   <tag></tag>
   <elementGuidId>4e4b5409-2298-4e15-aa9f-050a70f7a8e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img-zoom-lens-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='img-zoom-lens-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ae66e41-ae85-4a50-8aaf-45035b488922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-zoom-lens</value>
      <webElementGuid>deaddffc-b061-4e6f-8b07-9687b2e32f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img-zoom-lens-id</value>
      <webElementGuid>7135dfa2-2529-41f9-a64b-16ab26c639f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-zoom-lens-id&quot;)</value>
      <webElementGuid>9a1eb1db-feaf-4cd4-8c6e-59220e1ae323</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='img-zoom-lens-id']</value>
      <webElementGuid>099fe10b-b1bc-40e0-8e80-d36f67349d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div/div/figure/div[2]/div</value>
      <webElementGuid>e4e03960-dde9-4cc3-b552-c5ab40106ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div[2]/div</value>
      <webElementGuid>3f6e4d8e-cb67-4b17-8af0-bab21b5264b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'img-zoom-lens-id']</value>
      <webElementGuid>bee00fec-96da-4138-add3-edfc30541eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
