<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductImage_pdp</name>
   <tag></tag>
   <elementGuidId>2b2a76d6-c342-4a4b-bd59-7836f318203b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>figure.o-gallery__pdp--desktop.pzlcontainermain.d-none.d-lg-block.retain-css-property-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//figure[@class='o-gallery__pdp--desktop pzlcontainermain d-none d-lg-block retain-css-property-value'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>figure</value>
      <webElementGuid>94b6a6f8-cb5d-47ed-9b93-f43a281520cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-gallery__pdp--desktop pzlcontainermain d-none d-lg-block retain-css-property-value</value>
      <webElementGuid>3b511f69-97ee-4a03-b41d-41c58794a92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;min-vh-90&quot;]/div[@class=&quot;carousel o-product__image&quot;]/figure[@class=&quot;o-gallery__pdp--desktop pzlcontainermain d-none d-lg-block retain-css-property-value&quot;]</value>
      <webElementGuid>f314290a-6200-44fb-8876-def51df2456d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div/div/figure</value>
      <webElementGuid>d2503d4c-5a12-489a-b473-13c8148bc37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solares'])[1]/following::figure[1]</value>
      <webElementGuid>76c250c3-7d33-47a6-b49e-1043897d7f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lentes'])[1]/following::figure[1]</value>
      <webElementGuid>90c02714-fd97-4216-8d61-2d41ab1d8e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lentes de sol Perry Ellis Pesun21015 unisex'])[2]/preceding::figure[1]</value>
      <webElementGuid>5cafc7ad-bd3e-4220-b5f4-79c472929766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe una opinión'])[1]/preceding::figure[1]</value>
      <webElementGuid>55f81603-b224-431f-b749-e0506d0d3cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/figure</value>
      <webElementGuid>62fb331a-d87b-4634-8dc9-c585e9d75d84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
