<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductName_pdp (1)</name>
   <tag></tag>
   <elementGuidId>d36b1bf7-92ee-4977-8484-6d409d4da34d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.a-product__information--title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//h1[@class='a-product__information--title'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7b4c55da-957a-42c2-a044-e493511ea5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-product__information--title</value>
      <webElementGuid>022cbef7-5b53-4df3-9e80-adca5111171d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lentes de sol Perry Ellis Pesun21015 unisex</value>
      <webElementGuid>23ef26bf-f101-4913-8f7d-0419a4c2b61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/h1[@class=&quot;a-product__information--title&quot;]</value>
      <webElementGuid>354955e8-8b5a-4c10-9be2-7615b0db6d77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/h1</value>
      <webElementGuid>ed739983-ad0f-4dbd-b2b7-84fb7dd913e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solares'])[1]/following::h1[1]</value>
      <webElementGuid>15ca6cf9-ecce-4189-9a9b-aa4e63a60e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lentes'])[1]/following::h1[1]</value>
      <webElementGuid>7045bddd-0ebf-4823-b38f-b20f6aa40678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe una opinión'])[1]/preceding::h1[1]</value>
      <webElementGuid>90318639-1b9a-4a74-9aee-0a3e17d9d357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver disponibilidad en tienda'])[1]/preceding::h1[1]</value>
      <webElementGuid>c9463c90-7ff3-4fa2-84be-f40bddc948cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>1d308809-a545-413e-961e-f18cb52b1f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Lentes de sol Perry Ellis Pesun21015 unisex' or . = 'Lentes de sol Perry Ellis Pesun21015 unisex')]</value>
      <webElementGuid>2933c4ea-cf16-4307-822a-fea4de4db476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
