<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Quntity_pdp</name>
   <tag></tag>
   <elementGuidId>084e0ba7-01c2-4b83-9556-dc20ab41b559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-stickyBarPdp__inputQty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//p[@class='a-product__viewMorePromotion'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11bcc1d0-e208-496f-ab63-569ebf1e02ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-stickyBarPdp__inputQty</value>
      <webElementGuid>949b0ce8-46ee-4daa-98e4-ff8cfffec350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-stickyBar__inputQty  m-stickyBarPdp__inputQty</value>
      <webElementGuid>45b7ec45-933f-447f-8ae9-50249dc9ad3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8c51646-f914-4e36-8bd8-e24cca429563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a65eb879-a0e1-4247-a63c-1ad8a53a72d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>44c7d5e6-9c75-4379-9a6c-0f25869f4d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/div[@class=&quot;d-none d-lg-block&quot;]/div[@class=&quot;row o-product__productQty pto&quot;]/div[@class=&quot;col-12 mt-2 mb-3&quot;]/div[@class=&quot;m-stickyBar__qtyInputs d-flex&quot;]/input[@id=&quot;a-stickyBarPdp__inputQty&quot;]</value>
      <webElementGuid>7df02f05-1d13-42ae-a7f7-7cb5ed9d2844</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a-stickyBarPdp__inputQty']</value>
      <webElementGuid>53865c29-6e95-4f0b-b5d4-527b5cb13acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/div[6]/div/div[2]/div/input</value>
      <webElementGuid>c24a6d94-2c9f-4bf9-a20c-44980bf7ceb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>71a40096-600a-4c64-b458-d947797ff886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a-stickyBarPdp__inputQty' and @type = 'text']</value>
      <webElementGuid>fb8a1bb4-f46f-4a13-8ac2-171c9b0d74a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
