<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rating_pdp</name>
   <tag></tag>
   <elementGuidId>6dbb558a-1f17-4879-98b5-c787fe989cb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TT2left.TTratingBox.TTrating-4-5 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='m-product__information--rating'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>668b9bdc-4f6b-4008-8e0c-23d7d6f2732d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#ratings</value>
      <webElementGuid>39a64b5a-c9dd-4621-b2fe-9426669bb16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/div[@class=&quot;m-product__information--rating&quot;]/fieldset[@class=&quot;rating&quot;]/span[@class=&quot;TurnToReviewsTeaser&quot;]/div[@class=&quot;RRBox&quot;]/div[@class=&quot;TT2left TTratingBox TTrating-4-5&quot;]/a[1]</value>
      <webElementGuid>68b3799c-c01e-4afa-b94d-f53fc1ac828e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/div/fieldset/span/div/div/a</value>
      <webElementGuid>fd5f06a9-6800-4430-94d6-e36d31afe460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#ratings')]</value>
      <webElementGuid>28e22930-fa19-497a-b821-e9df0aa724a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/a</value>
      <webElementGuid>0359252c-a1e1-4fbb-ac29-bdec1baff2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#ratings']</value>
      <webElementGuid>47b50d59-608f-445d-a65b-7e3d562cd9f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
