<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Social_Link_pdp</name>
   <tag></tag>
   <elementGuidId>161cb141-baa4-4e38-a3b4-b6b1793d38ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homelink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='homelink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>504f2bb9-3694-4ec1-993d-75102fccdec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homelink</value>
      <webElementGuid>be7f72fa-d59b-48f8-b9d2-a9831ab50d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>c880f480-295b-4d2b-ba1d-74c914bbfeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homelink&quot;)</value>
      <webElementGuid>21cbcfd6-70d9-433b-8c9f-817d4fb822a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='homelink']</value>
      <webElementGuid>f581a0ba-8fc9-4a08-8d11-ac9b9e7c29a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_container']/div/h2</value>
      <webElementGuid>8448e77b-e52c-4752-945f-1c4d95157bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address or phone number:'])[1]/preceding::h2[1]</value>
      <webElementGuid>94200837-3ed7-4539-a05b-495cf04e059f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>543b7334-e388-47af-9597-185d6004a0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'homelink' and (text() = 'Facebook' or . = 'Facebook')]</value>
      <webElementGuid>a0ec6248-910c-4d82-8cdb-42fcad00630f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
