<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StickyProductQuantity_pdp</name>
   <tag></tag>
   <elementGuidId>c9902785-5524-4ddc-aa42-6157929f838b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='a-stickyBar__inputQty']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-stickyBar__inputQty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b289bec9-d965-48bb-9869-1f7572750d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-stickyBar__inputQty</value>
      <webElementGuid>dec8d7ed-79f5-4a11-ab24-0ce8a745a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-stickyBar__inputQty </value>
      <webElementGuid>6c93dc38-b259-4a00-a8ef-0ac06e49f9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41622bd9-4952-4fa8-aeb8-ac80b2c70698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1a1b7d6d-4cef-44b0-959e-90c9ac20c72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e199dcb8-d8e0-4cbe-90a4-ceb95ee4e1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-stickyBar__inputQty&quot;)</value>
      <webElementGuid>3497c87d-9358-470a-a80a-9ce2529252dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a-stickyBar__inputQty']</value>
      <webElementGuid>8c4f03bc-ffa2-408d-b98d-06d2ff203cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>e8e0f837-c2bb-4072-91ed-2f49c4862bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>23532c49-4a64-4e1a-a9cf-6c8c12ed5689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a-stickyBar__inputQty' and @type = 'text']</value>
      <webElementGuid>fe058270-887a-4c9c-9a98-09a8250ace43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
