<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StickyProductImg_pdp</name>
   <tag></tag>
   <elementGuidId>7d35100c-f42b-463c-8210-f004282d454d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[4]/div/div/div/div/div/figure/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.a-stickyBar__image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fd09e6ea-fdbc-4c0f-9320-9619e935b5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss634.liverpool.com.mx/xl/1109136731.jpg</value>
      <webElementGuid>97a8f94f-cd57-4c53-a31a-6b586ad924d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sticky Bar Image</value>
      <webElementGuid>9601a7db-94ad-4aff-9bc4-b4091187951b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-stickyBar__image</value>
      <webElementGuid>9dfc6ccf-3947-4d67-93e2-bcc571b87efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nonclickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab9754e7-8c75-4ea7-82ee-86eed4bf9607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[4]/div[@class=&quot;o-stickyBar__container  show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-1 p-0&quot;]/div[@class=&quot;m-stickyBar__image -selected&quot;]/figure[@class=&quot;m-imageProductMyBag m-figure&quot;]/div[@class=&quot;lazyload-wrapper&quot;]/img[@class=&quot;a-stickyBar__image&quot;]</value>
      <webElementGuid>82a93f78-9bcc-4325-bf6f-470711bd684d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div/div/figure/div/img</value>
      <webElementGuid>fa2eeaa3-d9d7-44c3-87c9-e7d674590169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sticky Bar Image']</value>
      <webElementGuid>e97eb668-33f7-47a0-bfdb-4474ab4476d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>e1908f35-8d34-4ab0-bda9-cd65291e164e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss634.liverpool.com.mx/xl/1109136731.jpg' and @alt = 'Sticky Bar Image']</value>
      <webElementGuid>52be2b28-6c48-4aa3-a5d1-6b3499983418</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
