<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StickyQuntity_pdp</name>
   <tag></tag>
   <elementGuidId>cbb81415-5f2b-4b66-918e-586e6b6987c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-stickyBar__inputQty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='a-stickyBar__inputQty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1541ed45-7dc6-4cb0-95c2-29a5214df7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-stickyBar__inputQty</value>
      <webElementGuid>40b20b47-be50-4507-800a-77e7c077c37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-stickyBar__inputQty </value>
      <webElementGuid>86888b2e-9556-4d88-8264-8a1865bd9460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee66501d-8df2-4913-83a8-744b2e80810a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>92a8f057-cb2a-4b38-b368-d49e81cdf488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b6fa8efb-b4c5-480c-a343-ef95e8c673f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-stickyBar__inputQty&quot;)</value>
      <webElementGuid>c2d8d7a9-00df-48d6-90c7-a8d5787e1f17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a-stickyBar__inputQty']</value>
      <webElementGuid>c88986f4-925e-4094-9ebe-dff44a973e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>d581832d-e6ee-4ae6-a286-8bb712b197f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ccb5086d-7dc3-4ec9-852b-d40cd85a81eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a-stickyBar__inputQty' and @type = 'text']</value>
      <webElementGuid>04d4161e-5d74-4e3f-aa3b-f5db8f9603ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
