<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StickyProductColour_pdp</name>
   <tag></tag>
   <elementGuidId>8fe6b9eb-d56c-4fb3-8ed8-c756ff15ba25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[4]/div/div/div/div[2]/div/div[2]/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-stickyBar__productColor.atom-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e6f025b1-7711-4936-b691-678ff218cac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-stickyBar__productColor atom-color</value>
      <webElementGuid>7b55f974-266f-4bce-81de-fc8dd583f3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>88fb76ec-f59d-42a4-8c4b-70b90bdb4347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>#f7a0ac</value>
      <webElementGuid>4fb1f6e7-d767-42a6-acdd-77030cfc1621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[4]/div[@class=&quot;o-stickyBar__container  show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-xl-5&quot;]/div[@class=&quot;m-stickyBar__info&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-2 text-center a-stickyBar__color -container&quot;]/div[@class=&quot;a-stickyBar__color a-productColor__item&quot;]/a[@class=&quot;a-stickyBar__productColor atom-color&quot;]</value>
      <webElementGuid>7dd5e6fa-2270-475c-a932-af1f4b020902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div[2]/div/div[2]/div[2]/div/a</value>
      <webElementGuid>b1c7c769-4a4c-4f5a-9a7e-259fc8cdec9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>22293e92-a6d7-4c16-9212-7cf9617ea588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>fbacf814-d3c4-452f-84f9-4b92cfef9473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>0cf1bd6f-bce1-4590-a97b-d65366fca57b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
