<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Breadcrum_pdp</name>
   <tag></tag>
   <elementGuidId>e993f1cb-043e-4f21-9904-f66e3448e364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.m-breadcrumb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='m-breadcrumb'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b795f88-770a-4495-9941-8b16de2ee597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-breadcrumb</value>
      <webElementGuid>a8c39e69-7ad4-49bd-8ca5-f6dc99877bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Home   Belleza   Perfumes   Perfumes Mujer </value>
      <webElementGuid>c109cd56-b0ec-4219-be37-1909904cd455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;d-none d-lg-block m-product__BreadCrumb&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row p-0&quot;]/div[@class=&quot;m-breadcrumb&quot;]</value>
      <webElementGuid>d4555e69-d2a0-4e27-847c-0259eb4d77ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[5]/div/div/div/div</value>
      <webElementGuid>a910e5b6-ec1a-4b08-85ed-1eca6fb699d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar ahora'])[1]/following::div[5]</value>
      <webElementGuid>71b1aa0a-95a6-46eb-9337-13ea779dc50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar a mi bolsa'])[1]/following::div[6]</value>
      <webElementGuid>9fee5e21-ae41-4ed6-acee-62ab47679dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div</value>
      <webElementGuid>d8e2a2e6-6d8e-4323-9737-2bf9a10497b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Home   Belleza   Perfumes   Perfumes Mujer ' or . = '  Home   Belleza   Perfumes   Perfumes Mujer ')]</value>
      <webElementGuid>306cc4c2-b06c-407e-8a80-0b382d2d50f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
