<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>description_Mini_PDP</name>
   <tag></tag>
   <elementGuidId>6a315386-79a7-4d37-8bd1-2de90f0fa589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='a-product__paragraphProductDescriptionContentWeb d-none d-lg-block m-0 mt-2 hidedesc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.productDetailTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7d9e3dd-da19-4962-ac49-9e4a34881336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productDetailTab</value>
      <webElementGuid>356fe87e-9fec-42e4-bf1a-3390ea815dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Elegante y exclusiva fragancia para la mujer . Para que todos a tu alrededor noten tu presencia desde el momento en el que llegas, Un perfume, atrevido, seductor y provocador que cautiva tanto por su aspecto indescifrable como por su inquietante y delicioso aroma. Es perfecto para la mujer con personalidad</value>
      <webElementGuid>c03ddf2b-4141-4a4b-85d1-9a135549ad32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o-product__productSpecsDetails&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;m-product__detail pt-4 pb-4 padding-pd&quot;]/div[@class=&quot;tabs-content&quot;]/div[@class=&quot;productDetailTab&quot;]</value>
      <webElementGuid>3e2603fc-55dc-4cba-8035-274a7c396bf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='o-product__productSpecsDetails']/div[2]/div/div/div/div</value>
      <webElementGuid>ffb4ec1f-33c7-4cbb-9934-48a2e843542e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle de producto'])[2]/following::div[5]</value>
      <webElementGuid>76c600fe-9729-44e1-83a6-473b82c75666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/preceding::div[1]</value>
      <webElementGuid>349fbc58-09d7-4869-bf25-2f081888f59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/preceding::div[2]</value>
      <webElementGuid>7932f15d-b4bd-44e3-8836-773743b05bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Elegante y exclusiva fragancia para la mujer . Para que todos a tu alrededor noten tu presencia desde el momento en el que llegas, Un perfume, atrevido, seductor y provocador que cautiva tanto por su aspecto indescifrable como por su inquietante y delicioso aroma. Es perfecto para la mujer con personalidad']/parent::*</value>
      <webElementGuid>850a870b-2054-450b-8a18-559d44ad0983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div/div/div</value>
      <webElementGuid>d12a83c0-14de-401b-8f9d-d6c704287f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Elegante y exclusiva fragancia para la mujer . Para que todos a tu alrededor noten tu presencia desde el momento en el que llegas, Un perfume, atrevido, seductor y provocador que cautiva tanto por su aspecto indescifrable como por su inquietante y delicioso aroma. Es perfecto para la mujer con personalidad' or . = 'Elegante y exclusiva fragancia para la mujer . Para que todos a tu alrededor noten tu presencia desde el momento en el que llegas, Un perfume, atrevido, seductor y provocador que cautiva tanto por su aspecto indescifrable como por su inquietante y delicioso aroma. Es perfecto para la mujer con personalidad')]</value>
      <webElementGuid>97df4593-6be2-408d-8ccc-f1877e9d8470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
