<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productColour1Image_PDP</name>
   <tag></tag>
   <elementGuidId>91e19879-0e9a-47e8-9d96-6be8b3e4c14a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div//img[@src='https://ss553.liverpool.com.mx/xl/1125199743.jpg'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
