<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_-</name>
   <tag></tag>
   <elementGuidId>15cac328-43e3-4b3e-8e68-4b86775d770b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-12.mt-2.mb-3 > div.m-stickyBar__qtyInputs.d-flex > button.a-btn.a-btn--qty.btn-qty.-minus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section/div/main/div[2]/div[6]/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58a7ed77-d373-4fcc-8542-2ee9562d8c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--qty btn-qty -minus</value>
      <webElementGuid>9df35e19-ac16-48b9-b0c6-bdb6ad938f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>b175e313-82c6-4b65-808b-e7b66bdee3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/div[@class=&quot;d-none d-lg-block&quot;]/div[@class=&quot;row o-product__productQty pto&quot;]/div[@class=&quot;col-12 mt-2 mb-3&quot;]/div[@class=&quot;m-stickyBar__qtyInputs d-flex&quot;]/button[@class=&quot;a-btn a-btn--qty btn-qty -minus&quot;]</value>
      <webElementGuid>0a1d6948-da2f-43df-a4e7-d72e46dc9ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/div[6]/div/div[2]/div/button</value>
      <webElementGuid>fbc631f2-e1d9-4608-bc3a-1dd2cdc20709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver disponibilidad en tienda'])[1]/following::button[1]</value>
      <webElementGuid>cebf56b8-03c4-4491-b10b-3c39f78614c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe una opinión'])[1]/following::button[1]</value>
      <webElementGuid>c6de3b5e-d522-4c20-aaea-6627c70826e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::button[1]</value>
      <webElementGuid>67c9cdb8-7fa5-4fcf-b371-c6b456f05b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Negro'])[2]/preceding::button[2]</value>
      <webElementGuid>5d9a37bb-2cd1-45cb-b62f-bf8ea61a0e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/button</value>
      <webElementGuid>061513d7-1114-4ed0-915f-51b423811326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '-' or . = '-')]</value>
      <webElementGuid>b7a3c5e9-bd0d-4012-8060-d2f40be6f9bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
