<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>figure_Solares_o-gallery__pdp--desktop pzlc_674924</name>
   <tag></tag>
   <elementGuidId>c7b558da-b40c-450d-88a6-beac7e298b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>figure.o-gallery__pdp--desktop.pzlcontainermain.d-none.d-lg-block.retain-css-property-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section/div/main/div/div/figure</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>figure</value>
      <webElementGuid>14069045-83d4-45fa-ae68-ca9d891a65b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-gallery__pdp--desktop pzlcontainermain d-none d-lg-block retain-css-property-value</value>
      <webElementGuid>b17466de-7ce2-4591-8b20-7f4f6e0d682e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;min-vh-90&quot;]/div[@class=&quot;carousel o-product__image&quot;]/figure[@class=&quot;o-gallery__pdp--desktop pzlcontainermain d-none d-lg-block retain-css-property-value&quot;]</value>
      <webElementGuid>7a400473-c657-47d4-964b-c197aad2e691</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div/div/figure</value>
      <webElementGuid>92529f85-1f9a-454a-8ffe-03eaf66526c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solares'])[1]/following::figure[1]</value>
      <webElementGuid>1bd9f3e1-e5f7-4b1a-90ca-9ebe0cd41ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lentes'])[1]/following::figure[1]</value>
      <webElementGuid>9760f4d3-c20a-4706-866d-82b467d248f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lentes de sol Perry Ellis Pesun21015 unisex'])[2]/preceding::figure[1]</value>
      <webElementGuid>591de7e5-aa3c-44f2-b9fd-5dec9d896dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe una opinión'])[1]/preceding::figure[1]</value>
      <webElementGuid>fea122b3-113a-4614-ba7e-d5fda0805689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/figure</value>
      <webElementGuid>daec7e7e-1c49-46a6-a309-306b92c129d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
