<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>carousels_pdp</name>
   <tag></tag>
   <elementGuidId>779d0ba8-fb73-4434-8295-f1510001b293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//section[@class='o-carousel plpclp my-carousel'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.o-carousel.plpclp.my-carousel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>3effb5f8-fe55-49d7-83d6-fa38dc223abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-carousel plpclp my-carousel</value>
      <webElementGuid>e8b27e6b-88fa-446e-ade1-e48248b1fe0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Artículos similares Tenis Puma unisex$1,49900 Tenis ADIDAS Showtheway 2.0 unisex para entrenamiento$1,49900 Tenis Puma unisex para correr$1,49900 Tenis ADIDAS The Velosamba Vegan unisex para entrenamiento$2,99900 Tenis Puma unisex para entrenamiento$1,59900 Tenis Puma unisex$1,49900 Tenis ADIDAS Showtheway 2.0 unisex para entrenamiento$1,49900 Tenis Puma unisex para correr$1,49900 Tenis ADIDAS The Velosamba Vegan unisex para entrenamiento$2,99900 Tenis Puma unisex para entrenamiento$1,5990012345</value>
      <webElementGuid>5e2e16da-e718-41ae-86b9-49a9c0446091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[5]/section[@class=&quot;o-carousel-section&quot;]/div[@class=&quot;container-fluid o-carousel-container&quot;]/div[@class=&quot;container p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/section[@class=&quot;o-carousel plpclp my-carousel&quot;]</value>
      <webElementGuid>e922d9a2-ad2e-422d-9799-253e69829899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[5]/section/div/div/div/div/section</value>
      <webElementGuid>b06ea576-67a3-448d-b9bc-9ad69ad26446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opiniones de productos similares'])[1]/following::section[3]</value>
      <webElementGuid>13748843-7f52-4e49-8d91-f9f76d35737d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostrar 20 opiniones más'])[1]/following::section[3]</value>
      <webElementGuid>854ebbc3-0420-4e73-8b91-8a30c7f45dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otros clientes también compraron'])[1]/preceding::section[11]</value>
      <webElementGuid>b6dd249a-d82f-4492-94fb-a676bb6d03b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/section</value>
      <webElementGuid>050f6aaf-e421-490d-b5f4-e0537db92aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Artículos similares Tenis Puma unisex$1,49900 Tenis ADIDAS Showtheway 2.0 unisex para entrenamiento$1,49900 Tenis Puma unisex para correr$1,49900 Tenis ADIDAS The Velosamba Vegan unisex para entrenamiento$2,99900 Tenis Puma unisex para entrenamiento$1,59900 Tenis Puma unisex$1,49900 Tenis ADIDAS Showtheway 2.0 unisex para entrenamiento$1,49900 Tenis Puma unisex para correr$1,49900 Tenis ADIDAS The Velosamba Vegan unisex para entrenamiento$2,99900 Tenis Puma unisex para entrenamiento$1,5990012345' or . = 'Artículos similares Tenis Puma unisex$1,49900 Tenis ADIDAS Showtheway 2.0 unisex para entrenamiento$1,49900 Tenis Puma unisex para correr$1,49900 Tenis ADIDAS The Velosamba Vegan unisex para entrenamiento$2,99900 Tenis Puma unisex para entrenamiento$1,59900 Tenis Puma unisex$1,49900 Tenis ADIDAS Showtheway 2.0 unisex para entrenamiento$1,49900 Tenis Puma unisex para correr$1,49900 Tenis ADIDAS The Velosamba Vegan unisex para entrenamiento$2,99900 Tenis Puma unisex para entrenamiento$1,5990012345')]</value>
      <webElementGuid>a2fdf569-7c7b-4ebe-9b05-254f35a2cc8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
