<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ITRLink_pdp</name>
   <tag></tag>
   <elementGuidId>a7af54e6-7de3-48f0-a039-3fec158697c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='btnGeoStore']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btnGeoStore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>765ecb71-fad9-4df9-8a89-0c97db22462f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnGeoStore</value>
      <webElementGuid>7266a975-d9b1-47ce-8879-afbcc451494e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver disponibilidad en tienda</value>
      <webElementGuid>9aaadbbd-d783-4cef-b61e-9c56433476d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/div[@class=&quot;mt-1&quot;]/div[@class=&quot;btnGeoStore&quot;]</value>
      <webElementGuid>ad81cab8-5f4a-4374-886c-89170605338c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/div[2]/div</value>
      <webElementGuid>faa38b44-952a-4526-9e99-f93b6573cd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe una opinión'])[1]/following::div[3]</value>
      <webElementGuid>28e4e6c5-2cce-498a-ada7-556d9569960f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenis Puma unisex'])[2]/following::div[7]</value>
      <webElementGuid>47d7f9fc-16e3-4886-bcb7-95c65cbee554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::div[11]</value>
      <webElementGuid>5408f849-ff1c-47f8-a5b3-870d772906bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::div[11]</value>
      <webElementGuid>caa714ec-f177-4574-b985-1948b3a335aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver disponibilidad en tienda']/parent::*</value>
      <webElementGuid>4d1a135c-5243-4a7c-aa2f-a8fff0375f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/div[2]/div</value>
      <webElementGuid>e09e6fa8-a594-495e-9b03-e9b341963d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ver disponibilidad en tienda' or . = 'Ver disponibilidad en tienda')]</value>
      <webElementGuid>babcd53e-033a-4571-9ed0-613bde2ebabf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
