<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quantity_pdp</name>
   <tag></tag>
   <elementGuidId>2dd74dd0-83ca-46de-85d9-ecb415b5308e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[(text() = '-+' or . = '-+')])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.mt-2.mb-3 > div.m-stickyBar__qtyInputs.d-flex</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>844614c4-ff60-4e44-b920-bd65178f579f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-stickyBar__qtyInputs d-flex</value>
      <webElementGuid>41f1f096-1df1-4042-b66a-731126f9de5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-+</value>
      <webElementGuid>023c9e4c-41eb-44af-bff9-9ba96df21b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/div[@class=&quot;d-none d-lg-block&quot;]/div[@class=&quot;row o-product__productQty pto&quot;]/div[@class=&quot;col-12 mt-2 mb-3&quot;]/div[@class=&quot;m-stickyBar__qtyInputs d-flex&quot;]</value>
      <webElementGuid>238a8066-71a1-43db-a1ec-d2a5f4260ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/div[6]/div/div[2]/div</value>
      <webElementGuid>1345a317-4999-4e4b-bc81-9e78e8136dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver disponibilidad en tienda'])[1]/following::div[14]</value>
      <webElementGuid>b6904a5c-f50a-467b-8ad4-57108ed1b1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe una opinión'])[1]/following::div[17]</value>
      <webElementGuid>8112c8f8-e232-473a-9fca-2ea87f7748ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div</value>
      <webElementGuid>c33ac0d0-ad76-4509-9f90-ef7a10bda5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '-+' or . = '-+')]</value>
      <webElementGuid>819a366b-232a-49ca-8211-ded2a40eb7d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
