<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Protege tu compra_icon-close close</name>
   <tag></tag>
   <elementGuidId>aeca0d50-1520-45fa-8d26-66bcdcde2c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-header.orderPdpTrackModal > button.close > i.icon-close.close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='waraanty_service-modal']/div/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>548d07d7-23c6-490c-812e-d4288f56bcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-close close</value>
      <webElementGuid>03a39504-033e-4a06-a39b-27b62aceb8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;waraanty_service-modal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header orderPdpTrackModal&quot;]/button[@class=&quot;close&quot;]/i[@class=&quot;icon-close close&quot;]</value>
      <webElementGuid>1f5db5f6-3bbc-4487-a30b-a55aa7ea4f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='waraanty_service-modal']/div/div/div/button/i</value>
      <webElementGuid>c15c3927-3c00-411e-b345-2020711ac816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/button/i</value>
      <webElementGuid>1c4d7f82-375b-4fe6-b562-fcdd6750e799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
