<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>l2Category_blp</name>
   <tag></tag>
   <elementGuidId>33628bc1-9e53-4f48-93f5-959c51704dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@class='nav-sub-link-leftMenu']//a)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70ed3eac-7cf9-4736-8f78-eca1b37eb0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-category__listElement 
                                </value>
      <webElementGuid>0c810f57-e644-4479-a7f9-359925ddce1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/zapatos/catst4003075</value>
      <webElementGuid>d0e9d3f9-e1f4-4b8e-ab9a-2c6ae15f7e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zapatos</value>
      <webElementGuid>48bff72e-bdc6-4c2b-ae7b-5b792041cbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-lg-4 m-aside__content&quot;]/div[@class=&quot;col-12 mr-lg-4 order-2 order-lg-1 mb-3 px-0 o-column__aside&quot;]/div[1]/div[@class=&quot;m-leftMenu-wrapper plp-filter-options active&quot;]/ul[@class=&quot;nav-sub-options-leftMenu pl-40&quot;]/li[@class=&quot;nav-sub-link-leftMenu&quot;]/a[@class=&quot;a-category__listElement&quot;]</value>
      <webElementGuid>6b0c6ea4-2f31-436a-a604-84f1a6d88ffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[4]/aside/div/div/div/ul/li/a</value>
      <webElementGuid>07fa6644-a59c-4bf8-8967-49adb736ecd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Zapatos')])[11]</value>
      <webElementGuid>1de5f92b-2713-4ffe-8d23-ff362fe6fafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mujer'])[8]/following::a[1]</value>
      <webElementGuid>1d70f96d-a079-4c63-95c3-b6ed4f4ed804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mujer'])[7]/following::a[1]</value>
      <webElementGuid>76925b42-eaed-4482-9465-703b3fb65700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bolsas'])[2]/preceding::a[1]</value>
      <webElementGuid>ff1da2d9-b02e-4990-a4a0-de9c364afa87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropa'])[3]/preceding::a[2]</value>
      <webElementGuid>56396ad2-6cff-463c-9395-ebf364ff7ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tienda/zapatos/catst4003075')]</value>
      <webElementGuid>b7c8d30b-0f29-4730-b00b-c7a88073ed6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div/ul/li/a</value>
      <webElementGuid>f6f1e75c-bc97-4bce-8df9-ce098bdc4bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/zapatos/catst4003075' and (text() = 'Zapatos' or . = 'Zapatos')]</value>
      <webElementGuid>147acb8d-3004-47a1-bd93-c1691c43e580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
