<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_slp</name>
   <tag></tag>
   <elementGuidId>2cbdc6d5-66ea-4b4e-8e92-8fc9edb9f79a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filters-storeLocator-storeInformation']/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-product__anchorSelectState</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce6370c1-bef3-479d-947f-b0fb7b6a1e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-product__anchorSelectState</value>
      <webElementGuid>67599fa8-ec0d-43b2-8c57-beb960d3c15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>4750f516-45c5-4816-8423-24a30d306c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#availability-modal</value>
      <webElementGuid>4d53d7d4-93d8-4829-b83e-40360ba40ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/home#!</value>
      <webElementGuid>de4c41bc-ea3f-4e28-8137-a617f0198406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AGUASCALIENTES</value>
      <webElementGuid>a12c9656-3d53-4d32-a5bb-22718c392530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filters-storeLocator-storeInformation&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content storeInformation_modal&quot;]/div[@class=&quot;modal-body p-0 select_states-body&quot;]/a[@class=&quot;a-product__anchorSelectState&quot;]</value>
      <webElementGuid>105275c1-d6f2-44dd-9f7a-e55a87b3e8c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filters-storeLocator-storeInformation']/div/div/div[2]/a</value>
      <webElementGuid>7f73802a-7074-45f7-9ae2-afccfad24048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AGUASCALIENTES')]</value>
      <webElementGuid>6bbdbd99-f158-4a94-9a1d-86abfb2f968f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona tu estado'])[2]/following::a[1]</value>
      <webElementGuid>7e8e2f78-c563-4b0f-9e20-8bab2014262c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/following::a[1]</value>
      <webElementGuid>dfab8511-818e-4beb-bd0c-b94ca3af75ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJA CALIFORNIA'])[1]/preceding::a[1]</value>
      <webElementGuid>83264edc-e7a8-460f-a4a2-f41b67143161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJA CALIFORNIA SUR'])[1]/preceding::a[2]</value>
      <webElementGuid>63c21e1d-5b92-4c4e-9a0a-d598b0b71e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AGUASCALIENTES']/parent::*</value>
      <webElementGuid>dcde1598-3f7f-4342-8bbd-a35523dfa742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/home#!')])[650]</value>
      <webElementGuid>28f557f9-b4de-4f26-b433-d0eccb9d0600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/a</value>
      <webElementGuid>b18ba931-1e79-4fa6-99a1-553656d95b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/home#!' and (text() = 'AGUASCALIENTES' or . = 'AGUASCALIENTES')]</value>
      <webElementGuid>dc1766dd-bc29-4660-bc32-e7109155d99b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
