<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stores_List_slp</name>
   <tag></tag>
   <elementGuidId>c3dccfbc-e206-41fc-9154-8d8ddf0b600c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='store-86']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#store-86</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>648643cb-2cd0-4ec7-b928-a9adf44c9ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>store-86</value>
      <webElementGuid>a2a57b37-a987-40d2-a0f1-7c7713d6839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-radio__input mdc-radio__native-control</value>
      <webElementGuid>cdeedfb5-29c1-42b1-ad9e-45af1d086546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ddb20d05-0738-4ea6-82f8-571a4d85a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2468c3eb-2364-46c9-909a-156381b34a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Stores-list</value>
      <webElementGuid>ded7d636-0b48-4d42-9a8c-7a8a285d2c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>store-86</value>
      <webElementGuid>b984cdad-13fb-4cbd-8b58-7dc68666001e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store-86&quot;)</value>
      <webElementGuid>d7fd1efc-a000-4a02-9c94-146b7f4e7f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='store-86']</value>
      <webElementGuid>ffe98abd-e41e-455a-8579-e0826d0bc62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectStore-modal']/div/div/div[2]/div/div[2]/div[3]/div/div/div/ul/li/div/div/input</value>
      <webElementGuid>d67332f1-f639-49bd-ba34-ea7de71f557b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/input</value>
      <webElementGuid>4a28451b-e5a2-4dc6-be16-b75998fc17a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'store-86' and @type = 'radio' and @name = 'Stores-list']</value>
      <webElementGuid>9f1d1c3b-14be-442c-b7b1-1f31a28d00b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='store-84']</value>
      <webElementGuid>e726b98a-10a6-4440-8712-a81975ea9823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'store-84' and @type = 'radio' and @name = 'Stores-list']</value>
      <webElementGuid>06100a2a-821f-44a1-9c20-ef4ede819121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
