<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_vaso</name>
   <tag></tag>
   <elementGuidId>569f120a-dff6-4bd2-9931-aa1a2ee6af2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-breadcrumb__label.6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]/div/div/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ff33f1a-46ee-43f2-bab5-9e03dc2a10dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-breadcrumb__label 6</value>
      <webElementGuid>de7fc8df-f671-4d8f-968b-7be2ba41cb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda?s=vaso#!</value>
      <webElementGuid>177db85d-e6e0-46a1-ae50-1ae77907346e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>vaso</value>
      <webElementGuid>f77ecc1e-a3a1-4805-a5c6-a5d861ec90bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row d-none d-lg-block m-row-bootstrap&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row p-0&quot;]/div[@class=&quot;m-breadcrumb&quot;]/ul[@class=&quot;m-breadcrumb-list&quot;]/li[@class=&quot;active&quot;]/a[@class=&quot;a-breadcrumb__label 6&quot;]</value>
      <webElementGuid>1dd5f555-f916-4376-9586-eb11f09def06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>e62de0b4-e675-4f9a-a9aa-40018d0ae2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'vaso')]</value>
      <webElementGuid>6db2377d-07f2-4b84-9336-30ed627ff26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>0219ef07-6ef2-4764-aa43-76332bacd470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar'])[1]/following::a[2]</value>
      <webElementGuid>3eb5d330-c680-48c4-86af-015b9da3f827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='vaso']/parent::*</value>
      <webElementGuid>9a98fa9e-ddb3-4fae-9716-4f2087a6c18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda?s=vaso#!')])[4]</value>
      <webElementGuid>e355b191-24d5-48fc-8e24-9f24e50e1888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>d216b76e-e043-4dc7-becd-f9c56ac4b9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda?s=vaso#!' and (text() = 'vaso' or . = 'vaso')]</value>
      <webElementGuid>f4b6e7a3-ef97-4cb3-989d-45330e3db814</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
