<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Banana Search Button</name>
   <tag></tag>
   <elementGuidId>655a9f64-fd9b-464b-93a6-63954f8f195d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon-zoom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/header/div[4]/div[2]/div/div/div/div[3]/div/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>64f80b10-5b73-4d40-9aea-41d5730c96ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-zoom</value>
      <webElementGuid>47e8fc15-a29b-4059-bd14-50c02abfa01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[1]/div[@class=&quot;o-header&quot;]/div[@class=&quot;o-container__fluid container-fluid&quot;]/div[@class=&quot;o-container container p-0&quot;]/div[@class=&quot;m-searchBar&quot;]/div[@class=&quot;o-checkout__header o-row row align-items-center no-gutters py-3 py-lg-2&quot;]/div[@class=&quot;o-col col-lg order-4 order-lg-2 pt-3 pt-lg-0&quot;]/div[@class=&quot;m-header__searchBar&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-append&quot;]/button[@class=&quot;input-group-text&quot;]/i[@class=&quot;icon-zoom&quot;]</value>
      <webElementGuid>dc73638a-caab-4866-8191-e5f92a12d3ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[4]/div[2]/div/div/div/div[3]/div/div/div/button/i</value>
      <webElementGuid>06b5ace6-2132-4a28-aaed-9acbd2db4d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button/i</value>
      <webElementGuid>54bf6e10-b00c-4100-b5ae-f5260cd7b1a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
