<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Total_a-myBagImageProduct</name>
   <tag></tag>
   <elementGuidId>17b6b7dc-cfd2-4095-a3bf-18470c3c34e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1029509103']/div/div/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.a-myBagImageProduct</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>baf77cc6-ad80-41f3-88d5-7952eedeccc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/images/filler_REC.gif</value>
      <webElementGuid>2e4a0891-4eef-4faa-956e-b957159cdccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>alt-Description</value>
      <webElementGuid>0a3ee89c-4406-4b41-9ef0-2b7ab4632857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-myBagImageProduct</value>
      <webElementGuid>c3e976fa-3d46-4fdb-a85e-ce3ef159f96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nonclickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6905590-5acd-4ca8-8c78-d29051a64fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1029509103&quot;)/div[@class=&quot;o-myBag__column o-myBag__column--triple&quot;]/div[@class=&quot;o-myBag__image&quot;]/figure[@class=&quot;m-imageProductMyBag&quot;]/img[@class=&quot;a-myBagImageProduct&quot;]</value>
      <webElementGuid>199db851-0f83-4a4d-b5c7-dab97b2748d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1029509103']/div/div/figure/img</value>
      <webElementGuid>9dd483eb-dfb8-48bd-956f-461ad1a6528f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='alt-Description']</value>
      <webElementGuid>24eb9fae-8a13-4439-acf9-cb1862c525c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/figure/img</value>
      <webElementGuid>c7f9a7a6-6938-4028-ab6c-d179bbfc94a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assetspwa.liverpool.com.mx/assets/images/filler_REC.gif' and @alt = 'alt-Description']</value>
      <webElementGuid>a6d75146-8235-4519-8263-e44783a475ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
