<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_mainSearchbar</name>
   <tag></tag>
   <elementGuidId>e214329d-3545-4e9c-b66b-4cff6b88aa98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='mainSearchbar'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.m-stickyBar__qtyInputs-OCP > #mainSearchbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80f5d670-70f0-4b6a-8159-2b811c4d8749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainSearchbar</value>
      <webElementGuid>0d0b59f1-ffe5-4264-8063-29978a0930e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-ProductQty__input</value>
      <webElementGuid>683efdfd-3766-491b-a6e9-39185cca0514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>daa13f42-163e-4c8e-a38f-833d236850ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e33392ba-d4ba-4c9a-8afb-e5e257204185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>15eee0de-1c17-4971-9d4b-9d357caea6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d0e55e63-a023-4641-a8ca-d9c152ec0eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>061a4feb-5d4e-4078-adf0-c693ac3dee51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1029509103&quot;)/div[@class=&quot;o-myBag__column&quot;]/div[@class=&quot;m-product m-product-qty&quot;]/div[@class=&quot;m-product__qty p-0 m-0&quot;]/div[@class=&quot;row m-stickyBar__mobile m_stickyBar_position m_stickyBar__opc&quot;]/div[@class=&quot;m-0 m-stickyBar__qty-mobile&quot;]/div[@class=&quot;m-stickyBar__qtyInputs-OCP&quot;]/input[@id=&quot;mainSearchbar&quot;]</value>
      <webElementGuid>eabacbcd-eb0e-40fb-88df-add17814467e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='mainSearchbar'])[2]</value>
      <webElementGuid>a5fb844f-51c7-4995-b319-d8071608691c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1029509103']/div[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>4a25b74f-77ab-4f0c-9ab5-70b8d38e82e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>02ed4126-7d20-46fc-844c-965f3086d051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mainSearchbar' and @type = 'tel']</value>
      <webElementGuid>b664b427-01a1-4dee-bc9f-903a826abdd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
