<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1</name>
   <tag></tag>
   <elementGuidId>4d378fbd-2185-4e95-b8b3-00b14c8e3c0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.a-inlineElement.-quantityReadOnly.quantityReadOnlyPdpValidation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1041990381']/div[3]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e79923c3-d70e-4a89-bdc6-5b9f8da8cc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-inlineElement -quantityReadOnly quantityReadOnlyPdpValidation</value>
      <webElementGuid>d616b76e-eda4-46f5-9969-d59eaf971d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>917d3aa2-de00-47d5-a3aa-6c335acdf924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1041990381&quot;)/div[@class=&quot;o-myBag__column&quot;]/div[@class=&quot;m-product m-product-qty&quot;]/div[1]/label[@class=&quot;a-inlineElement -quantityReadOnly quantityReadOnlyPdpValidation&quot;]</value>
      <webElementGuid>c93dd974-fd41-4e21-a011-326ad91d27cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1041990381']/div[3]/div/div/label</value>
      <webElementGuid>34190973-0029-4932-9e42-8d0529e90f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[1]/following::label[1]</value>
      <webElementGuid>7fab6564-8b73-4341-8f35-55f10d5d06fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar ahora'])[1]/following::label[1]</value>
      <webElementGuid>16f75a0f-1a7e-4e47-82a5-aed42b70569a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se puede asociar a mesa de regalo'])[1]/preceding::label[1]</value>
      <webElementGuid>a610084b-5909-4999-822c-aba4674a14ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar ahora'])[2]/preceding::label[1]</value>
      <webElementGuid>61426100-e444-401c-85c4-a5bae561e93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>782823c3-288e-4063-8d0b-faaf59eda4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>c31991e0-4e79-498f-91a4-f49b78038547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '1' or . = '1')]</value>
      <webElementGuid>d52cee58-4645-482f-9413-dade2ecafdec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
