<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Blusa</name>
   <tag></tag>
   <elementGuidId>37ce6230-909a-4735-9648-6f305077de82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1029509103']/div/div[2]/span/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.a-inlineElement.a-inlineElement--enphasis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>45ca5bdf-7718-4cd2-b785-3884fd9e3de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-inlineElement a-inlineElement--enphasis</value>
      <webElementGuid>08439e82-29e4-43a7-ad58-b869e24fb511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blusa</value>
      <webElementGuid>dfcc4e3f-c476-4925-b8e7-799f9e0866d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1029509103&quot;)/div[@class=&quot;o-myBag__column o-myBag__column--triple&quot;]/div[@class=&quot;o-myBag__description&quot;]/span[1]/p[@class=&quot;a-inlineElement a-inlineElement--enphasis&quot;]</value>
      <webElementGuid>db9aa8f4-92a6-417a-8630-2cff8c2bd96e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1029509103']/div/div[2]/span/p</value>
      <webElementGuid>da6c2c02-2d70-41a8-8d29-37fef6ada26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::p[1]</value>
      <webElementGuid>5d43833d-28b1-4c57-bdff-8c94c3ac4e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad'])[1]/following::p[1]</value>
      <webElementGuid>3ee36c44-8200-4994-8625-a8112128a298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Envolver para regalo?'])[1]/preceding::p[5]</value>
      <webElementGuid>77df46cb-6399-442c-8ad3-51f6d6734f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar para mesa de regalos'])[1]/preceding::p[5]</value>
      <webElementGuid>61eceba5-2b8a-48e5-8f9b-3289b4d79a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blusa']/parent::*</value>
      <webElementGuid>2f100796-174c-4075-8b56-5f3488326d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>1ac65da5-28cc-4e89-b4fe-75a5664dbc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Blusa' or . = 'Blusa')]</value>
      <webElementGuid>7bd8a37a-46f5-4c5c-86a0-123a40f40f09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
